// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: creator_payout_account.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getCreatorPayoutAccount = `-- name: GetCreatorPayoutAccount :one
SELECT creator_id, bank_bin, bank_code, bank_short_name, bank_name, bank_logo, account_number, account_name, verified_at, created_at, updated_at FROM creator_payout_accounts
WHERE creator_id = $1
LIMIT 1
`

func (q *Queries) GetCreatorPayoutAccount(ctx context.Context, creatorID uuid.UUID) (CreatorPayoutAccount, error) {
	row := q.db.QueryRowContext(ctx, getCreatorPayoutAccount, creatorID)
	var i CreatorPayoutAccount
	err := row.Scan(
		&i.CreatorID,
		&i.BankBin,
		&i.BankCode,
		&i.BankShortName,
		&i.BankName,
		&i.BankLogo,
		&i.AccountNumber,
		&i.AccountName,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCreatorPayoutAccount = `-- name: UpsertCreatorPayoutAccount :one
INSERT INTO creator_payout_accounts (
    creator_id,
    bank_bin,
    bank_code,
    bank_short_name,
    bank_name,
    bank_logo,
    account_number,
    account_name,
    verified_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NULL
)
ON CONFLICT (creator_id) DO UPDATE
SET bank_bin = EXCLUDED.bank_bin,
    bank_code = EXCLUDED.bank_code,
    bank_short_name = EXCLUDED.bank_short_name,
    bank_name = EXCLUDED.bank_name,
    bank_logo = EXCLUDED.bank_logo,
    account_number = EXCLUDED.account_number,
    account_name = EXCLUDED.account_name,
    verified_at = NULL,
    updated_at = CURRENT_TIMESTAMP
RETURNING creator_id, bank_bin, bank_code, bank_short_name, bank_name, bank_logo, account_number, account_name, verified_at, created_at, updated_at
`

type UpsertCreatorPayoutAccountParams struct {
	CreatorID     uuid.UUID      `json:"creator_id"`
	BankBin       string         `json:"bank_bin"`
	BankCode      string         `json:"bank_code"`
	BankShortName string         `json:"bank_short_name"`
	BankName      string         `json:"bank_name"`
	BankLogo      sql.NullString `json:"bank_logo"`
	AccountNumber string         `json:"account_number"`
	AccountName   string         `json:"account_name"`
}

func (q *Queries) UpsertCreatorPayoutAccount(ctx context.Context, arg UpsertCreatorPayoutAccountParams) (CreatorPayoutAccount, error) {
	row := q.db.QueryRowContext(ctx, upsertCreatorPayoutAccount,
		arg.CreatorID,
		arg.BankBin,
		arg.BankCode,
		arg.BankShortName,
		arg.BankName,
		arg.BankLogo,
		arg.AccountNumber,
		arg.AccountName,
	)
	var i CreatorPayoutAccount
	err := row.Scan(
		&i.CreatorID,
		&i.BankBin,
		&i.BankCode,
		&i.BankShortName,
		&i.BankName,
		&i.BankLogo,
		&i.AccountNumber,
		&i.AccountName,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
