// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: creator_balance.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCreatorWithdrawal = `-- name: CreateCreatorWithdrawal :one
INSERT INTO creator_withdrawals (
    creator_id,
    amount_vnd,
    status,
    payout_reference_id,
    payout_idempotency_key,
    payout_to_bin,
    payout_to_account_number,
    payout_to_account_name
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING withdrawal_id, creator_id, amount_vnd, status, requested_at, paid_at, payout_reference_id, payout_idempotency_key, payout_to_bin, payout_to_account_number, payout_to_account_name, payos_payout_id, payos_payout_transaction_id, payos_payout_state, payout_raw_payload, payout_failed_reason
`

type CreateCreatorWithdrawalParams struct {
	CreatorID             uuid.UUID      `json:"creator_id"`
	AmountVnd             int64          `json:"amount_vnd"`
	Status                string         `json:"status"`
	PayoutReferenceID     sql.NullString `json:"payout_reference_id"`
	PayoutIdempotencyKey  sql.NullString `json:"payout_idempotency_key"`
	PayoutToBin           sql.NullString `json:"payout_to_bin"`
	PayoutToAccountNumber sql.NullString `json:"payout_to_account_number"`
	PayoutToAccountName   sql.NullString `json:"payout_to_account_name"`
}

func (q *Queries) CreateCreatorWithdrawal(ctx context.Context, arg CreateCreatorWithdrawalParams) (CreatorWithdrawal, error) {
	row := q.db.QueryRowContext(ctx, createCreatorWithdrawal,
		arg.CreatorID,
		arg.AmountVnd,
		arg.Status,
		arg.PayoutReferenceID,
		arg.PayoutIdempotencyKey,
		arg.PayoutToBin,
		arg.PayoutToAccountNumber,
		arg.PayoutToAccountName,
	)
	var i CreatorWithdrawal
	err := row.Scan(
		&i.WithdrawalID,
		&i.CreatorID,
		&i.AmountVnd,
		&i.Status,
		&i.RequestedAt,
		&i.PaidAt,
		&i.PayoutReferenceID,
		&i.PayoutIdempotencyKey,
		&i.PayoutToBin,
		&i.PayoutToAccountNumber,
		&i.PayoutToAccountName,
		&i.PayosPayoutID,
		&i.PayosPayoutTransactionID,
		&i.PayosPayoutState,
		&i.PayoutRawPayload,
		&i.PayoutFailedReason,
	)
	return i, err
}

const getCreatorBalanceSummary = `-- name: GetCreatorBalanceSummary :one
SELECT
    COALESCE(SUM(CASE WHEN cbt.source_type = 'earning_credit' AND cbt.status = 'posted' THEN cbt.amount_vnd ELSE 0 END), 0)::bigint AS total_earned_amount_vnd,
    COALESCE(SUM(CASE WHEN cbt.source_type = 'withdrawal' AND (cbt.status = 'posted' OR w.status = 'paid') THEN -cbt.amount_vnd ELSE 0 END), 0)::bigint AS total_withdrawn_amount_vnd,
    COALESCE(SUM(CASE WHEN cbt.source_type = 'withdrawal' AND cbt.status = 'reserved' AND COALESCE(w.status, '') NOT IN ('paid', 'failed') THEN -cbt.amount_vnd ELSE 0 END), 0)::bigint AS pending_withdrawal_amount_vnd,
    (
        COALESCE(SUM(CASE WHEN cbt.source_type = 'earning_credit' AND cbt.status = 'posted' THEN cbt.amount_vnd ELSE 0 END), 0)
        - COALESCE(SUM(CASE WHEN cbt.source_type = 'withdrawal' AND (cbt.status = 'posted' OR w.status = 'paid') THEN -cbt.amount_vnd ELSE 0 END), 0)
        - COALESCE(SUM(CASE WHEN cbt.source_type = 'withdrawal' AND cbt.status = 'reserved' AND COALESCE(w.status, '') NOT IN ('paid', 'failed') THEN -cbt.amount_vnd ELSE 0 END), 0)
    )::bigint AS available_balance_vnd
FROM creator_balance_transactions cbt
LEFT JOIN creator_withdrawals w
    ON cbt.source_type = 'withdrawal'
   AND cbt.source_id = w.withdrawal_id::text
WHERE cbt.creator_id = $1
`

type GetCreatorBalanceSummaryRow struct {
	TotalEarnedAmountVnd       int64 `json:"total_earned_amount_vnd"`
	TotalWithdrawnAmountVnd    int64 `json:"total_withdrawn_amount_vnd"`
	PendingWithdrawalAmountVnd int64 `json:"pending_withdrawal_amount_vnd"`
	AvailableBalanceVnd        int64 `json:"available_balance_vnd"`
}

func (q *Queries) GetCreatorBalanceSummary(ctx context.Context, creatorID uuid.UUID) (GetCreatorBalanceSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getCreatorBalanceSummary, creatorID)
	var i GetCreatorBalanceSummaryRow
	err := row.Scan(
		&i.TotalEarnedAmountVnd,
		&i.TotalWithdrawnAmountVnd,
		&i.PendingWithdrawalAmountVnd,
		&i.AvailableBalanceVnd,
	)
	return i, err
}

const getCreatorWithdrawalByID = `-- name: GetCreatorWithdrawalByID :one
SELECT withdrawal_id, creator_id, amount_vnd, status, requested_at, paid_at, payout_reference_id, payout_idempotency_key, payout_to_bin, payout_to_account_number, payout_to_account_name, payos_payout_id, payos_payout_transaction_id, payos_payout_state, payout_raw_payload, payout_failed_reason FROM creator_withdrawals
WHERE withdrawal_id = $1
LIMIT 1
`

func (q *Queries) GetCreatorWithdrawalByID(ctx context.Context, withdrawalID uuid.UUID) (CreatorWithdrawal, error) {
	row := q.db.QueryRowContext(ctx, getCreatorWithdrawalByID, withdrawalID)
	var i CreatorWithdrawal
	err := row.Scan(
		&i.WithdrawalID,
		&i.CreatorID,
		&i.AmountVnd,
		&i.Status,
		&i.RequestedAt,
		&i.PaidAt,
		&i.PayoutReferenceID,
		&i.PayoutIdempotencyKey,
		&i.PayoutToBin,
		&i.PayoutToAccountNumber,
		&i.PayoutToAccountName,
		&i.PayosPayoutID,
		&i.PayosPayoutTransactionID,
		&i.PayosPayoutState,
		&i.PayoutRawPayload,
		&i.PayoutFailedReason,
	)
	return i, err
}

const listCreatorBalanceHistory = `-- name: ListCreatorBalanceHistory :many
SELECT
    cbt.transaction_id,
    cbt.source_type,
    cbt.source_id,
    cbt.amount_vnd,
    cbt.status AS ledger_status,
    cbt.pool_month,
    cbt.created_at,
    cbt.updated_at,
    ce.earning_id,
    ce.eligible_learners,
    ce.weighted_score,
    ce.status AS earning_status,
    w.withdrawal_id,
    w.amount_vnd AS withdrawal_amount_vnd,
    w.status AS withdrawal_status,
    w.requested_at AS withdrawal_requested_at,
    w.paid_at AS withdrawal_paid_at,
    w.payout_to_bin,
    w.payout_to_account_number,
    w.payout_to_account_name,
    w.payos_payout_id,
    w.payos_payout_transaction_id,
    w.payos_payout_state,
    w.payout_failed_reason
FROM creator_balance_transactions cbt
LEFT JOIN creator_earnings ce
    ON cbt.source_type = 'earning_credit'
   AND cbt.source_id = ce.earning_id::text
LEFT JOIN creator_withdrawals w
    ON cbt.source_type = 'withdrawal'
   AND cbt.source_id = w.withdrawal_id::text
WHERE cbt.creator_id = $1
ORDER BY COALESCE(w.requested_at, cbt.pool_month, cbt.created_at) DESC,
         cbt.created_at DESC
LIMIT $3 OFFSET $2
`

type ListCreatorBalanceHistoryParams struct {
	CreatorID  uuid.UUID `json:"creator_id"`
	OffsetRows int32     `json:"offset_rows"`
	LimitRows  int32     `json:"limit_rows"`
}

type ListCreatorBalanceHistoryRow struct {
	TransactionID            uuid.UUID      `json:"transaction_id"`
	SourceType               string         `json:"source_type"`
	SourceID                 string         `json:"source_id"`
	AmountVnd                int64          `json:"amount_vnd"`
	LedgerStatus             string         `json:"ledger_status"`
	PoolMonth                sql.NullTime   `json:"pool_month"`
	CreatedAt                time.Time      `json:"created_at"`
	UpdatedAt                time.Time      `json:"updated_at"`
	EarningID                uuid.NullUUID  `json:"earning_id"`
	EligibleLearners         sql.NullInt32  `json:"eligible_learners"`
	WeightedScore            sql.NullString `json:"weighted_score"`
	EarningStatus            sql.NullString `json:"earning_status"`
	WithdrawalID             uuid.NullUUID  `json:"withdrawal_id"`
	WithdrawalAmountVnd      sql.NullInt64  `json:"withdrawal_amount_vnd"`
	WithdrawalStatus         sql.NullString `json:"withdrawal_status"`
	WithdrawalRequestedAt    sql.NullTime   `json:"withdrawal_requested_at"`
	WithdrawalPaidAt         sql.NullTime   `json:"withdrawal_paid_at"`
	PayoutToBin              sql.NullString `json:"payout_to_bin"`
	PayoutToAccountNumber    sql.NullString `json:"payout_to_account_number"`
	PayoutToAccountName      sql.NullString `json:"payout_to_account_name"`
	PayosPayoutID            sql.NullString `json:"payos_payout_id"`
	PayosPayoutTransactionID sql.NullString `json:"payos_payout_transaction_id"`
	PayosPayoutState         sql.NullString `json:"payos_payout_state"`
	PayoutFailedReason       sql.NullString `json:"payout_failed_reason"`
}

func (q *Queries) ListCreatorBalanceHistory(ctx context.Context, arg ListCreatorBalanceHistoryParams) ([]ListCreatorBalanceHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listCreatorBalanceHistory, arg.CreatorID, arg.OffsetRows, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCreatorBalanceHistoryRow{}
	for rows.Next() {
		var i ListCreatorBalanceHistoryRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.SourceType,
			&i.SourceID,
			&i.AmountVnd,
			&i.LedgerStatus,
			&i.PoolMonth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EarningID,
			&i.EligibleLearners,
			&i.WeightedScore,
			&i.EarningStatus,
			&i.WithdrawalID,
			&i.WithdrawalAmountVnd,
			&i.WithdrawalStatus,
			&i.WithdrawalRequestedAt,
			&i.WithdrawalPaidAt,
			&i.PayoutToBin,
			&i.PayoutToAccountNumber,
			&i.PayoutToAccountName,
			&i.PayosPayoutID,
			&i.PayosPayoutTransactionID,
			&i.PayosPayoutState,
			&i.PayoutFailedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreatorBalanceTransactionStatus = `-- name: UpdateCreatorBalanceTransactionStatus :one
UPDATE creator_balance_transactions
SET status = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE source_type = $2
  AND source_id = $3
RETURNING transaction_id, creator_id, source_type, source_id, amount_vnd, status, pool_month, created_at, updated_at
`

type UpdateCreatorBalanceTransactionStatusParams struct {
	Status     string `json:"status"`
	SourceType string `json:"source_type"`
	SourceID   string `json:"source_id"`
}

func (q *Queries) UpdateCreatorBalanceTransactionStatus(ctx context.Context, arg UpdateCreatorBalanceTransactionStatusParams) (CreatorBalanceTransaction, error) {
	row := q.db.QueryRowContext(ctx, updateCreatorBalanceTransactionStatus, arg.Status, arg.SourceType, arg.SourceID)
	var i CreatorBalanceTransaction
	err := row.Scan(
		&i.TransactionID,
		&i.CreatorID,
		&i.SourceType,
		&i.SourceID,
		&i.AmountVnd,
		&i.Status,
		&i.PoolMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCreatorWithdrawalStatus = `-- name: UpdateCreatorWithdrawalStatus :one
UPDATE creator_withdrawals
SET status = $1::text,
    paid_at = CASE WHEN $1::text = 'paid' THEN CURRENT_TIMESTAMP ELSE paid_at END,
    payos_payout_id = COALESCE($2, payos_payout_id),
    payos_payout_transaction_id = COALESCE($3, payos_payout_transaction_id),
    payos_payout_state = COALESCE($4, payos_payout_state),
    payout_raw_payload = $5::text::jsonb,
    payout_failed_reason = $6
WHERE withdrawal_id = $7
RETURNING withdrawal_id, creator_id, amount_vnd, status, requested_at, paid_at, payout_reference_id, payout_idempotency_key, payout_to_bin, payout_to_account_number, payout_to_account_name, payos_payout_id, payos_payout_transaction_id, payos_payout_state, payout_raw_payload, payout_failed_reason
`

type UpdateCreatorWithdrawalStatusParams struct {
	Status                   string         `json:"status"`
	PayosPayoutID            sql.NullString `json:"payos_payout_id"`
	PayosPayoutTransactionID sql.NullString `json:"payos_payout_transaction_id"`
	PayosPayoutState         sql.NullString `json:"payos_payout_state"`
	PayoutRawPayload         string         `json:"payout_raw_payload"`
	PayoutFailedReason       sql.NullString `json:"payout_failed_reason"`
	WithdrawalID             uuid.UUID      `json:"withdrawal_id"`
}

func (q *Queries) UpdateCreatorWithdrawalStatus(ctx context.Context, arg UpdateCreatorWithdrawalStatusParams) (CreatorWithdrawal, error) {
	row := q.db.QueryRowContext(ctx, updateCreatorWithdrawalStatus,
		arg.Status,
		arg.PayosPayoutID,
		arg.PayosPayoutTransactionID,
		arg.PayosPayoutState,
		arg.PayoutRawPayload,
		arg.PayoutFailedReason,
		arg.WithdrawalID,
	)
	var i CreatorWithdrawal
	err := row.Scan(
		&i.WithdrawalID,
		&i.CreatorID,
		&i.AmountVnd,
		&i.Status,
		&i.RequestedAt,
		&i.PaidAt,
		&i.PayoutReferenceID,
		&i.PayoutIdempotencyKey,
		&i.PayoutToBin,
		&i.PayoutToAccountNumber,
		&i.PayoutToAccountName,
		&i.PayosPayoutID,
		&i.PayosPayoutTransactionID,
		&i.PayosPayoutState,
		&i.PayoutRawPayload,
		&i.PayoutFailedReason,
	)
	return i, err
}

const upsertCreatorEarningCreditTransaction = `-- name: UpsertCreatorEarningCreditTransaction :one
INSERT INTO creator_balance_transactions (
    creator_id,
    source_type,
    source_id,
    amount_vnd,
    status,
    pool_month
)
VALUES (
    $1,
    'earning_credit',
    $2,
    $3,
    'posted',
    $4
)
ON CONFLICT (source_type, source_id) DO UPDATE
SET amount_vnd = EXCLUDED.amount_vnd,
    status = 'posted',
    pool_month = EXCLUDED.pool_month,
    updated_at = CURRENT_TIMESTAMP
RETURNING transaction_id, creator_id, source_type, source_id, amount_vnd, status, pool_month, created_at, updated_at
`

type UpsertCreatorEarningCreditTransactionParams struct {
	CreatorID uuid.UUID    `json:"creator_id"`
	SourceID  string       `json:"source_id"`
	AmountVnd int64        `json:"amount_vnd"`
	PoolMonth sql.NullTime `json:"pool_month"`
}

func (q *Queries) UpsertCreatorEarningCreditTransaction(ctx context.Context, arg UpsertCreatorEarningCreditTransactionParams) (CreatorBalanceTransaction, error) {
	row := q.db.QueryRowContext(ctx, upsertCreatorEarningCreditTransaction,
		arg.CreatorID,
		arg.SourceID,
		arg.AmountVnd,
		arg.PoolMonth,
	)
	var i CreatorBalanceTransaction
	err := row.Scan(
		&i.TransactionID,
		&i.CreatorID,
		&i.SourceType,
		&i.SourceID,
		&i.AmountVnd,
		&i.Status,
		&i.PoolMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCreatorWithdrawalReservation = `-- name: UpsertCreatorWithdrawalReservation :one
INSERT INTO creator_balance_transactions (
    creator_id,
    source_type,
    source_id,
    amount_vnd,
    status
)
VALUES (
    $1,
    'withdrawal',
    $2,
    $3,
    $4
)
ON CONFLICT (source_type, source_id) DO UPDATE
SET amount_vnd = EXCLUDED.amount_vnd,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP
RETURNING transaction_id, creator_id, source_type, source_id, amount_vnd, status, pool_month, created_at, updated_at
`

type UpsertCreatorWithdrawalReservationParams struct {
	CreatorID uuid.UUID `json:"creator_id"`
	SourceID  string    `json:"source_id"`
	AmountVnd int64     `json:"amount_vnd"`
	Status    string    `json:"status"`
}

func (q *Queries) UpsertCreatorWithdrawalReservation(ctx context.Context, arg UpsertCreatorWithdrawalReservationParams) (CreatorBalanceTransaction, error) {
	row := q.db.QueryRowContext(ctx, upsertCreatorWithdrawalReservation,
		arg.CreatorID,
		arg.SourceID,
		arg.AmountVnd,
		arg.Status,
	)
	var i CreatorBalanceTransaction
	err := row.Scan(
		&i.TransactionID,
		&i.CreatorID,
		&i.SourceType,
		&i.SourceID,
		&i.AmountVnd,
		&i.Status,
		&i.PoolMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
