// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revenue.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCreatorEarning = `-- name: CreateCreatorEarning :one
INSERT INTO creator_earnings (
    pool_month,
    creator_id,
    eligible_learners,
    weighted_score,
    amount_vnd,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING earning_id, pool_month, creator_id, eligible_learners, weighted_score, amount_vnd, status, paid_at, created_at
`

type CreateCreatorEarningParams struct {
	PoolMonth        time.Time `json:"pool_month"`
	CreatorID        uuid.UUID `json:"creator_id"`
	EligibleLearners int32     `json:"eligible_learners"`
	WeightedScore    string    `json:"weighted_score"`
	AmountVnd        int64     `json:"amount_vnd"`
	Status           string    `json:"status"`
}

func (q *Queries) CreateCreatorEarning(ctx context.Context, arg CreateCreatorEarningParams) (CreatorEarning, error) {
	row := q.db.QueryRowContext(ctx, createCreatorEarning,
		arg.PoolMonth,
		arg.CreatorID,
		arg.EligibleLearners,
		arg.WeightedScore,
		arg.AmountVnd,
		arg.Status,
	)
	var i CreatorEarning
	err := row.Scan(
		&i.EarningID,
		&i.PoolMonth,
		&i.CreatorID,
		&i.EligibleLearners,
		&i.WeightedScore,
		&i.AmountVnd,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMonthlyRevenuePool = `-- name: CreateMonthlyRevenuePool :one
INSERT INTO monthly_revenue_pools (
    pool_month,
    gross_amount_vnd,
    creator_pool_amount_vnd,
    platform_amount_vnd,
    status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING pool_month, gross_amount_vnd, creator_pool_amount_vnd, platform_amount_vnd, status, finalized_at
`

type CreateMonthlyRevenuePoolParams struct {
	PoolMonth            time.Time `json:"pool_month"`
	GrossAmountVnd       int64     `json:"gross_amount_vnd"`
	CreatorPoolAmountVnd int64     `json:"creator_pool_amount_vnd"`
	PlatformAmountVnd    int64     `json:"platform_amount_vnd"`
	Status               string    `json:"status"`
}

func (q *Queries) CreateMonthlyRevenuePool(ctx context.Context, arg CreateMonthlyRevenuePoolParams) (MonthlyRevenuePool, error) {
	row := q.db.QueryRowContext(ctx, createMonthlyRevenuePool,
		arg.PoolMonth,
		arg.GrossAmountVnd,
		arg.CreatorPoolAmountVnd,
		arg.PlatformAmountVnd,
		arg.Status,
	)
	var i MonthlyRevenuePool
	err := row.Scan(
		&i.PoolMonth,
		&i.GrossAmountVnd,
		&i.CreatorPoolAmountVnd,
		&i.PlatformAmountVnd,
		&i.Status,
		&i.FinalizedAt,
	)
	return i, err
}

const getCreatorEarningsByMonth = `-- name: GetCreatorEarningsByMonth :many
SELECT earning_id, pool_month, creator_id, eligible_learners, weighted_score, amount_vnd, status, paid_at, created_at FROM creator_earnings
WHERE pool_month = $1
ORDER BY amount_vnd DESC
`

func (q *Queries) GetCreatorEarningsByMonth(ctx context.Context, poolMonth time.Time) ([]CreatorEarning, error) {
	rows, err := q.db.QueryContext(ctx, getCreatorEarningsByMonth, poolMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreatorEarning{}
	for rows.Next() {
		var i CreatorEarning
		if err := rows.Scan(
			&i.EarningID,
			&i.PoolMonth,
			&i.CreatorID,
			&i.EligibleLearners,
			&i.WeightedScore,
			&i.AmountVnd,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyRevenuePools = `-- name: GetMonthlyRevenuePools :many
SELECT pool_month, gross_amount_vnd, creator_pool_amount_vnd, platform_amount_vnd, status, finalized_at FROM monthly_revenue_pools
ORDER BY pool_month DESC
`

func (q *Queries) GetMonthlyRevenuePools(ctx context.Context) ([]MonthlyRevenuePool, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyRevenuePools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyRevenuePool{}
	for rows.Next() {
		var i MonthlyRevenuePool
		if err := rows.Scan(
			&i.PoolMonth,
			&i.GrossAmountVnd,
			&i.CreatorPoolAmountVnd,
			&i.PlatformAmountVnd,
			&i.Status,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyEarnings = `-- name: GetMyEarnings :many
SELECT earning_id, pool_month, creator_id, eligible_learners, weighted_score, amount_vnd, status, paid_at, created_at FROM creator_earnings
WHERE creator_id = $1
ORDER BY pool_month DESC
`

func (q *Queries) GetMyEarnings(ctx context.Context, creatorID uuid.UUID) ([]CreatorEarning, error) {
	rows, err := q.db.QueryContext(ctx, getMyEarnings, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CreatorEarning{}
	for rows.Next() {
		var i CreatorEarning
		if err := rows.Scan(
			&i.EarningID,
			&i.PoolMonth,
			&i.CreatorID,
			&i.EligibleLearners,
			&i.WeightedScore,
			&i.AmountVnd,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCreatorEarningPaid = `-- name: MarkCreatorEarningPaid :one
UPDATE creator_earnings
SET status = 'paid', paid_at = CURRENT_TIMESTAMP
WHERE earning_id = $1
RETURNING earning_id, pool_month, creator_id, eligible_learners, weighted_score, amount_vnd, status, paid_at, created_at
`

func (q *Queries) MarkCreatorEarningPaid(ctx context.Context, earningID uuid.UUID) (CreatorEarning, error) {
	row := q.db.QueryRowContext(ctx, markCreatorEarningPaid, earningID)
	var i CreatorEarning
	err := row.Scan(
		&i.EarningID,
		&i.PoolMonth,
		&i.CreatorID,
		&i.EligibleLearners,
		&i.WeightedScore,
		&i.AmountVnd,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}
