// Code generated by MockGen. DO NOT EDIT.
// Source: mem_pan/services/deck-service/internal/repository (interfaces: CardRepository)

package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	db "mem_pan/services/deck-service/internal/db"
)

type MockCardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCardRepositoryMockRecorder
}

type MockCardRepositoryMockRecorder struct {
	mock *MockCardRepository
}

func NewMockCardRepository(ctrl *gomock.Controller) *MockCardRepository {
	mock := &MockCardRepository{ctrl: ctrl}
	mock.recorder = &MockCardRepositoryMockRecorder{mock}
	return mock
}

func (m *MockCardRepository) EXPECT() *MockCardRepositoryMockRecorder {
	return m.recorder
}

func (m *MockCardRepository) CreateCard(ctx context.Context, arg db.CreateCardParams) (db.Card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCard", ctx, arg)
	ret0, _ := ret[0].(db.Card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCardRepositoryMockRecorder) CreateCard(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCard", reflect.TypeOf((*MockCardRepository)(nil).CreateCard), ctx, arg)
}

func (m *MockCardRepository) GetCardByID(ctx context.Context, id uuid.UUID) (db.GetCardByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardByID", ctx, id)
	ret0, _ := ret[0].(db.GetCardByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCardRepositoryMockRecorder) GetCardByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardByID", reflect.TypeOf((*MockCardRepository)(nil).GetCardByID), ctx, id)
}

func (m *MockCardRepository) ListCardsByDeck(ctx context.Context, deckID uuid.UUID) ([]db.ListCardsByDeckRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCardsByDeck", ctx, deckID)
	ret0, _ := ret[0].([]db.ListCardsByDeckRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCardRepositoryMockRecorder) ListCardsByDeck(ctx, deckID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCardsByDeck", reflect.TypeOf((*MockCardRepository)(nil).ListCardsByDeck), ctx, deckID)
}

func (m *MockCardRepository) DeleteCard(ctx context.Context, arg db.DeleteCardParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCard", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCardRepositoryMockRecorder) DeleteCard(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCard", reflect.TypeOf((*MockCardRepository)(nil).DeleteCard), ctx, arg)
}

func (m *MockCardRepository) CountCardsByDeck(ctx context.Context, deckID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCardsByDeck", ctx, deckID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCardRepositoryMockRecorder) CountCardsByDeck(ctx, deckID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCardsByDeck", reflect.TypeOf((*MockCardRepository)(nil).CountCardsByDeck), ctx, deckID)
}
