// Code generated by MockGen. DO NOT EDIT.
// Source: mem_pan/services/deck-service/internal/publisher (interfaces: EventPublisher)

package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	publisher "mem_pan/services/deck-service/internal/publisher"
)

type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
}

type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

func (m *MockEventPublisher) PublishDeckCreated(ctx context.Context, event publisher.DeckCreatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDeckCreated", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEventPublisherMockRecorder) PublishDeckCreated(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDeckCreated", reflect.TypeOf((*MockEventPublisher)(nil).PublishDeckCreated), ctx, event)
}

func (m *MockEventPublisher) PublishDeckUpdated(ctx context.Context, event publisher.DeckUpdatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDeckUpdated", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEventPublisherMockRecorder) PublishDeckUpdated(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDeckUpdated", reflect.TypeOf((*MockEventPublisher)(nil).PublishDeckUpdated), ctx, event)
}

func (m *MockEventPublisher) PublishDeckDeleted(ctx context.Context, event publisher.DeckDeletedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDeckDeleted", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEventPublisherMockRecorder) PublishDeckDeleted(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDeckDeleted", reflect.TypeOf((*MockEventPublisher)(nil).PublishDeckDeleted), ctx, event)
}

func (m *MockEventPublisher) PublishFolderCreated(ctx context.Context, event publisher.FolderCreatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFolderCreated", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEventPublisherMockRecorder) PublishFolderCreated(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFolderCreated", reflect.TypeOf((*MockEventPublisher)(nil).PublishFolderCreated), ctx, event)
}

func (m *MockEventPublisher) PublishFolderUpdated(ctx context.Context, event publisher.FolderUpdatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFolderUpdated", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEventPublisherMockRecorder) PublishFolderUpdated(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFolderUpdated", reflect.TypeOf((*MockEventPublisher)(nil).PublishFolderUpdated), ctx, event)
}

func (m *MockEventPublisher) PublishFolderDeleted(ctx context.Context, event publisher.FolderDeletedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFolderDeleted", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEventPublisherMockRecorder) PublishFolderDeleted(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFolderDeleted", reflect.TypeOf((*MockEventPublisher)(nil).PublishFolderDeleted), ctx, event)
}

func (m *MockEventPublisher) PublishCardCreated(ctx context.Context, event publisher.CardCreatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCardCreated", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEventPublisherMockRecorder) PublishCardCreated(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCardCreated", reflect.TypeOf((*MockEventPublisher)(nil).PublishCardCreated), ctx, event)
}

func (m *MockEventPublisher) PublishCardUpdated(ctx context.Context, event publisher.CardUpdatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCardUpdated", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEventPublisherMockRecorder) PublishCardUpdated(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCardUpdated", reflect.TypeOf((*MockEventPublisher)(nil).PublishCardUpdated), ctx, event)
}

func (m *MockEventPublisher) PublishCardDeleted(ctx context.Context, event publisher.CardDeletedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCardDeleted", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEventPublisherMockRecorder) PublishCardDeleted(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCardDeleted", reflect.TypeOf((*MockEventPublisher)(nil).PublishCardDeleted), ctx, event)
}

func (m *MockEventPublisher) PublishReportSubmitted(ctx context.Context, event publisher.ReportSubmittedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishReportSubmitted", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEventPublisherMockRecorder) PublishReportSubmitted(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishReportSubmitted", reflect.TypeOf((*MockEventPublisher)(nil).PublishReportSubmitted), ctx, event)
}
