// Code generated by MockGen. DO NOT EDIT.
// Source: mem_pan/services/deck-service/internal/repository (interfaces: FolderDeckRepository)

package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	db "mem_pan/services/deck-service/internal/db"
)

type MockFolderDeckRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFolderDeckRepositoryMockRecorder
}

type MockFolderDeckRepositoryMockRecorder struct {
	mock *MockFolderDeckRepository
}

func NewMockFolderDeckRepository(ctrl *gomock.Controller) *MockFolderDeckRepository {
	mock := &MockFolderDeckRepository{ctrl: ctrl}
	mock.recorder = &MockFolderDeckRepositoryMockRecorder{mock}
	return mock
}

func (m *MockFolderDeckRepository) EXPECT() *MockFolderDeckRepositoryMockRecorder {
	return m.recorder
}

func (m *MockFolderDeckRepository) AddDeckToFolder(ctx context.Context, arg db.AddDeckToFolderParams) (db.FolderDeck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDeckToFolder", ctx, arg)
	ret0, _ := ret[0].(db.FolderDeck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockFolderDeckRepositoryMockRecorder) AddDeckToFolder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDeckToFolder", reflect.TypeOf((*MockFolderDeckRepository)(nil).AddDeckToFolder), ctx, arg)
}

func (m *MockFolderDeckRepository) RemoveDeckFromFolder(ctx context.Context, arg db.RemoveDeckFromFolderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDeckFromFolder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockFolderDeckRepositoryMockRecorder) RemoveDeckFromFolder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDeckFromFolder", reflect.TypeOf((*MockFolderDeckRepository)(nil).RemoveDeckFromFolder), ctx, arg)
}

func (m *MockFolderDeckRepository) ListDecksByFolder(ctx context.Context, folderID uuid.UUID) ([]db.Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDecksByFolder", ctx, folderID)
	ret0, _ := ret[0].([]db.Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockFolderDeckRepositoryMockRecorder) ListDecksByFolder(ctx, folderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDecksByFolder", reflect.TypeOf((*MockFolderDeckRepository)(nil).ListDecksByFolder), ctx, folderID)
}

func (m *MockFolderDeckRepository) IsDeckInFolder(ctx context.Context, arg db.IsDeckInFolderParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDeckInFolder", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockFolderDeckRepositoryMockRecorder) IsDeckInFolder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDeckInFolder", reflect.TypeOf((*MockFolderDeckRepository)(nil).IsDeckInFolder), ctx, arg)
}
