// Code generated by MockGen. DO NOT EDIT.
// Source: mem_pan/services/deck-service/internal/repository (interfaces: FolderRepository)

package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	db "mem_pan/services/deck-service/internal/db"
)

type MockFolderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFolderRepositoryMockRecorder
}

type MockFolderRepositoryMockRecorder struct {
	mock *MockFolderRepository
}

func NewMockFolderRepository(ctrl *gomock.Controller) *MockFolderRepository {
	mock := &MockFolderRepository{ctrl: ctrl}
	mock.recorder = &MockFolderRepositoryMockRecorder{mock}
	return mock
}

func (m *MockFolderRepository) EXPECT() *MockFolderRepositoryMockRecorder {
	return m.recorder
}

func (m *MockFolderRepository) CreateFolder(ctx context.Context, arg db.CreateFolderParams) (db.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFolder", ctx, arg)
	ret0, _ := ret[0].(db.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockFolderRepositoryMockRecorder) CreateFolder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFolder", reflect.TypeOf((*MockFolderRepository)(nil).CreateFolder), ctx, arg)
}

func (m *MockFolderRepository) GetFolderByID(ctx context.Context, id uuid.UUID) (db.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFolderByID", ctx, id)
	ret0, _ := ret[0].(db.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockFolderRepositoryMockRecorder) GetFolderByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFolderByID", reflect.TypeOf((*MockFolderRepository)(nil).GetFolderByID), ctx, id)
}

func (m *MockFolderRepository) ListFoldersByUser(ctx context.Context, userID uuid.UUID) ([]db.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFoldersByUser", ctx, userID)
	ret0, _ := ret[0].([]db.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockFolderRepositoryMockRecorder) ListFoldersByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFoldersByUser", reflect.TypeOf((*MockFolderRepository)(nil).ListFoldersByUser), ctx, userID)
}

func (m *MockFolderRepository) UpdateFolder(ctx context.Context, arg db.UpdateFolderParams) (db.Folder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFolder", ctx, arg)
	ret0, _ := ret[0].(db.Folder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockFolderRepositoryMockRecorder) UpdateFolder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFolder", reflect.TypeOf((*MockFolderRepository)(nil).UpdateFolder), ctx, arg)
}

func (m *MockFolderRepository) DeleteFolder(ctx context.Context, arg db.DeleteFolderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFolder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockFolderRepositoryMockRecorder) DeleteFolder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFolder", reflect.TypeOf((*MockFolderRepository)(nil).DeleteFolder), ctx, arg)
}
