// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: search_service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeckSearchScope int32

const (
	DeckSearchScope_DECK_SCOPE_UNSPECIFIED DeckSearchScope = 0
	DeckSearchScope_DECK_SCOPE_PUBLIC      DeckSearchScope = 1
	DeckSearchScope_DECK_SCOPE_MINE        DeckSearchScope = 2
	DeckSearchScope_DECK_SCOPE_ALL         DeckSearchScope = 3
)

// Enum value maps for DeckSearchScope.
var (
	DeckSearchScope_name = map[int32]string{
		0: "DECK_SCOPE_UNSPECIFIED",
		1: "DECK_SCOPE_PUBLIC",
		2: "DECK_SCOPE_MINE",
		3: "DECK_SCOPE_ALL",
	}
	DeckSearchScope_value = map[string]int32{
		"DECK_SCOPE_UNSPECIFIED": 0,
		"DECK_SCOPE_PUBLIC":      1,
		"DECK_SCOPE_MINE":        2,
		"DECK_SCOPE_ALL":         3,
	}
)

func (x DeckSearchScope) Enum() *DeckSearchScope {
	p := new(DeckSearchScope)
	*p = x
	return p
}

func (x DeckSearchScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeckSearchScope) Descriptor() protoreflect.EnumDescriptor {
	return file_search_service_proto_enumTypes[0].Descriptor()
}

func (DeckSearchScope) Type() protoreflect.EnumType {
	return &file_search_service_proto_enumTypes[0]
}

func (x DeckSearchScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeckSearchScope.Descriptor instead.
func (DeckSearchScope) EnumDescriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{0}
}

type FolderSearchScope int32

const (
	FolderSearchScope_FOLDER_SCOPE_UNSPECIFIED FolderSearchScope = 0
	FolderSearchScope_FOLDER_SCOPE_PUBLIC      FolderSearchScope = 1
	FolderSearchScope_FOLDER_SCOPE_MINE        FolderSearchScope = 2
	FolderSearchScope_FOLDER_SCOPE_ALL         FolderSearchScope = 3
)

// Enum value maps for FolderSearchScope.
var (
	FolderSearchScope_name = map[int32]string{
		0: "FOLDER_SCOPE_UNSPECIFIED",
		1: "FOLDER_SCOPE_PUBLIC",
		2: "FOLDER_SCOPE_MINE",
		3: "FOLDER_SCOPE_ALL",
	}
	FolderSearchScope_value = map[string]int32{
		"FOLDER_SCOPE_UNSPECIFIED": 0,
		"FOLDER_SCOPE_PUBLIC":      1,
		"FOLDER_SCOPE_MINE":        2,
		"FOLDER_SCOPE_ALL":         3,
	}
)

func (x FolderSearchScope) Enum() *FolderSearchScope {
	p := new(FolderSearchScope)
	*p = x
	return p
}

func (x FolderSearchScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FolderSearchScope) Descriptor() protoreflect.EnumDescriptor {
	return file_search_service_proto_enumTypes[1].Descriptor()
}

func (FolderSearchScope) Type() protoreflect.EnumType {
	return &file_search_service_proto_enumTypes[1]
}

func (x FolderSearchScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FolderSearchScope.Descriptor instead.
func (FolderSearchScope) EnumDescriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{1}
}

type Deck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CardCount     int32                  `protobuf:"varint,7,opt,name=card_count,json=cardCount,proto3" json:"card_count,omitempty"`
	ClonedFrom    string                 `protobuf:"bytes,8,opt,name=cloned_from,json=clonedFrom,proto3" json:"cloned_from,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Score         float64                `protobuf:"fixed64,11,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deck) Reset() {
	*x = Deck{}
	mi := &file_search_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deck) ProtoMessage() {}

func (x *Deck) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deck.ProtoReflect.Descriptor instead.
func (*Deck) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{0}
}

func (x *Deck) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *Deck) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Deck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deck) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Deck) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Deck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Deck) GetCardCount() int32 {
	if x != nil {
		return x.CardCount
	}
	return 0
}

func (x *Deck) GetClonedFrom() string {
	if x != nil {
		return x.ClonedFrom
	}
	return ""
}

func (x *Deck) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Deck) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Deck) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Score         float64                `protobuf:"fixed64,8,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_search_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{1}
}

func (x *Folder) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *Folder) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Folder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Folder) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Folder) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Folder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Folder) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Folder) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeckId        string                 `protobuf:"bytes,3,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	NoteId        string                 `protobuf:"bytes,4,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	ContentFront  string                 `protobuf:"bytes,5,opt,name=content_front,json=contentFront,proto3" json:"content_front,omitempty"`
	ContentBack   string                 `protobuf:"bytes,6,opt,name=content_back,json=contentBack,proto3" json:"content_back,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Score         float64                `protobuf:"fixed64,8,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_search_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{2}
}

func (x *Card) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *Card) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Card) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *Card) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *Card) GetContentFront() string {
	if x != nil {
		return x.ContentFront
	}
	return ""
}

func (x *Card) GetContentBack() string {
	if x != nil {
		return x.ContentBack
	}
	return ""
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Card) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Score         float64                `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_search_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchDecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Scope         DeckSearchScope        `protobuf:"varint,2,opt,name=scope,proto3,enum=search.DeckSearchScope" json:"scope,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDecksRequest) Reset() {
	*x = SearchDecksRequest{}
	mi := &file_search_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDecksRequest) ProtoMessage() {}

func (x *SearchDecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDecksRequest.ProtoReflect.Descriptor instead.
func (*SearchDecksRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchDecksRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchDecksRequest) GetScope() DeckSearchScope {
	if x != nil {
		return x.Scope
	}
	return DeckSearchScope_DECK_SCOPE_UNSPECIFIED
}

func (x *SearchDecksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchDecksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchDecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decks         []*Deck                `protobuf:"bytes,1,rep,name=decks,proto3" json:"decks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDecksResponse) Reset() {
	*x = SearchDecksResponse{}
	mi := &file_search_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDecksResponse) ProtoMessage() {}

func (x *SearchDecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDecksResponse.ProtoReflect.Descriptor instead.
func (*SearchDecksResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{5}
}

func (x *SearchDecksResponse) GetDecks() []*Deck {
	if x != nil {
		return x.Decks
	}
	return nil
}

func (x *SearchDecksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchFoldersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Scope         FolderSearchScope      `protobuf:"varint,2,opt,name=scope,proto3,enum=search.FolderSearchScope" json:"scope,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFoldersRequest) Reset() {
	*x = SearchFoldersRequest{}
	mi := &file_search_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoldersRequest) ProtoMessage() {}

func (x *SearchFoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoldersRequest.ProtoReflect.Descriptor instead.
func (*SearchFoldersRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{6}
}

func (x *SearchFoldersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchFoldersRequest) GetScope() FolderSearchScope {
	if x != nil {
		return x.Scope
	}
	return FolderSearchScope_FOLDER_SCOPE_UNSPECIFIED
}

func (x *SearchFoldersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchFoldersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchFoldersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*Folder              `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFoldersResponse) Reset() {
	*x = SearchFoldersResponse{}
	mi := &file_search_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoldersResponse) ProtoMessage() {}

func (x *SearchFoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoldersResponse.ProtoReflect.Descriptor instead.
func (*SearchFoldersResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{7}
}

func (x *SearchFoldersResponse) GetFolders() []*Folder {
	if x != nil {
		return x.Folders
	}
	return nil
}

func (x *SearchFoldersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	DeckId        string                 `protobuf:"bytes,2,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"` // optional; if set, results are filtered to this deck
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCardsRequest) Reset() {
	*x = SearchCardsRequest{}
	mi := &file_search_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCardsRequest) ProtoMessage() {}

func (x *SearchCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCardsRequest.ProtoReflect.Descriptor instead.
func (*SearchCardsRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{8}
}

func (x *SearchCardsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchCardsRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *SearchCardsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchCardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCardsResponse) Reset() {
	*x = SearchCardsResponse{}
	mi := &file_search_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCardsResponse) ProtoMessage() {}

func (x *SearchCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCardsResponse.ProtoReflect.Descriptor instead.
func (*SearchCardsResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{9}
}

func (x *SearchCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *SearchCardsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_search_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{10}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_search_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{11}
}

func (x *SearchUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_search_service_proto protoreflect.FileDescriptor

const file_search_service_proto_rawDesc = "" +
	"\n" +
	"\x14search_service.proto\x12\x06search\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xef\x02\n" +
	"\x04Deck\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"card_count\x18\a \x01(\x05R\tcardCount\x12\x1f\n" +
	"\vcloned_from\x18\b \x01(\tR\n" +
	"clonedFrom\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n" +
	"\x05score\x18\v \x01(\x01R\x05score\"\x9d\x02\n" +
	"\x06Folder\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n" +
	"\x05score\x18\b \x01(\x01R\x05score\"\x83\x02\n" +
	"\x04Card\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\adeck_id\x18\x03 \x01(\tR\x06deckId\x12\x17\n" +
	"\anote_id\x18\x04 \x01(\tR\x06noteId\x12#\n" +
	"\rcontent_front\x18\x05 \x01(\tR\fcontentFront\x12!\n" +
	"\fcontent_back\x18\x06 \x01(\tR\vcontentBack\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05score\x18\b \x01(\x01R\x05score\"\xc8\x01\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\"\x8a\x01\n" +
	"\x12SearchDecksRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12-\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x17.search.DeckSearchScopeR\x05scope\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"O\n" +
	"\x13SearchDecksResponse\x12\"\n" +
	"\x05decks\x18\x01 \x03(\v2\f.search.DeckR\x05decks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x8e\x01\n" +
	"\x14SearchFoldersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12/\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x19.search.FolderSearchScopeR\x05scope\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"W\n" +
	"\x15SearchFoldersResponse\x12(\n" +
	"\afolders\x18\x01 \x03(\v2\x0e.search.FolderR\afolders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"t\n" +
	"\x12SearchCardsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\adeck_id\x18\x02 \x01(\tR\x06deckId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"O\n" +
	"\x13SearchCardsResponse\x12\"\n" +
	"\x05cards\x18\x01 \x03(\v2\f.search.CardR\x05cards\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"[\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"O\n" +
	"\x13SearchUsersResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.search.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total*m\n" +
	"\x0fDeckSearchScope\x12\x1a\n" +
	"\x16DECK_SCOPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DECK_SCOPE_PUBLIC\x10\x01\x12\x13\n" +
	"\x0fDECK_SCOPE_MINE\x10\x02\x12\x12\n" +
	"\x0eDECK_SCOPE_ALL\x10\x03*w\n" +
	"\x11FolderSearchScope\x12\x1c\n" +
	"\x18FOLDER_SCOPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FOLDER_SCOPE_PUBLIC\x10\x01\x12\x15\n" +
	"\x11FOLDER_SCOPE_MINE\x10\x02\x12\x14\n" +
	"\x10FOLDER_SCOPE_ALL\x10\x032\xd6\x05\n" +
	"\rSearchService\x12\xb0\x01\n" +
	"\vSearchDecks\x12\x1a.search.SearchDecksRequest\x1a\x1b.search.SearchDecksResponse\"h\x92AM\n" +
	"\x06search\x12CSearch decks (public by default; pass scope=mine for caller's own).\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/search/decks\x12\xba\x01\n" +
	"\rSearchFolders\x12\x1c.search.SearchFoldersRequest\x1a\x1d.search.SearchFoldersResponse\"l\x92AO\n" +
	"\x06search\x12ESearch folders (public by default; pass scope=mine for caller's own).\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/search/folders\x12\xbe\x01\n" +
	"\vSearchCards\x12\x1a.search.SearchCardsRequest\x1a\x1b.search.SearchCardsResponse\"v\x92A[\n" +
	"\x06search\x12?Search cards owned by the caller (optionally scoped to a deck).b\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/search/cards\x12\x93\x01\n" +
	"\vSearchUsers\x12\x1a.search.SearchUsersRequest\x1a\x1b.search.SearchUsersResponse\"K\x92A0\n" +
	"\x06search\x12&Search users by username or full name.\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/search/usersB\x8b\x01\x92Ad\x12\x19\n" +
	"\x12Search Service API2\x031.02\x10application/json:\x10application/jsonZ#\n" +
	"!\n" +
	"\n" +
	"BearerAuth\x12\x13\b\x02\x1a\rAuthorization \x02Z\"mem_pan/services/search-service/pbb\x06proto3"

var (
	file_search_service_proto_rawDescOnce sync.Once
	file_search_service_proto_rawDescData []byte
)

func file_search_service_proto_rawDescGZIP() []byte {
	file_search_service_proto_rawDescOnce.Do(func() {
		file_search_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_service_proto_rawDesc), len(file_search_service_proto_rawDesc)))
	})
	return file_search_service_proto_rawDescData
}

var file_search_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_search_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_search_service_proto_goTypes = []any{
	(DeckSearchScope)(0),          // 0: search.DeckSearchScope
	(FolderSearchScope)(0),        // 1: search.FolderSearchScope
	(*Deck)(nil),                  // 2: search.Deck
	(*Folder)(nil),                // 3: search.Folder
	(*Card)(nil),                  // 4: search.Card
	(*User)(nil),                  // 5: search.User
	(*SearchDecksRequest)(nil),    // 6: search.SearchDecksRequest
	(*SearchDecksResponse)(nil),   // 7: search.SearchDecksResponse
	(*SearchFoldersRequest)(nil),  // 8: search.SearchFoldersRequest
	(*SearchFoldersResponse)(nil), // 9: search.SearchFoldersResponse
	(*SearchCardsRequest)(nil),    // 10: search.SearchCardsRequest
	(*SearchCardsResponse)(nil),   // 11: search.SearchCardsResponse
	(*SearchUsersRequest)(nil),    // 12: search.SearchUsersRequest
	(*SearchUsersResponse)(nil),   // 13: search.SearchUsersResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_search_service_proto_depIdxs = []int32{
	14, // 0: search.Deck.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: search.Deck.updated_at:type_name -> google.protobuf.Timestamp
	14, // 2: search.Folder.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: search.Folder.updated_at:type_name -> google.protobuf.Timestamp
	14, // 4: search.Card.created_at:type_name -> google.protobuf.Timestamp
	14, // 5: search.User.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: search.SearchDecksRequest.scope:type_name -> search.DeckSearchScope
	2,  // 7: search.SearchDecksResponse.decks:type_name -> search.Deck
	1,  // 8: search.SearchFoldersRequest.scope:type_name -> search.FolderSearchScope
	3,  // 9: search.SearchFoldersResponse.folders:type_name -> search.Folder
	4,  // 10: search.SearchCardsResponse.cards:type_name -> search.Card
	5,  // 11: search.SearchUsersResponse.users:type_name -> search.User
	6,  // 12: search.SearchService.SearchDecks:input_type -> search.SearchDecksRequest
	8,  // 13: search.SearchService.SearchFolders:input_type -> search.SearchFoldersRequest
	10, // 14: search.SearchService.SearchCards:input_type -> search.SearchCardsRequest
	12, // 15: search.SearchService.SearchUsers:input_type -> search.SearchUsersRequest
	7,  // 16: search.SearchService.SearchDecks:output_type -> search.SearchDecksResponse
	9,  // 17: search.SearchService.SearchFolders:output_type -> search.SearchFoldersResponse
	11, // 18: search.SearchService.SearchCards:output_type -> search.SearchCardsResponse
	13, // 19: search.SearchService.SearchUsers:output_type -> search.SearchUsersResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_search_service_proto_init() }
func file_search_service_proto_init() {
	if File_search_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_service_proto_rawDesc), len(file_search_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_service_proto_goTypes,
		DependencyIndexes: file_search_service_proto_depIdxs,
		EnumInfos:         file_search_service_proto_enumTypes,
		MessageInfos:      file_search_service_proto_msgTypes,
	}.Build()
	File_search_service_proto = out.File
	file_search_service_proto_goTypes = nil
	file_search_service_proto_depIdxs = nil
}
