// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: deck_service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportDeckRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeckId         string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	ReasonCategory string                 `protobuf:"bytes,2,opt,name=reason_category,json=reasonCategory,proto3" json:"reason_category,omitempty"` // inappropriate_content | copyright_violation | spam | harassment | misinformation | other
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportDeckRequest) Reset() {
	*x = ReportDeckRequest{}
	mi := &file_deck_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDeckRequest) ProtoMessage() {}

func (x *ReportDeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deck_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDeckRequest.ProtoReflect.Descriptor instead.
func (*ReportDeckRequest) Descriptor() ([]byte, []int) {
	return file_deck_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReportDeckRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *ReportDeckRequest) GetReasonCategory() string {
	if x != nil {
		return x.ReasonCategory
	}
	return ""
}

func (x *ReportDeckRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ReportDeckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDeckResponse) Reset() {
	*x = ReportDeckResponse{}
	mi := &file_deck_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDeckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDeckResponse) ProtoMessage() {}

func (x *ReportDeckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deck_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDeckResponse.ProtoReflect.Descriptor instead.
func (*ReportDeckResponse) Descriptor() ([]byte, []int) {
	return file_deck_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReportDeckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_deck_service_proto protoreflect.FileDescriptor

const file_deck_service_proto_rawDesc = "" +
	"\n" +
	"\x12deck_service.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x10rpc_folder.proto\x1a\x0erpc_deck.proto\x1a\x0erpc_card.proto\x1a\x10rpc_import.proto\"w\n" +
	"\x11ReportDeckRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12'\n" +
	"\x0freason_category\x18\x02 \x01(\tR\x0ereasonCategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\".\n" +
	"\x12ReportDeckResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x93\x1d\n" +
	"\vDeckService\x12\x7f\n" +
	"\vListFolders\x12\x16.pb.ListFoldersRequest\x1a\x17.pb.ListFoldersResponse\"?\x92A)\n" +
	"\afolders\x12\fList foldersb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\r\x12\v/v1/folders\x12\x86\x01\n" +
	"\fCreateFolder\x12\x17.pb.CreateFolderRequest\x1a\x18.pb.CreateFolderResponse\"C\x92A*\n" +
	"\afolders\x12\rCreate folderb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/folders\x12\x8e\x01\n" +
	"\tGetFolder\x12\x14.pb.GetFolderRequest\x1a\x15.pb.GetFolderResponse\"T\x92A2\n" +
	"\afolders\x12\x15Get folder with decksb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/folders/{folder_id}\x12\x92\x01\n" +
	"\fUpdateFolder\x12\x17.pb.UpdateFolderRequest\x1a\x18.pb.UpdateFolderResponse\"O\x92A*\n" +
	"\afolders\x12\rUpdate folderb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1c:\x01*2\x17/v1/folders/{folder_id}\x12\x8f\x01\n" +
	"\fDeleteFolder\x12\x17.pb.DeleteFolderRequest\x1a\x18.pb.DeleteFolderResponse\"L\x92A*\n" +
	"\afolders\x12\rDelete folderb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x19*\x17/v1/folders/{folder_id}\x12\xb0\x01\n" +
	"\x0fAddDeckToFolder\x12\x1a.pb.AddDeckToFolderRequest\x1a\x1b.pb.AddDeckToFolderResponse\"d\x92A/\n" +
	"\afolders\x12\x12Add deck to folderb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02,:\x01*\"'/v1/folders/{folder_id}/decks/{deck_id}\x12\xc1\x01\n" +
	"\x14RemoveDeckFromFolder\x12\x1f.pb.RemoveDeckFromFolderRequest\x1a .pb.RemoveDeckFromFolderResponse\"f\x92A4\n" +
	"\afolders\x12\x17Remove deck from folderb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02)*'/v1/folders/{folder_id}/decks/{deck_id}\x12v\n" +
	"\tListDecks\x12\x14.pb.ListDecksRequest\x1a\x15.pb.ListDecksResponse\"<\x92A(\n" +
	"\x05decks\x12\rList my decksb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\v\x12\t/v1/decks\x12z\n" +
	"\n" +
	"CreateDeck\x12\x15.pb.CreateDeckRequest\x1a\x16.pb.CreateDeckResponse\"=\x92A&\n" +
	"\x05decks\x12\vCreate deckb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/decks\x12\x83\x01\n" +
	"\x0fListPublicDecks\x12\x1a.pb.ListPublicDecksRequest\x1a\x1b.pb.ListPublicDecksResponse\"7\x92A\x1c\n" +
	"\x05decks\x12\x13Search public decks\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/decks/public\x12|\n" +
	"\aGetDeck\x12\x12.pb.GetDeckRequest\x1a\x13.pb.GetDeckResponse\"H\x92A*\n" +
	"\x05decks\x12\x0fGet deck detailb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/decks/{deck_id}\x12\x89\x01\n" +
	"\n" +
	"UpdateDeck\x12\x15.pb.UpdateDeckRequest\x1a\x16.pb.UpdateDeckResponse\"L\x92A+\n" +
	"\x05decks\x12\x10Update deck infob\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/decks/{deck_id}\x12\x81\x01\n" +
	"\n" +
	"DeleteDeck\x12\x15.pb.DeleteDeckRequest\x1a\x16.pb.DeleteDeckResponse\"D\x92A&\n" +
	"\x05decks\x12\vDelete deckb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x15*\x13/v1/decks/{deck_id}\x12\xae\x01\n" +
	"\x12UpdateDeckSettings\x12\x1d.pb.UpdateDeckSettingsRequest\x1a\x1e.pb.UpdateDeckSettingsResponse\"Y\x92A/\n" +
	"\x05decks\x12\x14Update deck settingsb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02!:\x01*2\x1c/v1/decks/{deck_id}/settings\x12\xb8\x01\n" +
	"\x14UpdateDeckVisibility\x12\x1f.pb.UpdateDeckVisibilityRequest\x1a .pb.UpdateDeckVisibilityResponse\"]\x92A1\n" +
	"\x05decks\x12\x16Toggle deck visibilityb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02#:\x01*2\x1e/v1/decks/{deck_id}/visibility\x12\x88\x01\n" +
	"\tCloneDeck\x12\x14.pb.CloneDeckRequest\x1a\x15.pb.CloneDeckResponse\"N\x92A'\n" +
	"\x05decks\x12\fClone a deckb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/decks/{deck_id}/clone\x12\x95\x01\n" +
	"\fGetDeckStats\x12\x17.pb.GetDeckStatsRequest\x1a\x18.pb.GetDeckStatsResponse\"R\x92A.\n" +
	"\x05decks\x12\x13Get deck statisticsb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/decks/{deck_id}/stats\x12\x97\x01\n" +
	"\rListDeckCards\x12\x18.pb.ListDeckCardsRequest\x1a\x19.pb.ListDeckCardsResponse\"Q\x92A-\n" +
	"\x05decks\x12\x12List cards in deckb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/decks/{deck_id}/cards\x12\x92\x01\n" +
	"\n" +
	"CreateCard\x12\x15.pb.CreateCardRequest\x1a\x16.pb.CreateCardResponse\"U\x92A.\n" +
	"\x05decks\x12\x13Create card in deckb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/decks/{deck_id}/cards\x12\xa4\x01\n" +
	"\x0fBulkCreateCards\x12\x1a.pb.BulkCreateCardsRequest\x1a\x1b.pb.BulkCreateCardsResponse\"X\x92A,\n" +
	"\x05decks\x12\x11Bulk import cardsb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/decks/{deck_id}/cards/bulk\x12\xaa\x01\n" +
	"\x0fParseImportFile\x12\x1a.pb.ParseImportFileRequest\x1a\x1b.pb.ParseImportFileResponse\"^\x92A@\n" +
	"\x06import\x12$Parse CSV/PDF file and preview cardsb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/import/parse\x12|\n" +
	"\aGetCard\x12\x12.pb.GetCardRequest\x1a\x13.pb.GetCardResponse\"H\x92A*\n" +
	"\x05cards\x12\x0fGet card detailb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/cards/{card_id}\x12\x8c\x01\n" +
	"\n" +
	"UpdateCard\x12\x15.pb.UpdateCardRequest\x1a\x16.pb.UpdateCardResponse\"O\x92A.\n" +
	"\x05cards\x12\x13Update card contentb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/cards/{card_id}\x12\x81\x01\n" +
	"\n" +
	"DeleteCard\x12\x15.pb.DeleteCardRequest\x1a\x16.pb.DeleteCardResponse\"D\x92A&\n" +
	"\x05cards\x12\vDelete cardb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x15*\x13/v1/cards/{card_id}\x12\x9f\x01\n" +
	"\n" +
	"ReportDeck\x12\x15.pb.ReportDeckRequest\x1a\x16.pb.ReportDeckResponse\"b\x92A9\n" +
	"\areports\x12\x1cReport a deck for moderationb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/decks/{deck_id}/reportsB\x87\x01\x92Ab\x12\x17\n" +
	"\x10Deck Service API2\x031.02\x10application/json:\x10application/jsonZ#\n" +
	"!\n" +
	"\n" +
	"BearerAuth\x12\x13\b\x02\x1a\rAuthorization \x02Z mem_pan/services/deck-service/pbb\x06proto3"

var (
	file_deck_service_proto_rawDescOnce sync.Once
	file_deck_service_proto_rawDescData []byte
)

func file_deck_service_proto_rawDescGZIP() []byte {
	file_deck_service_proto_rawDescOnce.Do(func() {
		file_deck_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deck_service_proto_rawDesc), len(file_deck_service_proto_rawDesc)))
	})
	return file_deck_service_proto_rawDescData
}

var file_deck_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_deck_service_proto_goTypes = []any{
	(*ReportDeckRequest)(nil),            // 0: pb.ReportDeckRequest
	(*ReportDeckResponse)(nil),           // 1: pb.ReportDeckResponse
	(*ListFoldersRequest)(nil),           // 2: pb.ListFoldersRequest
	(*CreateFolderRequest)(nil),          // 3: pb.CreateFolderRequest
	(*GetFolderRequest)(nil),             // 4: pb.GetFolderRequest
	(*UpdateFolderRequest)(nil),          // 5: pb.UpdateFolderRequest
	(*DeleteFolderRequest)(nil),          // 6: pb.DeleteFolderRequest
	(*AddDeckToFolderRequest)(nil),       // 7: pb.AddDeckToFolderRequest
	(*RemoveDeckFromFolderRequest)(nil),  // 8: pb.RemoveDeckFromFolderRequest
	(*ListDecksRequest)(nil),             // 9: pb.ListDecksRequest
	(*CreateDeckRequest)(nil),            // 10: pb.CreateDeckRequest
	(*ListPublicDecksRequest)(nil),       // 11: pb.ListPublicDecksRequest
	(*GetDeckRequest)(nil),               // 12: pb.GetDeckRequest
	(*UpdateDeckRequest)(nil),            // 13: pb.UpdateDeckRequest
	(*DeleteDeckRequest)(nil),            // 14: pb.DeleteDeckRequest
	(*UpdateDeckSettingsRequest)(nil),    // 15: pb.UpdateDeckSettingsRequest
	(*UpdateDeckVisibilityRequest)(nil),  // 16: pb.UpdateDeckVisibilityRequest
	(*CloneDeckRequest)(nil),             // 17: pb.CloneDeckRequest
	(*GetDeckStatsRequest)(nil),          // 18: pb.GetDeckStatsRequest
	(*ListDeckCardsRequest)(nil),         // 19: pb.ListDeckCardsRequest
	(*CreateCardRequest)(nil),            // 20: pb.CreateCardRequest
	(*BulkCreateCardsRequest)(nil),       // 21: pb.BulkCreateCardsRequest
	(*ParseImportFileRequest)(nil),       // 22: pb.ParseImportFileRequest
	(*GetCardRequest)(nil),               // 23: pb.GetCardRequest
	(*UpdateCardRequest)(nil),            // 24: pb.UpdateCardRequest
	(*DeleteCardRequest)(nil),            // 25: pb.DeleteCardRequest
	(*ListFoldersResponse)(nil),          // 26: pb.ListFoldersResponse
	(*CreateFolderResponse)(nil),         // 27: pb.CreateFolderResponse
	(*GetFolderResponse)(nil),            // 28: pb.GetFolderResponse
	(*UpdateFolderResponse)(nil),         // 29: pb.UpdateFolderResponse
	(*DeleteFolderResponse)(nil),         // 30: pb.DeleteFolderResponse
	(*AddDeckToFolderResponse)(nil),      // 31: pb.AddDeckToFolderResponse
	(*RemoveDeckFromFolderResponse)(nil), // 32: pb.RemoveDeckFromFolderResponse
	(*ListDecksResponse)(nil),            // 33: pb.ListDecksResponse
	(*CreateDeckResponse)(nil),           // 34: pb.CreateDeckResponse
	(*ListPublicDecksResponse)(nil),      // 35: pb.ListPublicDecksResponse
	(*GetDeckResponse)(nil),              // 36: pb.GetDeckResponse
	(*UpdateDeckResponse)(nil),           // 37: pb.UpdateDeckResponse
	(*DeleteDeckResponse)(nil),           // 38: pb.DeleteDeckResponse
	(*UpdateDeckSettingsResponse)(nil),   // 39: pb.UpdateDeckSettingsResponse
	(*UpdateDeckVisibilityResponse)(nil), // 40: pb.UpdateDeckVisibilityResponse
	(*CloneDeckResponse)(nil),            // 41: pb.CloneDeckResponse
	(*GetDeckStatsResponse)(nil),         // 42: pb.GetDeckStatsResponse
	(*ListDeckCardsResponse)(nil),        // 43: pb.ListDeckCardsResponse
	(*CreateCardResponse)(nil),           // 44: pb.CreateCardResponse
	(*BulkCreateCardsResponse)(nil),      // 45: pb.BulkCreateCardsResponse
	(*ParseImportFileResponse)(nil),      // 46: pb.ParseImportFileResponse
	(*GetCardResponse)(nil),              // 47: pb.GetCardResponse
	(*UpdateCardResponse)(nil),           // 48: pb.UpdateCardResponse
	(*DeleteCardResponse)(nil),           // 49: pb.DeleteCardResponse
}
var file_deck_service_proto_depIdxs = []int32{
	2,  // 0: pb.DeckService.ListFolders:input_type -> pb.ListFoldersRequest
	3,  // 1: pb.DeckService.CreateFolder:input_type -> pb.CreateFolderRequest
	4,  // 2: pb.DeckService.GetFolder:input_type -> pb.GetFolderRequest
	5,  // 3: pb.DeckService.UpdateFolder:input_type -> pb.UpdateFolderRequest
	6,  // 4: pb.DeckService.DeleteFolder:input_type -> pb.DeleteFolderRequest
	7,  // 5: pb.DeckService.AddDeckToFolder:input_type -> pb.AddDeckToFolderRequest
	8,  // 6: pb.DeckService.RemoveDeckFromFolder:input_type -> pb.RemoveDeckFromFolderRequest
	9,  // 7: pb.DeckService.ListDecks:input_type -> pb.ListDecksRequest
	10, // 8: pb.DeckService.CreateDeck:input_type -> pb.CreateDeckRequest
	11, // 9: pb.DeckService.ListPublicDecks:input_type -> pb.ListPublicDecksRequest
	12, // 10: pb.DeckService.GetDeck:input_type -> pb.GetDeckRequest
	13, // 11: pb.DeckService.UpdateDeck:input_type -> pb.UpdateDeckRequest
	14, // 12: pb.DeckService.DeleteDeck:input_type -> pb.DeleteDeckRequest
	15, // 13: pb.DeckService.UpdateDeckSettings:input_type -> pb.UpdateDeckSettingsRequest
	16, // 14: pb.DeckService.UpdateDeckVisibility:input_type -> pb.UpdateDeckVisibilityRequest
	17, // 15: pb.DeckService.CloneDeck:input_type -> pb.CloneDeckRequest
	18, // 16: pb.DeckService.GetDeckStats:input_type -> pb.GetDeckStatsRequest
	19, // 17: pb.DeckService.ListDeckCards:input_type -> pb.ListDeckCardsRequest
	20, // 18: pb.DeckService.CreateCard:input_type -> pb.CreateCardRequest
	21, // 19: pb.DeckService.BulkCreateCards:input_type -> pb.BulkCreateCardsRequest
	22, // 20: pb.DeckService.ParseImportFile:input_type -> pb.ParseImportFileRequest
	23, // 21: pb.DeckService.GetCard:input_type -> pb.GetCardRequest
	24, // 22: pb.DeckService.UpdateCard:input_type -> pb.UpdateCardRequest
	25, // 23: pb.DeckService.DeleteCard:input_type -> pb.DeleteCardRequest
	0,  // 24: pb.DeckService.ReportDeck:input_type -> pb.ReportDeckRequest
	26, // 25: pb.DeckService.ListFolders:output_type -> pb.ListFoldersResponse
	27, // 26: pb.DeckService.CreateFolder:output_type -> pb.CreateFolderResponse
	28, // 27: pb.DeckService.GetFolder:output_type -> pb.GetFolderResponse
	29, // 28: pb.DeckService.UpdateFolder:output_type -> pb.UpdateFolderResponse
	30, // 29: pb.DeckService.DeleteFolder:output_type -> pb.DeleteFolderResponse
	31, // 30: pb.DeckService.AddDeckToFolder:output_type -> pb.AddDeckToFolderResponse
	32, // 31: pb.DeckService.RemoveDeckFromFolder:output_type -> pb.RemoveDeckFromFolderResponse
	33, // 32: pb.DeckService.ListDecks:output_type -> pb.ListDecksResponse
	34, // 33: pb.DeckService.CreateDeck:output_type -> pb.CreateDeckResponse
	35, // 34: pb.DeckService.ListPublicDecks:output_type -> pb.ListPublicDecksResponse
	36, // 35: pb.DeckService.GetDeck:output_type -> pb.GetDeckResponse
	37, // 36: pb.DeckService.UpdateDeck:output_type -> pb.UpdateDeckResponse
	38, // 37: pb.DeckService.DeleteDeck:output_type -> pb.DeleteDeckResponse
	39, // 38: pb.DeckService.UpdateDeckSettings:output_type -> pb.UpdateDeckSettingsResponse
	40, // 39: pb.DeckService.UpdateDeckVisibility:output_type -> pb.UpdateDeckVisibilityResponse
	41, // 40: pb.DeckService.CloneDeck:output_type -> pb.CloneDeckResponse
	42, // 41: pb.DeckService.GetDeckStats:output_type -> pb.GetDeckStatsResponse
	43, // 42: pb.DeckService.ListDeckCards:output_type -> pb.ListDeckCardsResponse
	44, // 43: pb.DeckService.CreateCard:output_type -> pb.CreateCardResponse
	45, // 44: pb.DeckService.BulkCreateCards:output_type -> pb.BulkCreateCardsResponse
	46, // 45: pb.DeckService.ParseImportFile:output_type -> pb.ParseImportFileResponse
	47, // 46: pb.DeckService.GetCard:output_type -> pb.GetCardResponse
	48, // 47: pb.DeckService.UpdateCard:output_type -> pb.UpdateCardResponse
	49, // 48: pb.DeckService.DeleteCard:output_type -> pb.DeleteCardResponse
	1,  // 49: pb.DeckService.ReportDeck:output_type -> pb.ReportDeckResponse
	25, // [25:50] is the sub-list for method output_type
	0,  // [0:25] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_deck_service_proto_init() }
func file_deck_service_proto_init() {
	if File_deck_service_proto != nil {
		return
	}
	file_rpc_folder_proto_init()
	file_rpc_deck_proto_init()
	file_rpc_card_proto_init()
	file_rpc_import_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deck_service_proto_rawDesc), len(file_deck_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deck_service_proto_goTypes,
		DependencyIndexes: file_deck_service_proto_depIdxs,
		MessageInfos:      file_deck_service_proto_msgTypes,
	}.Build()
	File_deck_service_proto = out.File
	file_deck_service_proto_goTypes = nil
	file_deck_service_proto_depIdxs = nil
}
