// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: models.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Folder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      string                 `protobuf:"bytes,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Folder) Reset() {
	*x = Folder{}
	mi := &file_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Folder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folder) ProtoMessage() {}

func (x *Folder) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folder.ProtoReflect.Descriptor instead.
func (*Folder) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{0}
}

func (x *Folder) GetFolderId() string {
	if x != nil {
		return x.FolderId
	}
	return ""
}

func (x *Folder) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Folder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Folder) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Folder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Folder) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type FolderWithDecks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        *Folder                `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	Decks         []*Deck                `protobuf:"bytes,2,rep,name=decks,proto3" json:"decks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderWithDecks) Reset() {
	*x = FolderWithDecks{}
	mi := &file_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderWithDecks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderWithDecks) ProtoMessage() {}

func (x *FolderWithDecks) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderWithDecks.ProtoReflect.Descriptor instead.
func (*FolderWithDecks) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{1}
}

func (x *FolderWithDecks) GetFolder() *Folder {
	if x != nil {
		return x.Folder
	}
	return nil
}

func (x *FolderWithDecks) GetDecks() []*Deck {
	if x != nil {
		return x.Decks
	}
	return nil
}

type DeckSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuizType       string                 `protobuf:"bytes,1,opt,name=quiz_type,json=quizType,proto3" json:"quiz_type,omitempty"`
	AnswerSide     string                 `protobuf:"bytes,2,opt,name=answer_side,json=answerSide,proto3" json:"answer_side,omitempty"`
	StrictTyping   bool                   `protobuf:"varint,3,opt,name=strict_typing,json=strictTyping,proto3" json:"strict_typing,omitempty"`
	PartialCorrect bool                   `protobuf:"varint,4,opt,name=partial_correct,json=partialCorrect,proto3" json:"partial_correct,omitempty"`
	NewCardsPerDay int32                  `protobuf:"varint,5,opt,name=new_cards_per_day,json=newCardsPerDay,proto3" json:"new_cards_per_day,omitempty"`
	ReviewsPerDay  int32                  `protobuf:"varint,6,opt,name=reviews_per_day,json=reviewsPerDay,proto3" json:"reviews_per_day,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeckSettings) Reset() {
	*x = DeckSettings{}
	mi := &file_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckSettings) ProtoMessage() {}

func (x *DeckSettings) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckSettings.ProtoReflect.Descriptor instead.
func (*DeckSettings) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{2}
}

func (x *DeckSettings) GetQuizType() string {
	if x != nil {
		return x.QuizType
	}
	return ""
}

func (x *DeckSettings) GetAnswerSide() string {
	if x != nil {
		return x.AnswerSide
	}
	return ""
}

func (x *DeckSettings) GetStrictTyping() bool {
	if x != nil {
		return x.StrictTyping
	}
	return false
}

func (x *DeckSettings) GetPartialCorrect() bool {
	if x != nil {
		return x.PartialCorrect
	}
	return false
}

func (x *DeckSettings) GetNewCardsPerDay() int32 {
	if x != nil {
		return x.NewCardsPerDay
	}
	return 0
}

func (x *DeckSettings) GetReviewsPerDay() int32 {
	if x != nil {
		return x.ReviewsPerDay
	}
	return 0
}

type Deck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Settings      *DeckSettings          `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	CardCount     int32                  `protobuf:"varint,8,opt,name=card_count,json=cardCount,proto3" json:"card_count,omitempty"`
	ClonedFrom    string                 `protobuf:"bytes,9,opt,name=cloned_from,json=clonedFrom,proto3" json:"cloned_from,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deck) Reset() {
	*x = Deck{}
	mi := &file_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deck) ProtoMessage() {}

func (x *Deck) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deck.ProtoReflect.Descriptor instead.
func (*Deck) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{3}
}

func (x *Deck) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *Deck) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Deck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deck) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Deck) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Deck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Deck) GetSettings() *DeckSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Deck) GetCardCount() int32 {
	if x != nil {
		return x.CardCount
	}
	return 0
}

func (x *Deck) GetClonedFrom() string {
	if x != nil {
		return x.ClonedFrom
	}
	return ""
}

func (x *Deck) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Deck) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeckId        string                 `protobuf:"bytes,3,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	NoteId        string                 `protobuf:"bytes,4,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	ContentFront  string                 `protobuf:"bytes,6,opt,name=content_front,json=contentFront,proto3" json:"content_front,omitempty"`
	ContentBack   string                 `protobuf:"bytes,7,opt,name=content_back,json=contentBack,proto3" json:"content_back,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LangFront     string                 `protobuf:"bytes,10,opt,name=lang_front,json=langFront,proto3" json:"lang_front,omitempty"`
	LangBack      string                 `protobuf:"bytes,11,opt,name=lang_back,json=langBack,proto3" json:"lang_back,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{4}
}

func (x *Card) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *Card) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Card) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *Card) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *Card) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Card) GetContentFront() string {
	if x != nil {
		return x.ContentFront
	}
	return ""
}

func (x *Card) GetContentBack() string {
	if x != nil {
		return x.ContentBack
	}
	return ""
}

func (x *Card) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Card) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Card) GetLangFront() string {
	if x != nil {
		return x.LangFront
	}
	return ""
}

func (x *Card) GetLangBack() string {
	if x != nil {
		return x.LangBack
	}
	return ""
}

type DeckStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	TotalCards    int32                  `protobuf:"varint,2,opt,name=total_cards,json=totalCards,proto3" json:"total_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckStats) Reset() {
	*x = DeckStats{}
	mi := &file_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckStats) ProtoMessage() {}

func (x *DeckStats) ProtoReflect() protoreflect.Message {
	mi := &file_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckStats.ProtoReflect.Descriptor instead.
func (*DeckStats) Descriptor() ([]byte, []int) {
	return file_models_proto_rawDescGZIP(), []int{5}
}

func (x *DeckStats) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *DeckStats) GetTotalCards() int32 {
	if x != nil {
		return x.TotalCards
	}
	return 0
}

var File_models_proto protoreflect.FileDescriptor

const file_models_proto_rawDesc = "" +
	"\n" +
	"\fmodels.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x01\n" +
	"\x06Folder\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\tR\bfolderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"U\n" +
	"\x0fFolderWithDecks\x12\"\n" +
	"\x06folder\x18\x01 \x01(\v2\n" +
	".pb.FolderR\x06folder\x12\x1e\n" +
	"\x05decks\x18\x02 \x03(\v2\b.pb.DeckR\x05decks\"\xed\x01\n" +
	"\fDeckSettings\x12\x1b\n" +
	"\tquiz_type\x18\x01 \x01(\tR\bquizType\x12\x1f\n" +
	"\vanswer_side\x18\x02 \x01(\tR\n" +
	"answerSide\x12#\n" +
	"\rstrict_typing\x18\x03 \x01(\bR\fstrictTyping\x12'\n" +
	"\x0fpartial_correct\x18\x04 \x01(\bR\x0epartialCorrect\x12)\n" +
	"\x11new_cards_per_day\x18\x05 \x01(\x05R\x0enewCardsPerDay\x12&\n" +
	"\x0freviews_per_day\x18\x06 \x01(\x05R\rreviewsPerDay\"\x87\x03\n" +
	"\x04Deck\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12,\n" +
	"\bsettings\x18\a \x01(\v2\x10.pb.DeckSettingsR\bsettings\x12\x1d\n" +
	"\n" +
	"card_count\x18\b \x01(\x05R\tcardCount\x12\x1f\n" +
	"\vcloned_from\x18\t \x01(\tR\n" +
	"clonedFrom\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe2\x02\n" +
	"\x04Card\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\adeck_id\x18\x03 \x01(\tR\x06deckId\x12\x17\n" +
	"\anote_id\x18\x04 \x01(\tR\x06noteId\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12#\n" +
	"\rcontent_front\x18\x06 \x01(\tR\fcontentFront\x12!\n" +
	"\fcontent_back\x18\a \x01(\tR\vcontentBack\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"lang_front\x18\n" +
	" \x01(\tR\tlangFront\x12\x1b\n" +
	"\tlang_back\x18\v \x01(\tR\blangBack\"E\n" +
	"\tDeckStats\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x1f\n" +
	"\vtotal_cards\x18\x02 \x01(\x05R\n" +
	"totalCardsB\"Z mem_pan/services/deck-service/pbb\x06proto3"

var (
	file_models_proto_rawDescOnce sync.Once
	file_models_proto_rawDescData []byte
)

func file_models_proto_rawDescGZIP() []byte {
	file_models_proto_rawDescOnce.Do(func() {
		file_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_proto_rawDesc), len(file_models_proto_rawDesc)))
	})
	return file_models_proto_rawDescData
}

var file_models_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_models_proto_goTypes = []any{
	(*Folder)(nil),                // 0: pb.Folder
	(*FolderWithDecks)(nil),       // 1: pb.FolderWithDecks
	(*DeckSettings)(nil),          // 2: pb.DeckSettings
	(*Deck)(nil),                  // 3: pb.Deck
	(*Card)(nil),                  // 4: pb.Card
	(*DeckStats)(nil),             // 5: pb.DeckStats
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_models_proto_depIdxs = []int32{
	6, // 0: pb.Folder.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: pb.Folder.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: pb.FolderWithDecks.folder:type_name -> pb.Folder
	3, // 3: pb.FolderWithDecks.decks:type_name -> pb.Deck
	2, // 4: pb.Deck.settings:type_name -> pb.DeckSettings
	6, // 5: pb.Deck.created_at:type_name -> google.protobuf.Timestamp
	6, // 6: pb.Deck.updated_at:type_name -> google.protobuf.Timestamp
	6, // 7: pb.Card.created_at:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_models_proto_init() }
func file_models_proto_init() {
	if File_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_proto_rawDesc), len(file_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_proto_goTypes,
		DependencyIndexes: file_models_proto_depIdxs,
		MessageInfos:      file_models_proto_msgTypes,
	}.Build()
	File_models_proto = out.File
	file_models_proto_goTypes = nil
	file_models_proto_depIdxs = nil
}
