// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc_deck.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecksRequest) Reset() {
	*x = ListDecksRequest{}
	mi := &file_rpc_deck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecksRequest) ProtoMessage() {}

func (x *ListDecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecksRequest.ProtoReflect.Descriptor instead.
func (*ListDecksRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{0}
}

func (x *ListDecksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDecksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListDecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decks         []*Deck                `protobuf:"bytes,1,rep,name=decks,proto3" json:"decks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecksResponse) Reset() {
	*x = ListDecksResponse{}
	mi := &file_rpc_deck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecksResponse) ProtoMessage() {}

func (x *ListDecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecksResponse.ProtoReflect.Descriptor instead.
func (*ListDecksResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{1}
}

func (x *ListDecksResponse) GetDecks() []*Deck {
	if x != nil {
		return x.Decks
	}
	return nil
}

func (x *ListDecksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateDeckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,3,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeckRequest) Reset() {
	*x = CreateDeckRequest{}
	mi := &file_rpc_deck_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeckRequest) ProtoMessage() {}

func (x *CreateDeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeckRequest.ProtoReflect.Descriptor instead.
func (*CreateDeckRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDeckRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDeckRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDeckRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type CreateDeckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck          *Deck                  `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeckResponse) Reset() {
	*x = CreateDeckResponse{}
	mi := &file_rpc_deck_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeckResponse) ProtoMessage() {}

func (x *CreateDeckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeckResponse.ProtoReflect.Descriptor instead.
func (*CreateDeckResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDeckResponse) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type ListPublicDecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccessLevel   string                 `protobuf:"bytes,4,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicDecksRequest) Reset() {
	*x = ListPublicDecksRequest{}
	mi := &file_rpc_deck_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicDecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicDecksRequest) ProtoMessage() {}

func (x *ListPublicDecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicDecksRequest.ProtoReflect.Descriptor instead.
func (*ListPublicDecksRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{4}
}

func (x *ListPublicDecksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPublicDecksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPublicDecksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListPublicDecksRequest) GetAccessLevel() string {
	if x != nil {
		return x.AccessLevel
	}
	return ""
}

type ListPublicDecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decks         []*Deck                `protobuf:"bytes,1,rep,name=decks,proto3" json:"decks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublicDecksResponse) Reset() {
	*x = ListPublicDecksResponse{}
	mi := &file_rpc_deck_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublicDecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublicDecksResponse) ProtoMessage() {}

func (x *ListPublicDecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublicDecksResponse.ProtoReflect.Descriptor instead.
func (*ListPublicDecksResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{5}
}

func (x *ListPublicDecksResponse) GetDecks() []*Deck {
	if x != nil {
		return x.Decks
	}
	return nil
}

func (x *ListPublicDecksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListTopPublicDecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`                             // max decks; <=0 falls back to 10
	WindowDays    int32                  `protobuf:"varint,2,opt,name=window_days,json=windowDays,proto3" json:"window_days,omitempty"` // trending window; <=0 falls back to 7 days
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopPublicDecksRequest) Reset() {
	*x = ListTopPublicDecksRequest{}
	mi := &file_rpc_deck_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopPublicDecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopPublicDecksRequest) ProtoMessage() {}

func (x *ListTopPublicDecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopPublicDecksRequest.ProtoReflect.Descriptor instead.
func (*ListTopPublicDecksRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{6}
}

func (x *ListTopPublicDecksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTopPublicDecksRequest) GetWindowDays() int32 {
	if x != nil {
		return x.WindowDays
	}
	return 0
}

type RankedPublicDeck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck          *Deck                  `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	LearnerCount  int64                  `protobuf:"varint,2,opt,name=learner_count,json=learnerCount,proto3" json:"learner_count,omitempty"` // distinct learners within the trending window
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankedPublicDeck) Reset() {
	*x = RankedPublicDeck{}
	mi := &file_rpc_deck_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankedPublicDeck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankedPublicDeck) ProtoMessage() {}

func (x *RankedPublicDeck) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankedPublicDeck.ProtoReflect.Descriptor instead.
func (*RankedPublicDeck) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{7}
}

func (x *RankedPublicDeck) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

func (x *RankedPublicDeck) GetLearnerCount() int64 {
	if x != nil {
		return x.LearnerCount
	}
	return 0
}

type ListTopPublicDecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decks         []*RankedPublicDeck    `protobuf:"bytes,1,rep,name=decks,proto3" json:"decks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopPublicDecksResponse) Reset() {
	*x = ListTopPublicDecksResponse{}
	mi := &file_rpc_deck_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopPublicDecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopPublicDecksResponse) ProtoMessage() {}

func (x *ListTopPublicDecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopPublicDecksResponse.ProtoReflect.Descriptor instead.
func (*ListTopPublicDecksResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{8}
}

func (x *ListTopPublicDecksResponse) GetDecks() []*RankedPublicDeck {
	if x != nil {
		return x.Decks
	}
	return nil
}

type GetDeckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeckRequest) Reset() {
	*x = GetDeckRequest{}
	mi := &file_rpc_deck_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeckRequest) ProtoMessage() {}

func (x *GetDeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeckRequest.ProtoReflect.Descriptor instead.
func (*GetDeckRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{9}
}

func (x *GetDeckRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

type GetDeckResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Deck            *Deck                  `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	CreatorUsername string                 `protobuf:"bytes,2,opt,name=creator_username,json=creatorUsername,proto3" json:"creator_username,omitempty"`
	CreatorAvatar   string                 `protobuf:"bytes,3,opt,name=creator_avatar,json=creatorAvatar,proto3" json:"creator_avatar,omitempty"`
	// Distinct users who have ever studied this deck (owner included). Best
	// effort: 0 if study-service is unreachable.
	LearnerCount  int64 `protobuf:"varint,4,opt,name=learner_count,json=learnerCount,proto3" json:"learner_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeckResponse) Reset() {
	*x = GetDeckResponse{}
	mi := &file_rpc_deck_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeckResponse) ProtoMessage() {}

func (x *GetDeckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeckResponse.ProtoReflect.Descriptor instead.
func (*GetDeckResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{10}
}

func (x *GetDeckResponse) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

func (x *GetDeckResponse) GetCreatorUsername() string {
	if x != nil {
		return x.CreatorUsername
	}
	return ""
}

func (x *GetDeckResponse) GetCreatorAvatar() string {
	if x != nil {
		return x.CreatorAvatar
	}
	return ""
}

func (x *GetDeckResponse) GetLearnerCount() int64 {
	if x != nil {
		return x.LearnerCount
	}
	return 0
}

type UpdateDeckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeckRequest) Reset() {
	*x = UpdateDeckRequest{}
	mi := &file_rpc_deck_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeckRequest) ProtoMessage() {}

func (x *UpdateDeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeckRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeckRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateDeckRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *UpdateDeckRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDeckRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateDeckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck          *Deck                  `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeckResponse) Reset() {
	*x = UpdateDeckResponse{}
	mi := &file_rpc_deck_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeckResponse) ProtoMessage() {}

func (x *UpdateDeckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeckResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeckResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDeckResponse) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type DeleteDeckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeckRequest) Reset() {
	*x = DeleteDeckRequest{}
	mi := &file_rpc_deck_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeckRequest) ProtoMessage() {}

func (x *DeleteDeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeckRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeckRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteDeckRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

type DeleteDeckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeckResponse) Reset() {
	*x = DeleteDeckResponse{}
	mi := &file_rpc_deck_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeckResponse) ProtoMessage() {}

func (x *DeleteDeckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeckResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeckResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteDeckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateDeckSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Settings      *DeckSettings          `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeckSettingsRequest) Reset() {
	*x = UpdateDeckSettingsRequest{}
	mi := &file_rpc_deck_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeckSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeckSettingsRequest) ProtoMessage() {}

func (x *UpdateDeckSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeckSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeckSettingsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateDeckSettingsRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *UpdateDeckSettingsRequest) GetSettings() *DeckSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateDeckSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck          *Deck                  `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeckSettingsResponse) Reset() {
	*x = UpdateDeckSettingsResponse{}
	mi := &file_rpc_deck_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeckSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeckSettingsResponse) ProtoMessage() {}

func (x *UpdateDeckSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeckSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeckSettingsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDeckSettingsResponse) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type UpdateDeckVisibilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	IsPublic      bool                   `protobuf:"varint,2,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeckVisibilityRequest) Reset() {
	*x = UpdateDeckVisibilityRequest{}
	mi := &file_rpc_deck_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeckVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeckVisibilityRequest) ProtoMessage() {}

func (x *UpdateDeckVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeckVisibilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeckVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDeckVisibilityRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *UpdateDeckVisibilityRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type UpdateDeckVisibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck          *Deck                  `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeckVisibilityResponse) Reset() {
	*x = UpdateDeckVisibilityResponse{}
	mi := &file_rpc_deck_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeckVisibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeckVisibilityResponse) ProtoMessage() {}

func (x *UpdateDeckVisibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeckVisibilityResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeckVisibilityResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateDeckVisibilityResponse) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type UpdateDeckAccessLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	AccessLevel   string                 `protobuf:"bytes,2,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeckAccessLevelRequest) Reset() {
	*x = UpdateDeckAccessLevelRequest{}
	mi := &file_rpc_deck_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeckAccessLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeckAccessLevelRequest) ProtoMessage() {}

func (x *UpdateDeckAccessLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeckAccessLevelRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeckAccessLevelRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateDeckAccessLevelRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *UpdateDeckAccessLevelRequest) GetAccessLevel() string {
	if x != nil {
		return x.AccessLevel
	}
	return ""
}

type UpdateDeckAccessLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck          *Deck                  `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeckAccessLevelResponse) Reset() {
	*x = UpdateDeckAccessLevelResponse{}
	mi := &file_rpc_deck_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeckAccessLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeckAccessLevelResponse) ProtoMessage() {}

func (x *UpdateDeckAccessLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeckAccessLevelResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeckAccessLevelResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateDeckAccessLevelResponse) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type CloneDeckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneDeckRequest) Reset() {
	*x = CloneDeckRequest{}
	mi := &file_rpc_deck_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneDeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneDeckRequest) ProtoMessage() {}

func (x *CloneDeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneDeckRequest.ProtoReflect.Descriptor instead.
func (*CloneDeckRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{21}
}

func (x *CloneDeckRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

type CloneDeckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck          *Deck                  `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneDeckResponse) Reset() {
	*x = CloneDeckResponse{}
	mi := &file_rpc_deck_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneDeckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneDeckResponse) ProtoMessage() {}

func (x *CloneDeckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneDeckResponse.ProtoReflect.Descriptor instead.
func (*CloneDeckResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{22}
}

func (x *CloneDeckResponse) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type GetDeckStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeckStatsRequest) Reset() {
	*x = GetDeckStatsRequest{}
	mi := &file_rpc_deck_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeckStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeckStatsRequest) ProtoMessage() {}

func (x *GetDeckStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeckStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDeckStatsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{23}
}

func (x *GetDeckStatsRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

type GetDeckStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *DeckStats             `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeckStatsResponse) Reset() {
	*x = GetDeckStatsResponse{}
	mi := &file_rpc_deck_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeckStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeckStatsResponse) ProtoMessage() {}

func (x *GetDeckStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeckStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDeckStatsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{24}
}

func (x *GetDeckStatsResponse) GetStats() *DeckStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ListDeckCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeckCardsRequest) Reset() {
	*x = ListDeckCardsRequest{}
	mi := &file_rpc_deck_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeckCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeckCardsRequest) ProtoMessage() {}

func (x *ListDeckCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeckCardsRequest.ProtoReflect.Descriptor instead.
func (*ListDeckCardsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{25}
}

func (x *ListDeckCardsRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

type ListDeckCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeckCardsResponse) Reset() {
	*x = ListDeckCardsResponse{}
	mi := &file_rpc_deck_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeckCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeckCardsResponse) ProtoMessage() {}

func (x *ListDeckCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeckCardsResponse.ProtoReflect.Descriptor instead.
func (*ListDeckCardsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{26}
}

func (x *ListDeckCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type CreateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	ContentFront  string                 `protobuf:"bytes,2,opt,name=content_front,json=contentFront,proto3" json:"content_front,omitempty"`
	ContentBack   string                 `protobuf:"bytes,3,opt,name=content_back,json=contentBack,proto3" json:"content_back,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	LangFront     string                 `protobuf:"bytes,6,opt,name=lang_front,json=langFront,proto3" json:"lang_front,omitempty"`
	LangBack      string                 `protobuf:"bytes,7,opt,name=lang_back,json=langBack,proto3" json:"lang_back,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardRequest) Reset() {
	*x = CreateCardRequest{}
	mi := &file_rpc_deck_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardRequest) ProtoMessage() {}

func (x *CreateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardRequest.ProtoReflect.Descriptor instead.
func (*CreateCardRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{27}
}

func (x *CreateCardRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *CreateCardRequest) GetContentFront() string {
	if x != nil {
		return x.ContentFront
	}
	return ""
}

func (x *CreateCardRequest) GetContentBack() string {
	if x != nil {
		return x.ContentBack
	}
	return ""
}

func (x *CreateCardRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateCardRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CreateCardRequest) GetLangFront() string {
	if x != nil {
		return x.LangFront
	}
	return ""
}

func (x *CreateCardRequest) GetLangBack() string {
	if x != nil {
		return x.LangBack
	}
	return ""
}

type CreateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCardResponse) Reset() {
	*x = CreateCardResponse{}
	mi := &file_rpc_deck_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCardResponse) ProtoMessage() {}

func (x *CreateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCardResponse.ProtoReflect.Descriptor instead.
func (*CreateCardResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{28}
}

func (x *CreateCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type BulkCardItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentFront  string                 `protobuf:"bytes,1,opt,name=content_front,json=contentFront,proto3" json:"content_front,omitempty"`
	ContentBack   string                 `protobuf:"bytes,2,opt,name=content_back,json=contentBack,proto3" json:"content_back,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	LangFront     string                 `protobuf:"bytes,4,opt,name=lang_front,json=langFront,proto3" json:"lang_front,omitempty"`
	LangBack      string                 `protobuf:"bytes,5,opt,name=lang_back,json=langBack,proto3" json:"lang_back,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCardItem) Reset() {
	*x = BulkCardItem{}
	mi := &file_rpc_deck_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCardItem) ProtoMessage() {}

func (x *BulkCardItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCardItem.ProtoReflect.Descriptor instead.
func (*BulkCardItem) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{29}
}

func (x *BulkCardItem) GetContentFront() string {
	if x != nil {
		return x.ContentFront
	}
	return ""
}

func (x *BulkCardItem) GetContentBack() string {
	if x != nil {
		return x.ContentBack
	}
	return ""
}

func (x *BulkCardItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *BulkCardItem) GetLangFront() string {
	if x != nil {
		return x.LangFront
	}
	return ""
}

func (x *BulkCardItem) GetLangBack() string {
	if x != nil {
		return x.LangBack
	}
	return ""
}

type BulkCreateCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Cards         []*BulkCardItem        `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateCardsRequest) Reset() {
	*x = BulkCreateCardsRequest{}
	mi := &file_rpc_deck_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateCardsRequest) ProtoMessage() {}

func (x *BulkCreateCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateCardsRequest.ProtoReflect.Descriptor instead.
func (*BulkCreateCardsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{30}
}

func (x *BulkCreateCardsRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *BulkCreateCardsRequest) GetCards() []*BulkCardItem {
	if x != nil {
		return x.Cards
	}
	return nil
}

type BulkCreateCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	Created       int32                  `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateCardsResponse) Reset() {
	*x = BulkCreateCardsResponse{}
	mi := &file_rpc_deck_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateCardsResponse) ProtoMessage() {}

func (x *BulkCreateCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateCardsResponse.ProtoReflect.Descriptor instead.
func (*BulkCreateCardsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{31}
}

func (x *BulkCreateCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *BulkCreateCardsResponse) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

type UpsertCreatorProfileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DisplayName       string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Bio               string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	BankName          string                 `protobuf:"bytes,3,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankAccountNumber string                 `protobuf:"bytes,4,opt,name=bank_account_number,json=bankAccountNumber,proto3" json:"bank_account_number,omitempty"`
	BankAccountName   string                 `protobuf:"bytes,5,opt,name=bank_account_name,json=bankAccountName,proto3" json:"bank_account_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpsertCreatorProfileRequest) Reset() {
	*x = UpsertCreatorProfileRequest{}
	mi := &file_rpc_deck_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertCreatorProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCreatorProfileRequest) ProtoMessage() {}

func (x *UpsertCreatorProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCreatorProfileRequest.ProtoReflect.Descriptor instead.
func (*UpsertCreatorProfileRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{32}
}

func (x *UpsertCreatorProfileRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpsertCreatorProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpsertCreatorProfileRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *UpsertCreatorProfileRequest) GetBankAccountNumber() string {
	if x != nil {
		return x.BankAccountNumber
	}
	return ""
}

func (x *UpsertCreatorProfileRequest) GetBankAccountName() string {
	if x != nil {
		return x.BankAccountName
	}
	return ""
}

type UpsertCreatorProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *CreatorProfile        `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertCreatorProfileResponse) Reset() {
	*x = UpsertCreatorProfileResponse{}
	mi := &file_rpc_deck_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertCreatorProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertCreatorProfileResponse) ProtoMessage() {}

func (x *UpsertCreatorProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertCreatorProfileResponse.ProtoReflect.Descriptor instead.
func (*UpsertCreatorProfileResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{33}
}

func (x *UpsertCreatorProfileResponse) GetProfile() *CreatorProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetCreatorProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreatorProfileRequest) Reset() {
	*x = GetCreatorProfileRequest{}
	mi := &file_rpc_deck_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreatorProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreatorProfileRequest) ProtoMessage() {}

func (x *GetCreatorProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreatorProfileRequest.ProtoReflect.Descriptor instead.
func (*GetCreatorProfileRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{34}
}

func (x *GetCreatorProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCreatorProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *CreatorProfile        `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreatorProfileResponse) Reset() {
	*x = GetCreatorProfileResponse{}
	mi := &file_rpc_deck_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreatorProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreatorProfileResponse) ProtoMessage() {}

func (x *GetCreatorProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreatorProfileResponse.ProtoReflect.Descriptor instead.
func (*GetCreatorProfileResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{35}
}

func (x *GetCreatorProfileResponse) GetProfile() *CreatorProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type FollowCreatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowCreatorRequest) Reset() {
	*x = FollowCreatorRequest{}
	mi := &file_rpc_deck_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowCreatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowCreatorRequest) ProtoMessage() {}

func (x *FollowCreatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowCreatorRequest.ProtoReflect.Descriptor instead.
func (*FollowCreatorRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{36}
}

func (x *FollowCreatorRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type FollowCreatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowCreatorResponse) Reset() {
	*x = FollowCreatorResponse{}
	mi := &file_rpc_deck_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowCreatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowCreatorResponse) ProtoMessage() {}

func (x *FollowCreatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowCreatorResponse.ProtoReflect.Descriptor instead.
func (*FollowCreatorResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{37}
}

func (x *FollowCreatorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpsertDeckReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDeckReviewRequest) Reset() {
	*x = UpsertDeckReviewRequest{}
	mi := &file_rpc_deck_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDeckReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDeckReviewRequest) ProtoMessage() {}

func (x *UpsertDeckReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDeckReviewRequest.ProtoReflect.Descriptor instead.
func (*UpsertDeckReviewRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{38}
}

func (x *UpsertDeckReviewRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *UpsertDeckReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UpsertDeckReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type UpsertDeckReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *DeckReview            `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	Deck          *Deck                  `protobuf:"bytes,2,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDeckReviewResponse) Reset() {
	*x = UpsertDeckReviewResponse{}
	mi := &file_rpc_deck_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDeckReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDeckReviewResponse) ProtoMessage() {}

func (x *UpsertDeckReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDeckReviewResponse.ProtoReflect.Descriptor instead.
func (*UpsertDeckReviewResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{39}
}

func (x *UpsertDeckReviewResponse) GetReview() *DeckReview {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *UpsertDeckReviewResponse) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type ListDeckReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeckReviewsRequest) Reset() {
	*x = ListDeckReviewsRequest{}
	mi := &file_rpc_deck_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeckReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeckReviewsRequest) ProtoMessage() {}

func (x *ListDeckReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeckReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListDeckReviewsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{40}
}

func (x *ListDeckReviewsRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *ListDeckReviewsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDeckReviewsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListDeckReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*DeckReview          `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeckReviewsResponse) Reset() {
	*x = ListDeckReviewsResponse{}
	mi := &file_rpc_deck_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeckReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeckReviewsResponse) ProtoMessage() {}

func (x *ListDeckReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_deck_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeckReviewsResponse.ProtoReflect.Descriptor instead.
func (*ListDeckReviewsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_deck_proto_rawDescGZIP(), []int{41}
}

func (x *ListDeckReviewsResponse) GetReviews() []*DeckReview {
	if x != nil {
		return x.Reviews
	}
	return nil
}

var File_rpc_deck_proto protoreflect.FileDescriptor

const file_rpc_deck_proto_rawDesc = "" +
	"\n" +
	"\x0erpc_deck.proto\x12\x02pb\x1a\fmodels.proto\"C\n" +
	"\x10ListDecksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"I\n" +
	"\x11ListDecksResponse\x12\x1e\n" +
	"\x05decks\x18\x01 \x03(\v2\b.pb.DeckR\x05decks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"f\n" +
	"\x11CreateDeckRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_public\x18\x03 \x01(\bR\bisPublic\"2\n" +
	"\x12CreateDeckResponse\x12\x1c\n" +
	"\x04deck\x18\x01 \x01(\v2\b.pb.DeckR\x04deck\"\x85\x01\n" +
	"\x16ListPublicDecksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12!\n" +
	"\faccess_level\x18\x04 \x01(\tR\vaccessLevel\"O\n" +
	"\x17ListPublicDecksResponse\x12\x1e\n" +
	"\x05decks\x18\x01 \x03(\v2\b.pb.DeckR\x05decks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"R\n" +
	"\x19ListTopPublicDecksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vwindow_days\x18\x02 \x01(\x05R\n" +
	"windowDays\"U\n" +
	"\x10RankedPublicDeck\x12\x1c\n" +
	"\x04deck\x18\x01 \x01(\v2\b.pb.DeckR\x04deck\x12#\n" +
	"\rlearner_count\x18\x02 \x01(\x03R\flearnerCount\"H\n" +
	"\x1aListTopPublicDecksResponse\x12*\n" +
	"\x05decks\x18\x01 \x03(\v2\x14.pb.RankedPublicDeckR\x05decks\")\n" +
	"\x0eGetDeckRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\"\xa6\x01\n" +
	"\x0fGetDeckResponse\x12\x1c\n" +
	"\x04deck\x18\x01 \x01(\v2\b.pb.DeckR\x04deck\x12)\n" +
	"\x10creator_username\x18\x02 \x01(\tR\x0fcreatorUsername\x12%\n" +
	"\x0ecreator_avatar\x18\x03 \x01(\tR\rcreatorAvatar\x12#\n" +
	"\rlearner_count\x18\x04 \x01(\x03R\flearnerCount\"b\n" +
	"\x11UpdateDeckRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"2\n" +
	"\x12UpdateDeckResponse\x12\x1c\n" +
	"\x04deck\x18\x01 \x01(\v2\b.pb.DeckR\x04deck\",\n" +
	"\x11DeleteDeckRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\".\n" +
	"\x12DeleteDeckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"b\n" +
	"\x19UpdateDeckSettingsRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12,\n" +
	"\bsettings\x18\x02 \x01(\v2\x10.pb.DeckSettingsR\bsettings\":\n" +
	"\x1aUpdateDeckSettingsResponse\x12\x1c\n" +
	"\x04deck\x18\x01 \x01(\v2\b.pb.DeckR\x04deck\"S\n" +
	"\x1bUpdateDeckVisibilityRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x1b\n" +
	"\tis_public\x18\x02 \x01(\bR\bisPublic\"<\n" +
	"\x1cUpdateDeckVisibilityResponse\x12\x1c\n" +
	"\x04deck\x18\x01 \x01(\v2\b.pb.DeckR\x04deck\"Z\n" +
	"\x1cUpdateDeckAccessLevelRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12!\n" +
	"\faccess_level\x18\x02 \x01(\tR\vaccessLevel\"=\n" +
	"\x1dUpdateDeckAccessLevelResponse\x12\x1c\n" +
	"\x04deck\x18\x01 \x01(\v2\b.pb.DeckR\x04deck\"+\n" +
	"\x10CloneDeckRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\"1\n" +
	"\x11CloneDeckResponse\x12\x1c\n" +
	"\x04deck\x18\x01 \x01(\v2\b.pb.DeckR\x04deck\".\n" +
	"\x13GetDeckStatsRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\";\n" +
	"\x14GetDeckStatsResponse\x12#\n" +
	"\x05stats\x18\x01 \x01(\v2\r.pb.DeckStatsR\x05stats\"/\n" +
	"\x14ListDeckCardsRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\"7\n" +
	"\x15ListDeckCardsResponse\x12\x1e\n" +
	"\x05cards\x18\x01 \x03(\v2\b.pb.CardR\x05cards\"\xe9\x01\n" +
	"\x11CreateCardRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12#\n" +
	"\rcontent_front\x18\x02 \x01(\tR\fcontentFront\x12!\n" +
	"\fcontent_back\x18\x03 \x01(\tR\vcontentBack\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12\x1d\n" +
	"\n" +
	"lang_front\x18\x06 \x01(\tR\tlangFront\x12\x1b\n" +
	"\tlang_back\x18\a \x01(\tR\blangBack\"2\n" +
	"\x12CreateCardResponse\x12\x1c\n" +
	"\x04card\x18\x01 \x01(\v2\b.pb.CardR\x04card\"\xaf\x01\n" +
	"\fBulkCardItem\x12#\n" +
	"\rcontent_front\x18\x01 \x01(\tR\fcontentFront\x12!\n" +
	"\fcontent_back\x18\x02 \x01(\tR\vcontentBack\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"lang_front\x18\x04 \x01(\tR\tlangFront\x12\x1b\n" +
	"\tlang_back\x18\x05 \x01(\tR\blangBack\"Y\n" +
	"\x16BulkCreateCardsRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12&\n" +
	"\x05cards\x18\x02 \x03(\v2\x10.pb.BulkCardItemR\x05cards\"S\n" +
	"\x17BulkCreateCardsResponse\x12\x1e\n" +
	"\x05cards\x18\x01 \x03(\v2\b.pb.CardR\x05cards\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x05R\acreated\"\xcb\x01\n" +
	"\x1bUpsertCreatorProfileRequest\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x1b\n" +
	"\tbank_name\x18\x03 \x01(\tR\bbankName\x12.\n" +
	"\x13bank_account_number\x18\x04 \x01(\tR\x11bankAccountNumber\x12*\n" +
	"\x11bank_account_name\x18\x05 \x01(\tR\x0fbankAccountName\"L\n" +
	"\x1cUpsertCreatorProfileResponse\x12,\n" +
	"\aprofile\x18\x01 \x01(\v2\x12.pb.CreatorProfileR\aprofile\"3\n" +
	"\x18GetCreatorProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"I\n" +
	"\x19GetCreatorProfileResponse\x12,\n" +
	"\aprofile\x18\x01 \x01(\v2\x12.pb.CreatorProfileR\aprofile\"5\n" +
	"\x14FollowCreatorRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\"1\n" +
	"\x15FollowCreatorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"d\n" +
	"\x17UpsertDeckReviewRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"`\n" +
	"\x18UpsertDeckReviewResponse\x12&\n" +
	"\x06review\x18\x01 \x01(\v2\x0e.pb.DeckReviewR\x06review\x12\x1c\n" +
	"\x04deck\x18\x02 \x01(\v2\b.pb.DeckR\x04deck\"b\n" +
	"\x16ListDeckReviewsRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"C\n" +
	"\x17ListDeckReviewsResponse\x12(\n" +
	"\areviews\x18\x01 \x03(\v2\x0e.pb.DeckReviewR\areviewsB\"Z mem_pan/services/deck-service/pbb\x06proto3"

var (
	file_rpc_deck_proto_rawDescOnce sync.Once
	file_rpc_deck_proto_rawDescData []byte
)

func file_rpc_deck_proto_rawDescGZIP() []byte {
	file_rpc_deck_proto_rawDescOnce.Do(func() {
		file_rpc_deck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_deck_proto_rawDesc), len(file_rpc_deck_proto_rawDesc)))
	})
	return file_rpc_deck_proto_rawDescData
}

var file_rpc_deck_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_rpc_deck_proto_goTypes = []any{
	(*ListDecksRequest)(nil),              // 0: pb.ListDecksRequest
	(*ListDecksResponse)(nil),             // 1: pb.ListDecksResponse
	(*CreateDeckRequest)(nil),             // 2: pb.CreateDeckRequest
	(*CreateDeckResponse)(nil),            // 3: pb.CreateDeckResponse
	(*ListPublicDecksRequest)(nil),        // 4: pb.ListPublicDecksRequest
	(*ListPublicDecksResponse)(nil),       // 5: pb.ListPublicDecksResponse
	(*ListTopPublicDecksRequest)(nil),     // 6: pb.ListTopPublicDecksRequest
	(*RankedPublicDeck)(nil),              // 7: pb.RankedPublicDeck
	(*ListTopPublicDecksResponse)(nil),    // 8: pb.ListTopPublicDecksResponse
	(*GetDeckRequest)(nil),                // 9: pb.GetDeckRequest
	(*GetDeckResponse)(nil),               // 10: pb.GetDeckResponse
	(*UpdateDeckRequest)(nil),             // 11: pb.UpdateDeckRequest
	(*UpdateDeckResponse)(nil),            // 12: pb.UpdateDeckResponse
	(*DeleteDeckRequest)(nil),             // 13: pb.DeleteDeckRequest
	(*DeleteDeckResponse)(nil),            // 14: pb.DeleteDeckResponse
	(*UpdateDeckSettingsRequest)(nil),     // 15: pb.UpdateDeckSettingsRequest
	(*UpdateDeckSettingsResponse)(nil),    // 16: pb.UpdateDeckSettingsResponse
	(*UpdateDeckVisibilityRequest)(nil),   // 17: pb.UpdateDeckVisibilityRequest
	(*UpdateDeckVisibilityResponse)(nil),  // 18: pb.UpdateDeckVisibilityResponse
	(*UpdateDeckAccessLevelRequest)(nil),  // 19: pb.UpdateDeckAccessLevelRequest
	(*UpdateDeckAccessLevelResponse)(nil), // 20: pb.UpdateDeckAccessLevelResponse
	(*CloneDeckRequest)(nil),              // 21: pb.CloneDeckRequest
	(*CloneDeckResponse)(nil),             // 22: pb.CloneDeckResponse
	(*GetDeckStatsRequest)(nil),           // 23: pb.GetDeckStatsRequest
	(*GetDeckStatsResponse)(nil),          // 24: pb.GetDeckStatsResponse
	(*ListDeckCardsRequest)(nil),          // 25: pb.ListDeckCardsRequest
	(*ListDeckCardsResponse)(nil),         // 26: pb.ListDeckCardsResponse
	(*CreateCardRequest)(nil),             // 27: pb.CreateCardRequest
	(*CreateCardResponse)(nil),            // 28: pb.CreateCardResponse
	(*BulkCardItem)(nil),                  // 29: pb.BulkCardItem
	(*BulkCreateCardsRequest)(nil),        // 30: pb.BulkCreateCardsRequest
	(*BulkCreateCardsResponse)(nil),       // 31: pb.BulkCreateCardsResponse
	(*UpsertCreatorProfileRequest)(nil),   // 32: pb.UpsertCreatorProfileRequest
	(*UpsertCreatorProfileResponse)(nil),  // 33: pb.UpsertCreatorProfileResponse
	(*GetCreatorProfileRequest)(nil),      // 34: pb.GetCreatorProfileRequest
	(*GetCreatorProfileResponse)(nil),     // 35: pb.GetCreatorProfileResponse
	(*FollowCreatorRequest)(nil),          // 36: pb.FollowCreatorRequest
	(*FollowCreatorResponse)(nil),         // 37: pb.FollowCreatorResponse
	(*UpsertDeckReviewRequest)(nil),       // 38: pb.UpsertDeckReviewRequest
	(*UpsertDeckReviewResponse)(nil),      // 39: pb.UpsertDeckReviewResponse
	(*ListDeckReviewsRequest)(nil),        // 40: pb.ListDeckReviewsRequest
	(*ListDeckReviewsResponse)(nil),       // 41: pb.ListDeckReviewsResponse
	(*Deck)(nil),                          // 42: pb.Deck
	(*DeckSettings)(nil),                  // 43: pb.DeckSettings
	(*DeckStats)(nil),                     // 44: pb.DeckStats
	(*Card)(nil),                          // 45: pb.Card
	(*CreatorProfile)(nil),                // 46: pb.CreatorProfile
	(*DeckReview)(nil),                    // 47: pb.DeckReview
}
var file_rpc_deck_proto_depIdxs = []int32{
	42, // 0: pb.ListDecksResponse.decks:type_name -> pb.Deck
	42, // 1: pb.CreateDeckResponse.deck:type_name -> pb.Deck
	42, // 2: pb.ListPublicDecksResponse.decks:type_name -> pb.Deck
	42, // 3: pb.RankedPublicDeck.deck:type_name -> pb.Deck
	7,  // 4: pb.ListTopPublicDecksResponse.decks:type_name -> pb.RankedPublicDeck
	42, // 5: pb.GetDeckResponse.deck:type_name -> pb.Deck
	42, // 6: pb.UpdateDeckResponse.deck:type_name -> pb.Deck
	43, // 7: pb.UpdateDeckSettingsRequest.settings:type_name -> pb.DeckSettings
	42, // 8: pb.UpdateDeckSettingsResponse.deck:type_name -> pb.Deck
	42, // 9: pb.UpdateDeckVisibilityResponse.deck:type_name -> pb.Deck
	42, // 10: pb.UpdateDeckAccessLevelResponse.deck:type_name -> pb.Deck
	42, // 11: pb.CloneDeckResponse.deck:type_name -> pb.Deck
	44, // 12: pb.GetDeckStatsResponse.stats:type_name -> pb.DeckStats
	45, // 13: pb.ListDeckCardsResponse.cards:type_name -> pb.Card
	45, // 14: pb.CreateCardResponse.card:type_name -> pb.Card
	29, // 15: pb.BulkCreateCardsRequest.cards:type_name -> pb.BulkCardItem
	45, // 16: pb.BulkCreateCardsResponse.cards:type_name -> pb.Card
	46, // 17: pb.UpsertCreatorProfileResponse.profile:type_name -> pb.CreatorProfile
	46, // 18: pb.GetCreatorProfileResponse.profile:type_name -> pb.CreatorProfile
	47, // 19: pb.UpsertDeckReviewResponse.review:type_name -> pb.DeckReview
	42, // 20: pb.UpsertDeckReviewResponse.deck:type_name -> pb.Deck
	47, // 21: pb.ListDeckReviewsResponse.reviews:type_name -> pb.DeckReview
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_rpc_deck_proto_init() }
func file_rpc_deck_proto_init() {
	if File_rpc_deck_proto != nil {
		return
	}
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_deck_proto_rawDesc), len(file_rpc_deck_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_deck_proto_goTypes,
		DependencyIndexes: file_rpc_deck_proto_depIdxs,
		MessageInfos:      file_rpc_deck_proto_msgTypes,
	}.Build()
	File_rpc_deck_proto = out.File
	file_rpc_deck_proto_goTypes = nil
	file_rpc_deck_proto_depIdxs = nil
}
