// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc_card.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_rpc_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_rpc_card_proto_rawDescGZIP(), []int{0}
}

func (x *GetCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type GetCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_rpc_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_rpc_card_proto_rawDescGZIP(), []int{1}
}

func (x *GetCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	ContentFront  string                 `protobuf:"bytes,2,opt,name=content_front,json=contentFront,proto3" json:"content_front,omitempty"`
	ContentBack   string                 `protobuf:"bytes,3,opt,name=content_back,json=contentBack,proto3" json:"content_back,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	LangFront     string                 `protobuf:"bytes,5,opt,name=lang_front,json=langFront,proto3" json:"lang_front,omitempty"`
	LangBack      string                 `protobuf:"bytes,6,opt,name=lang_back,json=langBack,proto3" json:"lang_back,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_rpc_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_rpc_card_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *UpdateCardRequest) GetContentFront() string {
	if x != nil {
		return x.ContentFront
	}
	return ""
}

func (x *UpdateCardRequest) GetContentBack() string {
	if x != nil {
		return x.ContentBack
	}
	return ""
}

func (x *UpdateCardRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateCardRequest) GetLangFront() string {
	if x != nil {
		return x.LangFront
	}
	return ""
}

func (x *UpdateCardRequest) GetLangBack() string {
	if x != nil {
		return x.LangBack
	}
	return ""
}

type UpdateCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardResponse) Reset() {
	*x = UpdateCardResponse{}
	mi := &file_rpc_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardResponse) ProtoMessage() {}

func (x *UpdateCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardResponse) Descriptor() ([]byte, []int) {
	return file_rpc_card_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_rpc_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_rpc_card_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

type DeleteCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardResponse) Reset() {
	*x = DeleteCardResponse{}
	mi := &file_rpc_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardResponse) ProtoMessage() {}

func (x *DeleteCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardResponse) Descriptor() ([]byte, []int) {
	return file_rpc_card_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpc_card_proto protoreflect.FileDescriptor

const file_rpc_card_proto_rawDesc = "" +
	"\n" +
	"\x0erpc_card.proto\x12\x02pb\x1a\fmodels.proto\")\n" +
	"\x0eGetCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"/\n" +
	"\x0fGetCardResponse\x12\x1c\n" +
	"\x04card\x18\x01 \x01(\v2\b.pb.CardR\x04card\"\xcd\x01\n" +
	"\x11UpdateCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12#\n" +
	"\rcontent_front\x18\x02 \x01(\tR\fcontentFront\x12!\n" +
	"\fcontent_back\x18\x03 \x01(\tR\vcontentBack\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"lang_front\x18\x05 \x01(\tR\tlangFront\x12\x1b\n" +
	"\tlang_back\x18\x06 \x01(\tR\blangBack\"2\n" +
	"\x12UpdateCardResponse\x12\x1c\n" +
	"\x04card\x18\x01 \x01(\v2\b.pb.CardR\x04card\",\n" +
	"\x11DeleteCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\".\n" +
	"\x12DeleteCardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\"Z mem_pan/services/deck-service/pbb\x06proto3"

var (
	file_rpc_card_proto_rawDescOnce sync.Once
	file_rpc_card_proto_rawDescData []byte
)

func file_rpc_card_proto_rawDescGZIP() []byte {
	file_rpc_card_proto_rawDescOnce.Do(func() {
		file_rpc_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_card_proto_rawDesc), len(file_rpc_card_proto_rawDesc)))
	})
	return file_rpc_card_proto_rawDescData
}

var file_rpc_card_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_card_proto_goTypes = []any{
	(*GetCardRequest)(nil),     // 0: pb.GetCardRequest
	(*GetCardResponse)(nil),    // 1: pb.GetCardResponse
	(*UpdateCardRequest)(nil),  // 2: pb.UpdateCardRequest
	(*UpdateCardResponse)(nil), // 3: pb.UpdateCardResponse
	(*DeleteCardRequest)(nil),  // 4: pb.DeleteCardRequest
	(*DeleteCardResponse)(nil), // 5: pb.DeleteCardResponse
	(*Card)(nil),               // 6: pb.Card
}
var file_rpc_card_proto_depIdxs = []int32{
	6, // 0: pb.GetCardResponse.card:type_name -> pb.Card
	6, // 1: pb.UpdateCardResponse.card:type_name -> pb.Card
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_card_proto_init() }
func file_rpc_card_proto_init() {
	if File_rpc_card_proto != nil {
		return
	}
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_card_proto_rawDesc), len(file_rpc_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_card_proto_goTypes,
		DependencyIndexes: file_rpc_card_proto_depIdxs,
		MessageInfos:      file_rpc_card_proto_msgTypes,
	}.Build()
	File_rpc_card_proto = out.File
	file_rpc_card_proto_goTypes = nil
	file_rpc_card_proto_depIdxs = nil
}
