// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc_admin_deck.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminUpdateDeckStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // active | hidden | deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateDeckStatusRequest) Reset() {
	*x = AdminUpdateDeckStatusRequest{}
	mi := &file_rpc_admin_deck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateDeckStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateDeckStatusRequest) ProtoMessage() {}

func (x *AdminUpdateDeckStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_deck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateDeckStatusRequest.ProtoReflect.Descriptor instead.
func (*AdminUpdateDeckStatusRequest) Descriptor() ([]byte, []int) {
	return file_rpc_admin_deck_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUpdateDeckStatusRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *AdminUpdateDeckStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AdminUpdateDeckStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateDeckStatusResponse) Reset() {
	*x = AdminUpdateDeckStatusResponse{}
	mi := &file_rpc_admin_deck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateDeckStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateDeckStatusResponse) ProtoMessage() {}

func (x *AdminUpdateDeckStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_deck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateDeckStatusResponse.ProtoReflect.Descriptor instead.
func (*AdminUpdateDeckStatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_admin_deck_proto_rawDescGZIP(), []int{1}
}

func (x *AdminUpdateDeckStatusResponse) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *AdminUpdateDeckStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminUpdateDeckStatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminUpdateDeckStatusResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AdminReviewDeckPlusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	PlusStatus    string                 `protobuf:"bytes,2,opt,name=plus_status,json=plusStatus,proto3" json:"plus_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminReviewDeckPlusRequest) Reset() {
	*x = AdminReviewDeckPlusRequest{}
	mi := &file_rpc_admin_deck_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminReviewDeckPlusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminReviewDeckPlusRequest) ProtoMessage() {}

func (x *AdminReviewDeckPlusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_deck_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminReviewDeckPlusRequest.ProtoReflect.Descriptor instead.
func (*AdminReviewDeckPlusRequest) Descriptor() ([]byte, []int) {
	return file_rpc_admin_deck_proto_rawDescGZIP(), []int{2}
}

func (x *AdminReviewDeckPlusRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *AdminReviewDeckPlusRequest) GetPlusStatus() string {
	if x != nil {
		return x.PlusStatus
	}
	return ""
}

type AdminReviewDeckPlusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deck          *Deck                  `protobuf:"bytes,1,opt,name=deck,proto3" json:"deck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminReviewDeckPlusResponse) Reset() {
	*x = AdminReviewDeckPlusResponse{}
	mi := &file_rpc_admin_deck_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminReviewDeckPlusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminReviewDeckPlusResponse) ProtoMessage() {}

func (x *AdminReviewDeckPlusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_deck_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminReviewDeckPlusResponse.ProtoReflect.Descriptor instead.
func (*AdminReviewDeckPlusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_admin_deck_proto_rawDescGZIP(), []int{3}
}

func (x *AdminReviewDeckPlusResponse) GetDeck() *Deck {
	if x != nil {
		return x.Deck
	}
	return nil
}

type AdminDeckRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CardCount     int32                  `protobuf:"varint,7,opt,name=card_count,json=cardCount,proto3" json:"card_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeckRecord) Reset() {
	*x = AdminDeckRecord{}
	mi := &file_rpc_admin_deck_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeckRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeckRecord) ProtoMessage() {}

func (x *AdminDeckRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_deck_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeckRecord.ProtoReflect.Descriptor instead.
func (*AdminDeckRecord) Descriptor() ([]byte, []int) {
	return file_rpc_admin_deck_proto_rawDescGZIP(), []int{4}
}

func (x *AdminDeckRecord) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *AdminDeckRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminDeckRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminDeckRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminDeckRecord) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *AdminDeckRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminDeckRecord) GetCardCount() int32 {
	if x != nil {
		return x.CardCount
	}
	return 0
}

func (x *AdminDeckRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AdminDeckRecord) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AdminListDecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,3,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // "", "active", "hidden", "deleted"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListDecksRequest) Reset() {
	*x = AdminListDecksRequest{}
	mi := &file_rpc_admin_deck_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListDecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListDecksRequest) ProtoMessage() {}

func (x *AdminListDecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_deck_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListDecksRequest.ProtoReflect.Descriptor instead.
func (*AdminListDecksRequest) Descriptor() ([]byte, []int) {
	return file_rpc_admin_deck_proto_rawDescGZIP(), []int{5}
}

func (x *AdminListDecksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AdminListDecksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AdminListDecksRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type AdminListDecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decks         []*AdminDeckRecord     `protobuf:"bytes,1,rep,name=decks,proto3" json:"decks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListDecksResponse) Reset() {
	*x = AdminListDecksResponse{}
	mi := &file_rpc_admin_deck_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListDecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListDecksResponse) ProtoMessage() {}

func (x *AdminListDecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_admin_deck_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListDecksResponse.ProtoReflect.Descriptor instead.
func (*AdminListDecksResponse) Descriptor() ([]byte, []int) {
	return file_rpc_admin_deck_proto_rawDescGZIP(), []int{6}
}

func (x *AdminListDecksResponse) GetDecks() []*AdminDeckRecord {
	if x != nil {
		return x.Decks
	}
	return nil
}

func (x *AdminListDecksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_rpc_admin_deck_proto protoreflect.FileDescriptor

const file_rpc_admin_deck_proto_rawDesc = "" +
	"\n" +
	"\x14rpc_admin_deck.proto\x12\x02pb\x1a\fmodels.proto\"O\n" +
	"\x1cAdminUpdateDeckStatusRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"}\n" +
	"\x1dAdminUpdateDeckStatusResponse\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"V\n" +
	"\x1aAdminReviewDeckPlusRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x1f\n" +
	"\vplus_status\x18\x02 \x01(\tR\n" +
	"plusStatus\";\n" +
	"\x1bAdminReviewDeckPlusResponse\x12\x1c\n" +
	"\x04deck\x18\x01 \x01(\v2\b.pb.DeckR\x04deck\"\x8b\x02\n" +
	"\x0fAdminDeckRecord\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"card_count\x18\a \x01(\x05R\tcardCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"q\n" +
	"\x15AdminListDecksRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12#\n" +
	"\rstatus_filter\x18\x03 \x01(\tR\fstatusFilter\"Y\n" +
	"\x16AdminListDecksResponse\x12)\n" +
	"\x05decks\x18\x01 \x03(\v2\x13.pb.AdminDeckRecordR\x05decks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05totalB\"Z mem_pan/services/deck-service/pbb\x06proto3"

var (
	file_rpc_admin_deck_proto_rawDescOnce sync.Once
	file_rpc_admin_deck_proto_rawDescData []byte
)

func file_rpc_admin_deck_proto_rawDescGZIP() []byte {
	file_rpc_admin_deck_proto_rawDescOnce.Do(func() {
		file_rpc_admin_deck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_admin_deck_proto_rawDesc), len(file_rpc_admin_deck_proto_rawDesc)))
	})
	return file_rpc_admin_deck_proto_rawDescData
}

var file_rpc_admin_deck_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_admin_deck_proto_goTypes = []any{
	(*AdminUpdateDeckStatusRequest)(nil),  // 0: pb.AdminUpdateDeckStatusRequest
	(*AdminUpdateDeckStatusResponse)(nil), // 1: pb.AdminUpdateDeckStatusResponse
	(*AdminReviewDeckPlusRequest)(nil),    // 2: pb.AdminReviewDeckPlusRequest
	(*AdminReviewDeckPlusResponse)(nil),   // 3: pb.AdminReviewDeckPlusResponse
	(*AdminDeckRecord)(nil),               // 4: pb.AdminDeckRecord
	(*AdminListDecksRequest)(nil),         // 5: pb.AdminListDecksRequest
	(*AdminListDecksResponse)(nil),        // 6: pb.AdminListDecksResponse
	(*Deck)(nil),                          // 7: pb.Deck
}
var file_rpc_admin_deck_proto_depIdxs = []int32{
	7, // 0: pb.AdminReviewDeckPlusResponse.deck:type_name -> pb.Deck
	4, // 1: pb.AdminListDecksResponse.decks:type_name -> pb.AdminDeckRecord
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_admin_deck_proto_init() }
func file_rpc_admin_deck_proto_init() {
	if File_rpc_admin_deck_proto != nil {
		return
	}
	file_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_admin_deck_proto_rawDesc), len(file_rpc_admin_deck_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_admin_deck_proto_goTypes,
		DependencyIndexes: file_rpc_admin_deck_proto_depIdxs,
		MessageInfos:      file_rpc_admin_deck_proto_msgTypes,
	}.Build()
	File_rpc_admin_deck_proto = out.File
	file_rpc_admin_deck_proto_goTypes = nil
	file_rpc_admin_deck_proto_depIdxs = nil
}
