// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: stats_service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserReminderState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentStreak      int32                  `protobuf:"varint,2,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	LastStudiedDate    string                 `protobuf:"bytes,3,opt,name=last_studied_date,json=lastStudiedDate,proto3" json:"last_studied_date,omitempty"`           // YYYY-MM-DD or "" if never
	OptimalHourWeekday int32                  `protobuf:"varint,4,opt,name=optimal_hour_weekday,json=optimalHourWeekday,proto3" json:"optimal_hour_weekday,omitempty"` // 0-23, -1 if unset
	OptimalHourWeekend int32                  `protobuf:"varint,5,opt,name=optimal_hour_weekend,json=optimalHourWeekend,proto3" json:"optimal_hour_weekend,omitempty"` // 0-23, -1 if unset
	ReminderLocalTime  string                 `protobuf:"bytes,6,opt,name=reminder_local_time,json=reminderLocalTime,proto3" json:"reminder_local_time,omitempty"`     // HH:MM (24h), default "21:00"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserReminderState) Reset() {
	*x = UserReminderState{}
	mi := &file_stats_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReminderState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReminderState) ProtoMessage() {}

func (x *UserReminderState) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReminderState.ProtoReflect.Descriptor instead.
func (*UserReminderState) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserReminderState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserReminderState) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *UserReminderState) GetLastStudiedDate() string {
	if x != nil {
		return x.LastStudiedDate
	}
	return ""
}

func (x *UserReminderState) GetOptimalHourWeekday() int32 {
	if x != nil {
		return x.OptimalHourWeekday
	}
	return 0
}

func (x *UserReminderState) GetOptimalHourWeekend() int32 {
	if x != nil {
		return x.OptimalHourWeekend
	}
	return 0
}

func (x *UserReminderState) GetReminderLocalTime() string {
	if x != nil {
		return x.ReminderLocalTime
	}
	return ""
}

type ListReminderStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, return only users with current_streak >= 1 (streak-warning cron).
	OnlyActiveStreak bool `protobuf:"varint,1,opt,name=only_active_streak,json=onlyActiveStreak,proto3" json:"only_active_streak,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListReminderStateRequest) Reset() {
	*x = ListReminderStateRequest{}
	mi := &file_stats_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReminderStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReminderStateRequest) ProtoMessage() {}

func (x *ListReminderStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReminderStateRequest.ProtoReflect.Descriptor instead.
func (*ListReminderStateRequest) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListReminderStateRequest) GetOnlyActiveStreak() bool {
	if x != nil {
		return x.OnlyActiveStreak
	}
	return false
}

type ListReminderStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserReminderState   `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReminderStateResponse) Reset() {
	*x = ListReminderStateResponse{}
	mi := &file_stats_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReminderStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReminderStateResponse) ProtoMessage() {}

func (x *ListReminderStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReminderStateResponse.ProtoReflect.Descriptor instead.
func (*ListReminderStateResponse) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListReminderStateResponse) GetUsers() []*UserReminderState {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalCards       int32                  `protobuf:"varint,2,opt,name=total_cards,json=totalCards,proto3" json:"total_cards,omitempty"`
	TotalReviews     int32                  `protobuf:"varint,3,opt,name=total_reviews,json=totalReviews,proto3" json:"total_reviews,omitempty"`
	TotalStudyTimeMs int64                  `protobuf:"varint,4,opt,name=total_study_time_ms,json=totalStudyTimeMs,proto3" json:"total_study_time_ms,omitempty"`
	CurrentStreak    int32                  `protobuf:"varint,5,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	LongestStreak    int32                  `protobuf:"varint,6,opt,name=longest_streak,json=longestStreak,proto3" json:"longest_streak,omitempty"`
	LastStudiedDate  string                 `protobuf:"bytes,7,opt,name=last_studied_date,json=lastStudiedDate,proto3" json:"last_studied_date,omitempty"`
	TotalCorrect     int32                  `protobuf:"varint,8,opt,name=total_correct,json=totalCorrect,proto3" json:"total_correct,omitempty"`
	TotalIncorrect   int32                  `protobuf:"varint,9,opt,name=total_incorrect,json=totalIncorrect,proto3" json:"total_incorrect,omitempty"`
	Username         string                 `protobuf:"bytes,10,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl        string                 `protobuf:"bytes,11,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	mi := &file_stats_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{3}
}

func (x *UserStats) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserStats) GetTotalCards() int32 {
	if x != nil {
		return x.TotalCards
	}
	return 0
}

func (x *UserStats) GetTotalReviews() int32 {
	if x != nil {
		return x.TotalReviews
	}
	return 0
}

func (x *UserStats) GetTotalStudyTimeMs() int64 {
	if x != nil {
		return x.TotalStudyTimeMs
	}
	return 0
}

func (x *UserStats) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *UserStats) GetLongestStreak() int32 {
	if x != nil {
		return x.LongestStreak
	}
	return 0
}

func (x *UserStats) GetLastStudiedDate() string {
	if x != nil {
		return x.LastStudiedDate
	}
	return ""
}

func (x *UserStats) GetTotalCorrect() int32 {
	if x != nil {
		return x.TotalCorrect
	}
	return 0
}

func (x *UserStats) GetTotalIncorrect() int32 {
	if x != nil {
		return x.TotalIncorrect
	}
	return 0
}

func (x *UserStats) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserStats) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserStats) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetMyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyStatsRequest) Reset() {
	*x = GetMyStatsRequest{}
	mi := &file_stats_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyStatsRequest) ProtoMessage() {}

func (x *GetMyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMyStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{4}
}

type GetMyStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *UserStats             `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyStatsResponse) Reset() {
	*x = GetMyStatsResponse{}
	mi := &file_stats_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyStatsResponse) ProtoMessage() {}

func (x *GetMyStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyStatsResponse.ProtoReflect.Descriptor instead.
func (*GetMyStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetMyStatsResponse) GetStats() *UserStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type DailyStatEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudyDate     string                 `protobuf:"bytes,1,opt,name=study_date,json=studyDate,proto3" json:"study_date,omitempty"`
	ReviewsCount  int32                  `protobuf:"varint,2,opt,name=reviews_count,json=reviewsCount,proto3" json:"reviews_count,omitempty"`
	NewCardsCount int32                  `protobuf:"varint,3,opt,name=new_cards_count,json=newCardsCount,proto3" json:"new_cards_count,omitempty"`
	StudyTimeMs   int64                  `protobuf:"varint,4,opt,name=study_time_ms,json=studyTimeMs,proto3" json:"study_time_ms,omitempty"`
	CorrectCount  int32                  `protobuf:"varint,5,opt,name=correct_count,json=correctCount,proto3" json:"correct_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyStatEntry) Reset() {
	*x = DailyStatEntry{}
	mi := &file_stats_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStatEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStatEntry) ProtoMessage() {}

func (x *DailyStatEntry) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStatEntry.ProtoReflect.Descriptor instead.
func (*DailyStatEntry) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{6}
}

func (x *DailyStatEntry) GetStudyDate() string {
	if x != nil {
		return x.StudyDate
	}
	return ""
}

func (x *DailyStatEntry) GetReviewsCount() int32 {
	if x != nil {
		return x.ReviewsCount
	}
	return 0
}

func (x *DailyStatEntry) GetNewCardsCount() int32 {
	if x != nil {
		return x.NewCardsCount
	}
	return 0
}

func (x *DailyStatEntry) GetStudyTimeMs() int64 {
	if x != nil {
		return x.StudyTimeMs
	}
	return 0
}

func (x *DailyStatEntry) GetCorrectCount() int32 {
	if x != nil {
		return x.CorrectCount
	}
	return 0
}

type GetHeatmapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromDate      string                 `protobuf:"bytes,1,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,2,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeatmapRequest) Reset() {
	*x = GetHeatmapRequest{}
	mi := &file_stats_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeatmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeatmapRequest) ProtoMessage() {}

func (x *GetHeatmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeatmapRequest.ProtoReflect.Descriptor instead.
func (*GetHeatmapRequest) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetHeatmapRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GetHeatmapRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type GetHeatmapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DailyStatEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeatmapResponse) Reset() {
	*x = GetHeatmapResponse{}
	mi := &file_stats_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeatmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeatmapResponse) ProtoMessage() {}

func (x *GetHeatmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeatmapResponse.ProtoReflect.Descriptor instead.
func (*GetHeatmapResponse) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetHeatmapResponse) GetEntries() []*DailyStatEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DeckStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalCards    int32                  `protobuf:"varint,3,opt,name=total_cards,json=totalCards,proto3" json:"total_cards,omitempty"`
	NewCards      int32                  `protobuf:"varint,4,opt,name=new_cards,json=newCards,proto3" json:"new_cards,omitempty"`
	LearningCards int32                  `protobuf:"varint,5,opt,name=learning_cards,json=learningCards,proto3" json:"learning_cards,omitempty"`
	ReviewCards   int32                  `protobuf:"varint,6,opt,name=review_cards,json=reviewCards,proto3" json:"review_cards,omitempty"`
	MasteredCards int32                  `protobuf:"varint,7,opt,name=mastered_cards,json=masteredCards,proto3" json:"mastered_cards,omitempty"`
	DueToday      int32                  `protobuf:"varint,8,opt,name=due_today,json=dueToday,proto3" json:"due_today,omitempty"`
	DeckName      string                 `protobuf:"bytes,9,opt,name=deck_name,json=deckName,proto3" json:"deck_name,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckStat) Reset() {
	*x = DeckStat{}
	mi := &file_stats_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckStat) ProtoMessage() {}

func (x *DeckStat) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckStat.ProtoReflect.Descriptor instead.
func (*DeckStat) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeckStat) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *DeckStat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeckStat) GetTotalCards() int32 {
	if x != nil {
		return x.TotalCards
	}
	return 0
}

func (x *DeckStat) GetNewCards() int32 {
	if x != nil {
		return x.NewCards
	}
	return 0
}

func (x *DeckStat) GetLearningCards() int32 {
	if x != nil {
		return x.LearningCards
	}
	return 0
}

func (x *DeckStat) GetReviewCards() int32 {
	if x != nil {
		return x.ReviewCards
	}
	return 0
}

func (x *DeckStat) GetMasteredCards() int32 {
	if x != nil {
		return x.MasteredCards
	}
	return 0
}

func (x *DeckStat) GetDueToday() int32 {
	if x != nil {
		return x.DueToday
	}
	return 0
}

func (x *DeckStat) GetDeckName() string {
	if x != nil {
		return x.DeckName
	}
	return ""
}

func (x *DeckStat) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetDeckStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeckStatsRequest) Reset() {
	*x = GetDeckStatsRequest{}
	mi := &file_stats_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeckStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeckStatsRequest) ProtoMessage() {}

func (x *GetDeckStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeckStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDeckStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetDeckStatsRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

type GetDeckStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *DeckStat              `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeckStatsResponse) Reset() {
	*x = GetDeckStatsResponse{}
	mi := &file_stats_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeckStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeckStatsResponse) ProtoMessage() {}

func (x *GetDeckStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeckStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDeckStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetDeckStatsResponse) GetStats() *DeckStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ListMyDeckStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyDeckStatsRequest) Reset() {
	*x = ListMyDeckStatsRequest{}
	mi := &file_stats_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyDeckStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyDeckStatsRequest) ProtoMessage() {}

func (x *ListMyDeckStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyDeckStatsRequest.ProtoReflect.Descriptor instead.
func (*ListMyDeckStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{12}
}

type ListMyDeckStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decks         []*DeckStat            `protobuf:"bytes,1,rep,name=decks,proto3" json:"decks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyDeckStatsResponse) Reset() {
	*x = ListMyDeckStatsResponse{}
	mi := &file_stats_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyDeckStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyDeckStatsResponse) ProtoMessage() {}

func (x *ListMyDeckStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyDeckStatsResponse.ProtoReflect.Descriptor instead.
func (*ListMyDeckStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListMyDeckStatsResponse) GetDecks() []*DeckStat {
	if x != nil {
		return x.Decks
	}
	return nil
}

type DeckProgressEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotDate  string                 `protobuf:"bytes,1,opt,name=snapshot_date,json=snapshotDate,proto3" json:"snapshot_date,omitempty"`
	NewCount      int32                  `protobuf:"varint,2,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`
	LearningCount int32                  `protobuf:"varint,3,opt,name=learning_count,json=learningCount,proto3" json:"learning_count,omitempty"`
	ReviewCount   int32                  `protobuf:"varint,4,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	MasteredCount int32                  `protobuf:"varint,5,opt,name=mastered_count,json=masteredCount,proto3" json:"mastered_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckProgressEntry) Reset() {
	*x = DeckProgressEntry{}
	mi := &file_stats_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckProgressEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckProgressEntry) ProtoMessage() {}

func (x *DeckProgressEntry) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckProgressEntry.ProtoReflect.Descriptor instead.
func (*DeckProgressEntry) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeckProgressEntry) GetSnapshotDate() string {
	if x != nil {
		return x.SnapshotDate
	}
	return ""
}

func (x *DeckProgressEntry) GetNewCount() int32 {
	if x != nil {
		return x.NewCount
	}
	return 0
}

func (x *DeckProgressEntry) GetLearningCount() int32 {
	if x != nil {
		return x.LearningCount
	}
	return 0
}

func (x *DeckProgressEntry) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *DeckProgressEntry) GetMasteredCount() int32 {
	if x != nil {
		return x.MasteredCount
	}
	return 0
}

type GetDeckProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeckId        string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeckProgressRequest) Reset() {
	*x = GetDeckProgressRequest{}
	mi := &file_stats_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeckProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeckProgressRequest) ProtoMessage() {}

func (x *GetDeckProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeckProgressRequest.ProtoReflect.Descriptor instead.
func (*GetDeckProgressRequest) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetDeckProgressRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *GetDeckProgressRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GetDeckProgressRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type GetDeckProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DeckProgressEntry   `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeckProgressResponse) Reset() {
	*x = GetDeckProgressResponse{}
	mi := &file_stats_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeckProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeckProgressResponse) ProtoMessage() {}

func (x *GetDeckProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeckProgressResponse.ProtoReflect.Descriptor instead.
func (*GetDeckProgressResponse) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetDeckProgressResponse) GetEntries() []*DeckProgressEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_stats_service_proto protoreflect.FileDescriptor

const file_stats_service_proto_rawDesc = "" +
	"\n" +
	"\x13stats_service.proto\x12\x05stats\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x93\x02\n" +
	"\x11UserReminderState\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ecurrent_streak\x18\x02 \x01(\x05R\rcurrentStreak\x12*\n" +
	"\x11last_studied_date\x18\x03 \x01(\tR\x0flastStudiedDate\x120\n" +
	"\x14optimal_hour_weekday\x18\x04 \x01(\x05R\x12optimalHourWeekday\x120\n" +
	"\x14optimal_hour_weekend\x18\x05 \x01(\x05R\x12optimalHourWeekend\x12.\n" +
	"\x13reminder_local_time\x18\x06 \x01(\tR\x11reminderLocalTime\"H\n" +
	"\x18ListReminderStateRequest\x12,\n" +
	"\x12only_active_streak\x18\x01 \x01(\bR\x10onlyActiveStreak\"K\n" +
	"\x19ListReminderStateResponse\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.stats.UserReminderStateR\x05users\"\xbb\x03\n" +
	"\tUserStats\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtotal_cards\x18\x02 \x01(\x05R\n" +
	"totalCards\x12#\n" +
	"\rtotal_reviews\x18\x03 \x01(\x05R\ftotalReviews\x12-\n" +
	"\x13total_study_time_ms\x18\x04 \x01(\x03R\x10totalStudyTimeMs\x12%\n" +
	"\x0ecurrent_streak\x18\x05 \x01(\x05R\rcurrentStreak\x12%\n" +
	"\x0elongest_streak\x18\x06 \x01(\x05R\rlongestStreak\x12*\n" +
	"\x11last_studied_date\x18\a \x01(\tR\x0flastStudiedDate\x12#\n" +
	"\rtotal_correct\x18\b \x01(\x05R\ftotalCorrect\x12'\n" +
	"\x0ftotal_incorrect\x18\t \x01(\x05R\x0etotalIncorrect\x12\x1a\n" +
	"\busername\x18\n" +
	" \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\v \x01(\tR\tavatarUrl\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\x13\n" +
	"\x11GetMyStatsRequest\"<\n" +
	"\x12GetMyStatsResponse\x12&\n" +
	"\x05stats\x18\x01 \x01(\v2\x10.stats.UserStatsR\x05stats\"\xc5\x01\n" +
	"\x0eDailyStatEntry\x12\x1d\n" +
	"\n" +
	"study_date\x18\x01 \x01(\tR\tstudyDate\x12#\n" +
	"\rreviews_count\x18\x02 \x01(\x05R\freviewsCount\x12&\n" +
	"\x0fnew_cards_count\x18\x03 \x01(\x05R\rnewCardsCount\x12\"\n" +
	"\rstudy_time_ms\x18\x04 \x01(\x03R\vstudyTimeMs\x12#\n" +
	"\rcorrect_count\x18\x05 \x01(\x05R\fcorrectCount\"I\n" +
	"\x11GetHeatmapRequest\x12\x1b\n" +
	"\tfrom_date\x18\x01 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x02 \x01(\tR\x06toDate\"E\n" +
	"\x12GetHeatmapResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.stats.DailyStatEntryR\aentries\"\xc4\x02\n" +
	"\bDeckStat\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtotal_cards\x18\x03 \x01(\x05R\n" +
	"totalCards\x12\x1b\n" +
	"\tnew_cards\x18\x04 \x01(\x05R\bnewCards\x12%\n" +
	"\x0elearning_cards\x18\x05 \x01(\x05R\rlearningCards\x12!\n" +
	"\freview_cards\x18\x06 \x01(\x05R\vreviewCards\x12%\n" +
	"\x0emastered_cards\x18\a \x01(\x05R\rmasteredCards\x12\x1b\n" +
	"\tdue_today\x18\b \x01(\x05R\bdueToday\x12\x1b\n" +
	"\tdeck_name\x18\t \x01(\tR\bdeckName\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\".\n" +
	"\x13GetDeckStatsRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\"=\n" +
	"\x14GetDeckStatsResponse\x12%\n" +
	"\x05stats\x18\x01 \x01(\v2\x0f.stats.DeckStatR\x05stats\"\x18\n" +
	"\x16ListMyDeckStatsRequest\"@\n" +
	"\x17ListMyDeckStatsResponse\x12%\n" +
	"\x05decks\x18\x01 \x03(\v2\x0f.stats.DeckStatR\x05decks\"\xc6\x01\n" +
	"\x11DeckProgressEntry\x12#\n" +
	"\rsnapshot_date\x18\x01 \x01(\tR\fsnapshotDate\x12\x1b\n" +
	"\tnew_count\x18\x02 \x01(\x05R\bnewCount\x12%\n" +
	"\x0elearning_count\x18\x03 \x01(\x05R\rlearningCount\x12!\n" +
	"\freview_count\x18\x04 \x01(\x05R\vreviewCount\x12%\n" +
	"\x0emastered_count\x18\x05 \x01(\x05R\rmasteredCount\"g\n" +
	"\x16GetDeckProgressRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\"M\n" +
	"\x17GetDeckProgressResponse\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.stats.DeckProgressEntryR\aentries2\xcd\a\n" +
	"\fStatsService\x12\x93\x01\n" +
	"\n" +
	"GetMyStats\x12\x18.stats.GetMyStatsRequest\x1a\x19.stats.GetMyStatsResponse\"P\x92A9\n" +
	"\x05stats\x12\x1eGet current user overall statsb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/stats/me\x12\xa5\x01\n" +
	"\n" +
	"GetHeatmap\x12\x18.stats.GetHeatmapRequest\x1a\x19.stats.GetHeatmapResponse\"b\x92AC\n" +
	"\x05stats\x12(Get daily study heatmap for a date rangeb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/stats/me/heatmap\x12\xa5\x01\n" +
	"\fGetDeckStats\x12\x1a.stats.GetDeckStatsRequest\x1a\x1b.stats.GetDeckStatsResponse\"\\\x92A8\n" +
	"\x05stats\x12\x1dGet stats for a specific deckb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/stats/decks/{deck_id}\x12\xbc\x01\n" +
	"\x0fListMyDeckStats\x12\x1d.stats.ListMyDeckStatsRequest\x1a\x1e.stats.ListMyDeckStatsResponse\"j\x92AM\n" +
	"\x05stats\x122List stats for all decks owned by the current userb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/stats/me/decks\x12\xbf\x01\n" +
	"\x0fGetDeckProgress\x12\x1d.stats.GetDeckProgressRequest\x1a\x1e.stats.GetDeckProgressResponse\"m\x92A@\n" +
	"\x05stats\x12%Get deck card-state progress timelineb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02$\x12\"/v1/stats/decks/{deck_id}/progress\x12V\n" +
	"\x11ListReminderState\x12\x1f.stats.ListReminderStateRequest\x1a .stats.ListReminderStateResponseB\x89\x01\x92Ac\x12\x18\n" +
	"\x11Stats Service API2\x031.02\x10application/json:\x10application/jsonZ#\n" +
	"!\n" +
	"\n" +
	"BearerAuth\x12\x13\b\x02\x1a\rAuthorization \x02Z!mem_pan/services/stats-service/pbb\x06proto3"

var (
	file_stats_service_proto_rawDescOnce sync.Once
	file_stats_service_proto_rawDescData []byte
)

func file_stats_service_proto_rawDescGZIP() []byte {
	file_stats_service_proto_rawDescOnce.Do(func() {
		file_stats_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_service_proto_rawDesc), len(file_stats_service_proto_rawDesc)))
	})
	return file_stats_service_proto_rawDescData
}

var file_stats_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_stats_service_proto_goTypes = []any{
	(*UserReminderState)(nil),         // 0: stats.UserReminderState
	(*ListReminderStateRequest)(nil),  // 1: stats.ListReminderStateRequest
	(*ListReminderStateResponse)(nil), // 2: stats.ListReminderStateResponse
	(*UserStats)(nil),                 // 3: stats.UserStats
	(*GetMyStatsRequest)(nil),         // 4: stats.GetMyStatsRequest
	(*GetMyStatsResponse)(nil),        // 5: stats.GetMyStatsResponse
	(*DailyStatEntry)(nil),            // 6: stats.DailyStatEntry
	(*GetHeatmapRequest)(nil),         // 7: stats.GetHeatmapRequest
	(*GetHeatmapResponse)(nil),        // 8: stats.GetHeatmapResponse
	(*DeckStat)(nil),                  // 9: stats.DeckStat
	(*GetDeckStatsRequest)(nil),       // 10: stats.GetDeckStatsRequest
	(*GetDeckStatsResponse)(nil),      // 11: stats.GetDeckStatsResponse
	(*ListMyDeckStatsRequest)(nil),    // 12: stats.ListMyDeckStatsRequest
	(*ListMyDeckStatsResponse)(nil),   // 13: stats.ListMyDeckStatsResponse
	(*DeckProgressEntry)(nil),         // 14: stats.DeckProgressEntry
	(*GetDeckProgressRequest)(nil),    // 15: stats.GetDeckProgressRequest
	(*GetDeckProgressResponse)(nil),   // 16: stats.GetDeckProgressResponse
}
var file_stats_service_proto_depIdxs = []int32{
	0,  // 0: stats.ListReminderStateResponse.users:type_name -> stats.UserReminderState
	3,  // 1: stats.GetMyStatsResponse.stats:type_name -> stats.UserStats
	6,  // 2: stats.GetHeatmapResponse.entries:type_name -> stats.DailyStatEntry
	9,  // 3: stats.GetDeckStatsResponse.stats:type_name -> stats.DeckStat
	9,  // 4: stats.ListMyDeckStatsResponse.decks:type_name -> stats.DeckStat
	14, // 5: stats.GetDeckProgressResponse.entries:type_name -> stats.DeckProgressEntry
	4,  // 6: stats.StatsService.GetMyStats:input_type -> stats.GetMyStatsRequest
	7,  // 7: stats.StatsService.GetHeatmap:input_type -> stats.GetHeatmapRequest
	10, // 8: stats.StatsService.GetDeckStats:input_type -> stats.GetDeckStatsRequest
	12, // 9: stats.StatsService.ListMyDeckStats:input_type -> stats.ListMyDeckStatsRequest
	15, // 10: stats.StatsService.GetDeckProgress:input_type -> stats.GetDeckProgressRequest
	1,  // 11: stats.StatsService.ListReminderState:input_type -> stats.ListReminderStateRequest
	5,  // 12: stats.StatsService.GetMyStats:output_type -> stats.GetMyStatsResponse
	8,  // 13: stats.StatsService.GetHeatmap:output_type -> stats.GetHeatmapResponse
	11, // 14: stats.StatsService.GetDeckStats:output_type -> stats.GetDeckStatsResponse
	13, // 15: stats.StatsService.ListMyDeckStats:output_type -> stats.ListMyDeckStatsResponse
	16, // 16: stats.StatsService.GetDeckProgress:output_type -> stats.GetDeckProgressResponse
	2,  // 17: stats.StatsService.ListReminderState:output_type -> stats.ListReminderStateResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_stats_service_proto_init() }
func file_stats_service_proto_init() {
	if File_stats_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_service_proto_rawDesc), len(file_stats_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_service_proto_goTypes,
		DependencyIndexes: file_stats_service_proto_depIdxs,
		MessageInfos:      file_stats_service_proto_msgTypes,
	}.Build()
	File_stats_service_proto = out.File
	file_stats_service_proto_goTypes = nil
	file_stats_service_proto_depIdxs = nil
}
