// Code generated by MockGen. DO NOT EDIT.
// Source: mem_pan/services/auth-service/internal/repository (interfaces: VerificationTokenRepository)

package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	db "mem_pan/services/auth-service/internal/db"
)

type MockVerificationTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationTokenRepositoryMockRecorder
}

type MockVerificationTokenRepositoryMockRecorder struct {
	mock *MockVerificationTokenRepository
}

func NewMockVerificationTokenRepository(ctrl *gomock.Controller) *MockVerificationTokenRepository {
	mock := &MockVerificationTokenRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationTokenRepositoryMockRecorder{mock}
	return mock
}

func (m *MockVerificationTokenRepository) EXPECT() *MockVerificationTokenRepositoryMockRecorder {
	return m.recorder
}

func (m *MockVerificationTokenRepository) CreateVerificationToken(ctx context.Context, userID uuid.UUID, tokenHash, tokenType string, expiresAt time.Time) (db.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerificationToken", ctx, userID, tokenHash, tokenType, expiresAt)
	ret0, _ := ret[0].(db.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockVerificationTokenRepositoryMockRecorder) CreateVerificationToken(ctx, userID, tokenHash, tokenType, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerificationToken", reflect.TypeOf((*MockVerificationTokenRepository)(nil).CreateVerificationToken), ctx, userID, tokenHash, tokenType, expiresAt)
}

func (m *MockVerificationTokenRepository) GetByHash(ctx context.Context, tokenHash string) (db.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", ctx, tokenHash)
	ret0, _ := ret[0].(db.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockVerificationTokenRepositoryMockRecorder) GetByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockVerificationTokenRepository)(nil).GetByHash), ctx, tokenHash)
}

func (m *MockVerificationTokenRepository) MarkUsed(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockVerificationTokenRepositoryMockRecorder) MarkUsed(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockVerificationTokenRepository)(nil).MarkUsed), ctx, tokenHash)
}

func (m *MockVerificationTokenRepository) DeleteExpiredForUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredForUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockVerificationTokenRepositoryMockRecorder) DeleteExpiredForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredForUser", reflect.TypeOf((*MockVerificationTokenRepository)(nil).DeleteExpiredForUser), ctx, userID)
}
