// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc_ban_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ban           bool                   `protobuf:"varint,2,opt,name=ban,proto3" json:"ban,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserRequest) Reset() {
	*x = BanUserRequest{}
	mi := &file_rpc_ban_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserRequest) ProtoMessage() {}

func (x *BanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ban_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserRequest.ProtoReflect.Descriptor instead.
func (*BanUserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_ban_user_proto_rawDescGZIP(), []int{0}
}

func (x *BanUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BanUserRequest) GetBan() bool {
	if x != nil {
		return x.Ban
	}
	return false
}

func (x *BanUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsBanned      bool                   `protobuf:"varint,4,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserResponse) Reset() {
	*x = BanUserResponse{}
	mi := &file_rpc_ban_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserResponse) ProtoMessage() {}

func (x *BanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_ban_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserResponse.ProtoReflect.Descriptor instead.
func (*BanUserResponse) Descriptor() ([]byte, []int) {
	return file_rpc_ban_user_proto_rawDescGZIP(), []int{1}
}

func (x *BanUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BanUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BanUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BanUserResponse) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

var File_rpc_ban_user_proto protoreflect.FileDescriptor

const file_rpc_ban_user_proto_rawDesc = "" +
	"\n" +
	"\x12rpc_ban_user.proto\x12\x02pb\"S\n" +
	"\x0eBanUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03ban\x18\x02 \x01(\bR\x03ban\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"y\n" +
	"\x0fBanUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tis_banned\x18\x04 \x01(\bR\bisBannedB\"Z mem_pan/services/auth-service/pbb\x06proto3"

var (
	file_rpc_ban_user_proto_rawDescOnce sync.Once
	file_rpc_ban_user_proto_rawDescData []byte
)

func file_rpc_ban_user_proto_rawDescGZIP() []byte {
	file_rpc_ban_user_proto_rawDescOnce.Do(func() {
		file_rpc_ban_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_ban_user_proto_rawDesc), len(file_rpc_ban_user_proto_rawDesc)))
	})
	return file_rpc_ban_user_proto_rawDescData
}

var file_rpc_ban_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_ban_user_proto_goTypes = []any{
	(*BanUserRequest)(nil),  // 0: pb.BanUserRequest
	(*BanUserResponse)(nil), // 1: pb.BanUserResponse
}
var file_rpc_ban_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_ban_user_proto_init() }
func file_rpc_ban_user_proto_init() {
	if File_rpc_ban_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_ban_user_proto_rawDesc), len(file_rpc_ban_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_ban_user_proto_goTypes,
		DependencyIndexes: file_rpc_ban_user_proto_depIdxs,
		MessageInfos:      file_rpc_ban_user_proto_msgTypes,
	}.Build()
	File_rpc_ban_user_proto = out.File
	file_rpc_ban_user_proto_goTypes = nil
	file_rpc_ban_user_proto_depIdxs = nil
}
