// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc_get_user_by_id.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_rpc_get_user_by_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_user_by_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_user_by_id_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDResponse) Reset() {
	*x = GetUserByIDResponse{}
	mi := &file_rpc_get_user_by_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDResponse) ProtoMessage() {}

func (x *GetUserByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_user_by_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIDResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_user_by_id_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByIDResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_rpc_get_user_by_id_proto protoreflect.FileDescriptor

const file_rpc_get_user_by_id_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_get_user_by_id.proto\x12\x02pb\x1a\n" +
	"user.proto\"-\n" +
	"\x12GetUserByIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x13GetUserByIDResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x01(\v2\b.pb.UserR\x04userB\"Z mem_pan/services/auth-service/pbb\x06proto3"

var (
	file_rpc_get_user_by_id_proto_rawDescOnce sync.Once
	file_rpc_get_user_by_id_proto_rawDescData []byte
)

func file_rpc_get_user_by_id_proto_rawDescGZIP() []byte {
	file_rpc_get_user_by_id_proto_rawDescOnce.Do(func() {
		file_rpc_get_user_by_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_user_by_id_proto_rawDesc), len(file_rpc_get_user_by_id_proto_rawDesc)))
	})
	return file_rpc_get_user_by_id_proto_rawDescData
}

var file_rpc_get_user_by_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_user_by_id_proto_goTypes = []any{
	(*GetUserByIDRequest)(nil),  // 0: pb.GetUserByIDRequest
	(*GetUserByIDResponse)(nil), // 1: pb.GetUserByIDResponse
	(*User)(nil),                // 2: pb.User
}
var file_rpc_get_user_by_id_proto_depIdxs = []int32{
	2, // 0: pb.GetUserByIDResponse.user:type_name -> pb.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_user_by_id_proto_init() }
func file_rpc_get_user_by_id_proto_init() {
	if File_rpc_get_user_by_id_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_user_by_id_proto_rawDesc), len(file_rpc_get_user_by_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_user_by_id_proto_goTypes,
		DependencyIndexes: file_rpc_get_user_by_id_proto_depIdxs,
		MessageInfos:      file_rpc_get_user_by_id_proto_msgTypes,
	}.Build()
	File_rpc_get_user_by_id_proto = out.File
	file_rpc_get_user_by_id_proto_goTypes = nil
	file_rpc_get_user_by_id_proto_depIdxs = nil
}
