// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rpc_update_user_plus_status.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateUserPlusStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsPlus        bool                   `protobuf:"varint,2,opt,name=is_plus,json=isPlus,proto3" json:"is_plus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPlusStatusRequest) Reset() {
	*x = UpdateUserPlusStatusRequest{}
	mi := &file_rpc_update_user_plus_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPlusStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPlusStatusRequest) ProtoMessage() {}

func (x *UpdateUserPlusStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_user_plus_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPlusStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPlusStatusRequest) Descriptor() ([]byte, []int) {
	return file_rpc_update_user_plus_status_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateUserPlusStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserPlusStatusRequest) GetIsPlus() bool {
	if x != nil {
		return x.IsPlus
	}
	return false
}

type UpdateUserPlusStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPlusStatusResponse) Reset() {
	*x = UpdateUserPlusStatusResponse{}
	mi := &file_rpc_update_user_plus_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPlusStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPlusStatusResponse) ProtoMessage() {}

func (x *UpdateUserPlusStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_user_plus_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPlusStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserPlusStatusResponse) Descriptor() ([]byte, []int) {
	return file_rpc_update_user_plus_status_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserPlusStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpc_update_user_plus_status_proto protoreflect.FileDescriptor

const file_rpc_update_user_plus_status_proto_rawDesc = "" +
	"\n" +
	"!rpc_update_user_plus_status.proto\x12\x02pb\"O\n" +
	"\x1bUpdateUserPlusStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\ais_plus\x18\x02 \x01(\bR\x06isPlus\"8\n" +
	"\x1cUpdateUserPlusStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\"Z mem_pan/services/auth-service/pbb\x06proto3"

var (
	file_rpc_update_user_plus_status_proto_rawDescOnce sync.Once
	file_rpc_update_user_plus_status_proto_rawDescData []byte
)

func file_rpc_update_user_plus_status_proto_rawDescGZIP() []byte {
	file_rpc_update_user_plus_status_proto_rawDescOnce.Do(func() {
		file_rpc_update_user_plus_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_update_user_plus_status_proto_rawDesc), len(file_rpc_update_user_plus_status_proto_rawDesc)))
	})
	return file_rpc_update_user_plus_status_proto_rawDescData
}

var file_rpc_update_user_plus_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_update_user_plus_status_proto_goTypes = []any{
	(*UpdateUserPlusStatusRequest)(nil),  // 0: pb.UpdateUserPlusStatusRequest
	(*UpdateUserPlusStatusResponse)(nil), // 1: pb.UpdateUserPlusStatusResponse
}
var file_rpc_update_user_plus_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_update_user_plus_status_proto_init() }
func file_rpc_update_user_plus_status_proto_init() {
	if File_rpc_update_user_plus_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_update_user_plus_status_proto_rawDesc), len(file_rpc_update_user_plus_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_update_user_plus_status_proto_goTypes,
		DependencyIndexes: file_rpc_update_user_plus_status_proto_depIdxs,
		MessageInfos:      file_rpc_update_user_plus_status_proto_msgTypes,
	}.Build()
	File_rpc_update_user_plus_status_proto = out.File
	file_rpc_update_user_plus_status_proto_goTypes = nil
	file_rpc_update_user_plus_status_proto_depIdxs = nil
}
