// Code generated by MockGen. DO NOT EDIT.
// Source: mem_pan/services/study-service/internal/deckclient (interfaces: Client)

package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	deckclient "mem_pan/services/study-service/internal/deckclient"
)

type MockDeckClient struct {
	ctrl     *gomock.Controller
	recorder *MockDeckClientMockRecorder
}

type MockDeckClientMockRecorder struct {
	mock *MockDeckClient
}

func NewMockDeckClient(ctrl *gomock.Controller) *MockDeckClient {
	mock := &MockDeckClient{ctrl: ctrl}
	mock.recorder = &MockDeckClientMockRecorder{mock}
	return mock
}

func (m *MockDeckClient) EXPECT() *MockDeckClientMockRecorder {
	return m.recorder
}

func (m *MockDeckClient) GetDeck(ctx context.Context, deckID uuid.UUID, accessToken string) (deckclient.DeckInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeck", ctx, deckID, accessToken)
	ret0, _ := ret[0].(deckclient.DeckInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDeckClientMockRecorder) GetDeck(ctx, deckID, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeck", reflect.TypeOf((*MockDeckClient)(nil).GetDeck), ctx, deckID, accessToken)
}

func (m *MockDeckClient) ListDeckCards(ctx context.Context, deckID uuid.UUID, accessToken string) ([]deckclient.CardInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeckCards", ctx, deckID, accessToken)
	ret0, _ := ret[0].([]deckclient.CardInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDeckClientMockRecorder) ListDeckCards(ctx, deckID, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeckCards", reflect.TypeOf((*MockDeckClient)(nil).ListDeckCards), ctx, deckID, accessToken)
}

func (m *MockDeckClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockDeckClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDeckClient)(nil).Close))
}
