// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: report.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countReports = `-- name: CountReports :one
SELECT COUNT(*) FROM reports
WHERE status = COALESCE($1, status)
`

func (q *Queries) CountReports(ctx context.Context, statusFilter NullReportStatus) (int64, error) {
	row := q.queryRow(ctx, q.countReportsStmt, countReports, statusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createModerationLog = `-- name: CreateModerationLog :one
INSERT INTO moderation_logs (
    admin_id,
    action,
    target_type,
    target_id,
    reason,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING log_id, admin_id, action, target_type, target_id, reason, metadata, created_at
`

type CreateModerationLogParams struct {
	AdminID    uuid.UUID             `json:"admin_id"`
	Action     string                `json:"action"`
	TargetType string                `json:"target_type"`
	TargetID   uuid.UUID             `json:"target_id"`
	Reason     sql.NullString        `json:"reason"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateModerationLog(ctx context.Context, arg CreateModerationLogParams) (ModerationLog, error) {
	row := q.queryRow(ctx, q.createModerationLogStmt, createModerationLog,
		arg.AdminID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.Metadata,
	)
	var i ModerationLog
	err := row.Scan(
		&i.LogID,
		&i.AdminID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    reporter_id,
    target_type,
    target_id,
    reason_category,
    description
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING report_id, reporter_id, target_type, target_id, reason_category, description, status, assigned_to, admin_note, resolution, resolved_by, resolved_at, created_at, updated_at
`

type CreateReportParams struct {
	ReporterID     uuid.UUID        `json:"reporter_id"`
	TargetType     ReportTargetType `json:"target_type"`
	TargetID       uuid.UUID        `json:"target_id"`
	ReasonCategory ReportCategory   `json:"reason_category"`
	Description    sql.NullString   `json:"description"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.queryRow(ctx, q.createReportStmt, createReport,
		arg.ReporterID,
		arg.TargetType,
		arg.TargetID,
		arg.ReasonCategory,
		arg.Description,
	)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.ReasonCategory,
		&i.Description,
		&i.Status,
		&i.AssignedTo,
		&i.AdminNote,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT report_id, reporter_id, target_type, target_id, reason_category, description, status, assigned_to, admin_note, resolution, resolved_by, resolved_at, created_at, updated_at FROM reports
WHERE report_id = $1 LIMIT 1
`

func (q *Queries) GetReport(ctx context.Context, reportID uuid.UUID) (Report, error) {
	row := q.queryRow(ctx, q.getReportStmt, getReport, reportID)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.ReasonCategory,
		&i.Description,
		&i.Status,
		&i.AssignedTo,
		&i.AdminNote,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT report_id, reporter_id, target_type, target_id, reason_category, description, status, assigned_to, admin_note, resolution, resolved_by, resolved_at, created_at, updated_at FROM reports
WHERE status = COALESCE($3, status)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListReportsParams struct {
	Limit        int32            `json:"limit"`
	Offset       int32            `json:"offset"`
	StatusFilter NullReportStatus `json:"status_filter"`
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	rows, err := q.query(ctx, q.listReportsStmt, listReports, arg.Limit, arg.Offset, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ReportID,
			&i.ReporterID,
			&i.TargetType,
			&i.TargetID,
			&i.ReasonCategory,
			&i.Description,
			&i.Status,
			&i.AssignedTo,
			&i.AdminNote,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE reports
SET
    status = $2,
    resolution = COALESCE($3, resolution),
    admin_note = COALESCE($4, admin_note),
    resolved_by = COALESCE($5, resolved_by),
    resolved_at = CASE WHEN $2::report_status IN ('resolved', 'dismissed') THEN CURRENT_TIMESTAMP ELSE resolved_at END,
    updated_at = CURRENT_TIMESTAMP
WHERE report_id = $1
RETURNING report_id, reporter_id, target_type, target_id, reason_category, description, status, assigned_to, admin_note, resolution, resolved_by, resolved_at, created_at, updated_at
`

type UpdateReportStatusParams struct {
	ReportID   uuid.UUID      `json:"report_id"`
	Status     ReportStatus   `json:"status"`
	Resolution sql.NullString `json:"resolution"`
	AdminNote  sql.NullString `json:"admin_note"`
	ResolvedBy uuid.NullUUID  `json:"resolved_by"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.queryRow(ctx, q.updateReportStatusStmt, updateReportStatus,
		arg.ReportID,
		arg.Status,
		arg.Resolution,
		arg.AdminNote,
		arg.ResolvedBy,
	)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.ReasonCategory,
		&i.Description,
		&i.Status,
		&i.AssignedTo,
		&i.AdminNote,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
