// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const upsertFCMToken = `-- name: UpsertFCMToken :one
INSERT INTO fcm_tokens (user_id, token, device_name)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE
    SET user_id     = EXCLUDED.user_id,
        device_name = EXCLUDED.device_name,
        updated_at  = NOW()
RETURNING id, user_id, token, device_name, created_at, updated_at
`

type UpsertFCMTokenParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Token      string    `json:"token"`
	DeviceName string    `json:"device_name"`
}

func (q *Queries) UpsertFCMToken(ctx context.Context, arg UpsertFCMTokenParams) (FcmToken, error) {
	row := q.db.QueryRowContext(ctx, upsertFCMToken, arg.UserID, arg.Token, arg.DeviceName)
	var t FcmToken
	err := row.Scan(&t.ID, &t.UserID, &t.Token, &t.DeviceName, &t.CreatedAt, &t.UpdatedAt)
	return t, err
}

const deleteFCMToken = `-- name: DeleteFCMToken :exec
DELETE FROM fcm_tokens WHERE token = $1 AND user_id = $2
`

type DeleteFCMTokenParams struct {
	Token  string    `json:"token"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteFCMToken(ctx context.Context, arg DeleteFCMTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteFCMToken, arg.Token, arg.UserID)
	return err
}

const listFCMTokensByUser = `-- name: ListFCMTokensByUser :many
SELECT id, user_id, token, device_name, created_at, updated_at FROM fcm_tokens WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListFCMTokensByUser(ctx context.Context, userID uuid.UUID) ([]FcmToken, error) {
	rows, err := q.db.QueryContext(ctx, listFCMTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FcmToken
	for rows.Next() {
		var t FcmToken
		if err := rows.Scan(&t.ID, &t.UserID, &t.Token, &t.DeviceName, &t.CreatedAt, &t.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, t)
	}
	return items, rows.Err()
}

const logNotification = `-- name: LogNotification :exec
INSERT INTO notification_log (user_id, notification_type, channel, recipient, status, error_message)
VALUES ($1, $2, $3, $4, $5, $6)
`

type LogNotificationParams struct {
	UserID           *uuid.UUID `json:"user_id"`
	NotificationType string     `json:"notification_type"`
	Channel          string     `json:"channel"`
	Recipient        string     `json:"recipient"`
	Status           string     `json:"status"`
	ErrorMessage     *string    `json:"error_message"`
}

func (q *Queries) LogNotification(ctx context.Context, arg LogNotificationParams) error {
	_, err := q.db.ExecContext(ctx, logNotification,
		arg.UserID, arg.NotificationType, arg.Channel, arg.Recipient, arg.Status, arg.ErrorMessage,
	)
	return err
}

const countRecentNotifications = `-- name: CountRecentNotifications :one
SELECT COUNT(*)::bigint
FROM notification_log
WHERE user_id           = $1
  AND notification_type = $2
  AND status            = 'sent'
  AND created_at        >= $3
`

type CountRecentNotificationsParams struct {
	UserID           *uuid.UUID `json:"user_id"`
	NotificationType string     `json:"notification_type"`
	CreatedAt        time.Time  `json:"created_at"`
}

func (q *Queries) CountRecentNotifications(ctx context.Context, arg CountRecentNotificationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentNotifications, arg.UserID, arg.NotificationType, arg.CreatedAt)
	var n int64
	err := row.Scan(&n)
	return n, err
}
