// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: study_models.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCardState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserCardId     string                 `protobuf:"bytes,1,opt,name=user_card_id,json=userCardId,proto3" json:"user_card_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardId         string                 `protobuf:"bytes,3,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	DeckId         string                 `protobuf:"bytes,4,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	State          string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Stability      float64                `protobuf:"fixed64,6,opt,name=stability,proto3" json:"stability,omitempty"`
	Difficulty     float64                `protobuf:"fixed64,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Reps           int32                  `protobuf:"varint,8,opt,name=reps,proto3" json:"reps,omitempty"`
	Lapses         int32                  `protobuf:"varint,9,opt,name=lapses,proto3" json:"lapses,omitempty"`
	ScheduledDays  int32                  `protobuf:"varint,10,opt,name=scheduled_days,json=scheduledDays,proto3" json:"scheduled_days,omitempty"`
	NextReviewDate *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=next_review_date,json=nextReviewDate,proto3" json:"next_review_date,omitempty"`
	LastReviewDate *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_review_date,json=lastReviewDate,proto3" json:"last_review_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserCardState) Reset() {
	*x = UserCardState{}
	mi := &file_study_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCardState) ProtoMessage() {}

func (x *UserCardState) ProtoReflect() protoreflect.Message {
	mi := &file_study_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCardState.ProtoReflect.Descriptor instead.
func (*UserCardState) Descriptor() ([]byte, []int) {
	return file_study_models_proto_rawDescGZIP(), []int{0}
}

func (x *UserCardState) GetUserCardId() string {
	if x != nil {
		return x.UserCardId
	}
	return ""
}

func (x *UserCardState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCardState) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *UserCardState) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *UserCardState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UserCardState) GetStability() float64 {
	if x != nil {
		return x.Stability
	}
	return 0
}

func (x *UserCardState) GetDifficulty() float64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *UserCardState) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

func (x *UserCardState) GetLapses() int32 {
	if x != nil {
		return x.Lapses
	}
	return 0
}

func (x *UserCardState) GetScheduledDays() int32 {
	if x != nil {
		return x.ScheduledDays
	}
	return 0
}

func (x *UserCardState) GetNextReviewDate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextReviewDate
	}
	return nil
}

func (x *UserCardState) GetLastReviewDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReviewDate
	}
	return nil
}

type SessionCardItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	CardId        string                 `protobuf:"bytes,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	UserCardId    string                 `protobuf:"bytes,3,opt,name=user_card_id,json=userCardId,proto3" json:"user_card_id,omitempty"`
	Reviewed      bool                   `protobuf:"varint,4,opt,name=reviewed,proto3" json:"reviewed,omitempty"`
	Rating        int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCardItem) Reset() {
	*x = SessionCardItem{}
	mi := &file_study_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCardItem) ProtoMessage() {}

func (x *SessionCardItem) ProtoReflect() protoreflect.Message {
	mi := &file_study_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCardItem.ProtoReflect.Descriptor instead.
func (*SessionCardItem) Descriptor() ([]byte, []int) {
	return file_study_models_proto_rawDescGZIP(), []int{1}
}

func (x *SessionCardItem) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *SessionCardItem) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *SessionCardItem) GetUserCardId() string {
	if x != nil {
		return x.UserCardId
	}
	return ""
}

func (x *SessionCardItem) GetReviewed() bool {
	if x != nil {
		return x.Reviewed
	}
	return false
}

func (x *SessionCardItem) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type StudySession struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeckId         string                 `protobuf:"bytes,3,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	TotalCards     int32                  `protobuf:"varint,5,opt,name=total_cards,json=totalCards,proto3" json:"total_cards,omitempty"`
	CompletedCards int32                  `protobuf:"varint,6,opt,name=completed_cards,json=completedCards,proto3" json:"completed_cards,omitempty"`
	Cards          []*SessionCardItem     `protobuf:"bytes,7,rep,name=cards,proto3" json:"cards,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StudySession) Reset() {
	*x = StudySession{}
	mi := &file_study_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudySession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudySession) ProtoMessage() {}

func (x *StudySession) ProtoReflect() protoreflect.Message {
	mi := &file_study_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudySession.ProtoReflect.Descriptor instead.
func (*StudySession) Descriptor() ([]byte, []int) {
	return file_study_models_proto_rawDescGZIP(), []int{2}
}

func (x *StudySession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StudySession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StudySession) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *StudySession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StudySession) GetTotalCards() int32 {
	if x != nil {
		return x.TotalCards
	}
	return 0
}

func (x *StudySession) GetCompletedCards() int32 {
	if x != nil {
		return x.CompletedCards
	}
	return 0
}

func (x *StudySession) GetCards() []*SessionCardItem {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *StudySession) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StudySession) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type DueCard struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CardId         string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	DeckId         string                 `protobuf:"bytes,2,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	UserCardId     string                 `protobuf:"bytes,3,opt,name=user_card_id,json=userCardId,proto3" json:"user_card_id,omitempty"`
	State          string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	NextReviewDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=next_review_date,json=nextReviewDate,proto3" json:"next_review_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DueCard) Reset() {
	*x = DueCard{}
	mi := &file_study_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DueCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DueCard) ProtoMessage() {}

func (x *DueCard) ProtoReflect() protoreflect.Message {
	mi := &file_study_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DueCard.ProtoReflect.Descriptor instead.
func (*DueCard) Descriptor() ([]byte, []int) {
	return file_study_models_proto_rawDescGZIP(), []int{3}
}

func (x *DueCard) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *DueCard) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *DueCard) GetUserCardId() string {
	if x != nil {
		return x.UserCardId
	}
	return ""
}

func (x *DueCard) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DueCard) GetNextReviewDate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextReviewDate
	}
	return nil
}

type RecentDeckItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeckId         string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	LastAccessedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_accessed_at,json=lastAccessedAt,proto3" json:"last_accessed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecentDeckItem) Reset() {
	*x = RecentDeckItem{}
	mi := &file_study_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentDeckItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentDeckItem) ProtoMessage() {}

func (x *RecentDeckItem) ProtoReflect() protoreflect.Message {
	mi := &file_study_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentDeckItem.ProtoReflect.Descriptor instead.
func (*RecentDeckItem) Descriptor() ([]byte, []int) {
	return file_study_models_proto_rawDescGZIP(), []int{4}
}

func (x *RecentDeckItem) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *RecentDeckItem) GetLastAccessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccessedAt
	}
	return nil
}

type ProgressTag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	CardIds       []string               `protobuf:"bytes,3,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressTag) Reset() {
	*x = ProgressTag{}
	mi := &file_study_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressTag) ProtoMessage() {}

func (x *ProgressTag) ProtoReflect() protoreflect.Message {
	mi := &file_study_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressTag.ProtoReflect.Descriptor instead.
func (*ProgressTag) Descriptor() ([]byte, []int) {
	return file_study_models_proto_rawDescGZIP(), []int{5}
}

func (x *ProgressTag) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ProgressTag) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ProgressTag) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

type DeckProgressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeckId         string                 `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	NewCount       int32                  `protobuf:"varint,2,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`
	LearnCount     int32                  `protobuf:"varint,3,opt,name=learn_count,json=learnCount,proto3" json:"learn_count,omitempty"`
	MemorizedCount int32                  `protobuf:"varint,4,opt,name=memorized_count,json=memorizedCount,proto3" json:"memorized_count,omitempty"`
	TotalCount     int32                  `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Tags           []*ProgressTag         `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// Soonest next_review_date among the user's non-new cards in this deck.
	// Unset when the deck has no scheduled (non-new) cards yet. The client
	// renders the countdown from this absolute timestamp.
	NextReviewDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=next_review_date,json=nextReviewDate,proto3" json:"next_review_date,omitempty"`
	// Number of non-new cards already due (next_review_date <= now).
	DueNow        int32 `protobuf:"varint,8,opt,name=due_now,json=dueNow,proto3" json:"due_now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckProgressResponse) Reset() {
	*x = DeckProgressResponse{}
	mi := &file_study_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckProgressResponse) ProtoMessage() {}

func (x *DeckProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_study_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckProgressResponse.ProtoReflect.Descriptor instead.
func (*DeckProgressResponse) Descriptor() ([]byte, []int) {
	return file_study_models_proto_rawDescGZIP(), []int{6}
}

func (x *DeckProgressResponse) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *DeckProgressResponse) GetNewCount() int32 {
	if x != nil {
		return x.NewCount
	}
	return 0
}

func (x *DeckProgressResponse) GetLearnCount() int32 {
	if x != nil {
		return x.LearnCount
	}
	return 0
}

func (x *DeckProgressResponse) GetMemorizedCount() int32 {
	if x != nil {
		return x.MemorizedCount
	}
	return 0
}

func (x *DeckProgressResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *DeckProgressResponse) GetTags() []*ProgressTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DeckProgressResponse) GetNextReviewDate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextReviewDate
	}
	return nil
}

func (x *DeckProgressResponse) GetDueNow() int32 {
	if x != nil {
		return x.DueNow
	}
	return 0
}

type StudySettings struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	ShuffleTerms                 bool                   `protobuf:"varint,1,opt,name=shuffle_terms,json=shuffleTerms,proto3" json:"shuffle_terms,omitempty"`
	TextToSpeech                 bool                   `protobuf:"varint,2,opt,name=text_to_speech,json=textToSpeech,proto3" json:"text_to_speech,omitempty"`
	AnswerWithTerm               bool                   `protobuf:"varint,3,opt,name=answer_with_term,json=answerWithTerm,proto3" json:"answer_with_term,omitempty"`
	AnswerWithDefinition         bool                   `protobuf:"varint,4,opt,name=answer_with_definition,json=answerWithDefinition,proto3" json:"answer_with_definition,omitempty"`
	QuestionTypeFlashcards       bool                   `protobuf:"varint,5,opt,name=question_type_flashcards,json=questionTypeFlashcards,proto3" json:"question_type_flashcards,omitempty"`
	QuestionTypeMultipleChoice   bool                   `protobuf:"varint,6,opt,name=question_type_multiple_choice,json=questionTypeMultipleChoice,proto3" json:"question_type_multiple_choice,omitempty"`
	QuestionTypeWritten          bool                   `protobuf:"varint,7,opt,name=question_type_written,json=questionTypeWritten,proto3" json:"question_type_written,omitempty"`
	StrictnessLevel              string                 `protobuf:"bytes,8,opt,name=strictness_level,json=strictnessLevel,proto3" json:"strictness_level,omitempty"`
	RequireRetypingCorrectAnswer bool                   `protobuf:"varint,9,opt,name=require_retyping_correct_answer,json=requireRetypingCorrectAnswer,proto3" json:"require_retyping_correct_answer,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *StudySettings) Reset() {
	*x = StudySettings{}
	mi := &file_study_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudySettings) ProtoMessage() {}

func (x *StudySettings) ProtoReflect() protoreflect.Message {
	mi := &file_study_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudySettings.ProtoReflect.Descriptor instead.
func (*StudySettings) Descriptor() ([]byte, []int) {
	return file_study_models_proto_rawDescGZIP(), []int{7}
}

func (x *StudySettings) GetShuffleTerms() bool {
	if x != nil {
		return x.ShuffleTerms
	}
	return false
}

func (x *StudySettings) GetTextToSpeech() bool {
	if x != nil {
		return x.TextToSpeech
	}
	return false
}

func (x *StudySettings) GetAnswerWithTerm() bool {
	if x != nil {
		return x.AnswerWithTerm
	}
	return false
}

func (x *StudySettings) GetAnswerWithDefinition() bool {
	if x != nil {
		return x.AnswerWithDefinition
	}
	return false
}

func (x *StudySettings) GetQuestionTypeFlashcards() bool {
	if x != nil {
		return x.QuestionTypeFlashcards
	}
	return false
}

func (x *StudySettings) GetQuestionTypeMultipleChoice() bool {
	if x != nil {
		return x.QuestionTypeMultipleChoice
	}
	return false
}

func (x *StudySettings) GetQuestionTypeWritten() bool {
	if x != nil {
		return x.QuestionTypeWritten
	}
	return false
}

func (x *StudySettings) GetStrictnessLevel() string {
	if x != nil {
		return x.StrictnessLevel
	}
	return ""
}

func (x *StudySettings) GetRequireRetypingCorrectAnswer() bool {
	if x != nil {
		return x.RequireRetypingCorrectAnswer
	}
	return false
}

var File_study_models_proto protoreflect.FileDescriptor

const file_study_models_proto_rawDesc = "" +
	"\n" +
	"\x12study_models.proto\x12\x05study\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x03\n" +
	"\rUserCardState\x12 \n" +
	"\fuser_card_id\x18\x01 \x01(\tR\n" +
	"userCardId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\acard_id\x18\x03 \x01(\tR\x06cardId\x12\x17\n" +
	"\adeck_id\x18\x04 \x01(\tR\x06deckId\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1c\n" +
	"\tstability\x18\x06 \x01(\x01R\tstability\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\x01R\n" +
	"difficulty\x12\x12\n" +
	"\x04reps\x18\b \x01(\x05R\x04reps\x12\x16\n" +
	"\x06lapses\x18\t \x01(\x05R\x06lapses\x12%\n" +
	"\x0escheduled_days\x18\n" +
	" \x01(\x05R\rscheduledDays\x12D\n" +
	"\x10next_review_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0enextReviewDate\x12D\n" +
	"\x10last_review_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0elastReviewDate\"\x9c\x01\n" +
	"\x0fSessionCardItem\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\tR\x06cardId\x12 \n" +
	"\fuser_card_id\x18\x03 \x01(\tR\n" +
	"userCardId\x12\x1a\n" +
	"\breviewed\x18\x04 \x01(\bR\breviewed\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\"\xe7\x02\n" +
	"\fStudySession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\adeck_id\x18\x03 \x01(\tR\x06deckId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_cards\x18\x05 \x01(\x05R\n" +
	"totalCards\x12'\n" +
	"\x0fcompleted_cards\x18\x06 \x01(\x05R\x0ecompletedCards\x12,\n" +
	"\x05cards\x18\a \x03(\v2\x16.study.SessionCardItemR\x05cards\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xb9\x01\n" +
	"\aDueCard\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x17\n" +
	"\adeck_id\x18\x02 \x01(\tR\x06deckId\x12 \n" +
	"\fuser_card_id\x18\x03 \x01(\tR\n" +
	"userCardId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12D\n" +
	"\x10next_review_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0enextReviewDate\"o\n" +
	"\x0eRecentDeckItem\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12D\n" +
	"\x10last_accessed_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastAccessedAt\"T\n" +
	"\vProgressTag\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x19\n" +
	"\bcard_ids\x18\x03 \x03(\tR\acardIds\"\xbe\x02\n" +
	"\x14DeckProgressResponse\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\tR\x06deckId\x12\x1b\n" +
	"\tnew_count\x18\x02 \x01(\x05R\bnewCount\x12\x1f\n" +
	"\vlearn_count\x18\x03 \x01(\x05R\n" +
	"learnCount\x12'\n" +
	"\x0fmemorized_count\x18\x04 \x01(\x05R\x0ememorizedCount\x12\x1f\n" +
	"\vtotal_count\x18\x05 \x01(\x05R\n" +
	"totalCount\x12&\n" +
	"\x04tags\x18\x06 \x03(\v2\x12.study.ProgressTagR\x04tags\x12D\n" +
	"\x10next_review_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0enextReviewDate\x12\x17\n" +
	"\adue_now\x18\b \x01(\x05R\x06dueNow\"\xdd\x03\n" +
	"\rStudySettings\x12#\n" +
	"\rshuffle_terms\x18\x01 \x01(\bR\fshuffleTerms\x12$\n" +
	"\x0etext_to_speech\x18\x02 \x01(\bR\ftextToSpeech\x12(\n" +
	"\x10answer_with_term\x18\x03 \x01(\bR\x0eanswerWithTerm\x124\n" +
	"\x16answer_with_definition\x18\x04 \x01(\bR\x14answerWithDefinition\x128\n" +
	"\x18question_type_flashcards\x18\x05 \x01(\bR\x16questionTypeFlashcards\x12A\n" +
	"\x1dquestion_type_multiple_choice\x18\x06 \x01(\bR\x1aquestionTypeMultipleChoice\x122\n" +
	"\x15question_type_written\x18\a \x01(\bR\x13questionTypeWritten\x12)\n" +
	"\x10strictness_level\x18\b \x01(\tR\x0fstrictnessLevel\x12E\n" +
	"\x1frequire_retyping_correct_answer\x18\t \x01(\bR\x1crequireRetypingCorrectAnswerB#Z!mem_pan/services/study-service/pbb\x06proto3"

var (
	file_study_models_proto_rawDescOnce sync.Once
	file_study_models_proto_rawDescData []byte
)

func file_study_models_proto_rawDescGZIP() []byte {
	file_study_models_proto_rawDescOnce.Do(func() {
		file_study_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_study_models_proto_rawDesc), len(file_study_models_proto_rawDesc)))
	})
	return file_study_models_proto_rawDescData
}

var file_study_models_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_study_models_proto_goTypes = []any{
	(*UserCardState)(nil),         // 0: study.UserCardState
	(*SessionCardItem)(nil),       // 1: study.SessionCardItem
	(*StudySession)(nil),          // 2: study.StudySession
	(*DueCard)(nil),               // 3: study.DueCard
	(*RecentDeckItem)(nil),        // 4: study.RecentDeckItem
	(*ProgressTag)(nil),           // 5: study.ProgressTag
	(*DeckProgressResponse)(nil),  // 6: study.DeckProgressResponse
	(*StudySettings)(nil),         // 7: study.StudySettings
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_study_models_proto_depIdxs = []int32{
	8, // 0: study.UserCardState.next_review_date:type_name -> google.protobuf.Timestamp
	8, // 1: study.UserCardState.last_review_date:type_name -> google.protobuf.Timestamp
	1, // 2: study.StudySession.cards:type_name -> study.SessionCardItem
	8, // 3: study.StudySession.started_at:type_name -> google.protobuf.Timestamp
	8, // 4: study.StudySession.finished_at:type_name -> google.protobuf.Timestamp
	8, // 5: study.DueCard.next_review_date:type_name -> google.protobuf.Timestamp
	8, // 6: study.RecentDeckItem.last_accessed_at:type_name -> google.protobuf.Timestamp
	5, // 7: study.DeckProgressResponse.tags:type_name -> study.ProgressTag
	8, // 8: study.DeckProgressResponse.next_review_date:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_study_models_proto_init() }
func file_study_models_proto_init() {
	if File_study_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_study_models_proto_rawDesc), len(file_study_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_study_models_proto_goTypes,
		DependencyIndexes: file_study_models_proto_depIdxs,
		MessageInfos:      file_study_models_proto_msgTypes,
	}.Build()
	File_study_models_proto = out.File
	file_study_models_proto_goTypes = nil
	file_study_models_proto_depIdxs = nil
}
