// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: notification_service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterDeviceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DeviceName    string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceTokenRequest) Reset() {
	*x = RegisterDeviceTokenRequest{}
	mi := &file_notification_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceTokenRequest) ProtoMessage() {}

func (x *RegisterDeviceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceTokenRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceTokenRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDeviceTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterDeviceTokenRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type RegisterDeviceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceTokenResponse) Reset() {
	*x = RegisterDeviceTokenResponse{}
	mi := &file_notification_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceTokenResponse) ProtoMessage() {}

func (x *RegisterDeviceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceTokenResponse.ProtoReflect.Descriptor instead.
func (*RegisterDeviceTokenResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterDeviceTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnregisterDeviceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceTokenRequest) Reset() {
	*x = UnregisterDeviceTokenRequest{}
	mi := &file_notification_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceTokenRequest) ProtoMessage() {}

func (x *UnregisterDeviceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceTokenRequest.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceTokenRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterDeviceTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UnregisterDeviceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceTokenResponse) Reset() {
	*x = UnregisterDeviceTokenResponse{}
	mi := &file_notification_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceTokenResponse) ProtoMessage() {}

func (x *UnregisterDeviceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceTokenResponse.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceTokenResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_rawDescGZIP(), []int{3}
}

var File_notification_service_proto protoreflect.FileDescriptor

const file_notification_service_proto_rawDesc = "" +
	"\n" +
	"\x1anotification_service.proto\x12\fnotification\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"S\n" +
	"\x1aRegisterDeviceTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\"7\n" +
	"\x1bRegisterDeviceTokenResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\x1cUnregisterDeviceTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x1f\n" +
	"\x1dUnregisterDeviceTokenResponse2\xca\x03\n" +
	"\x13NotificationService\x12\xd1\x01\n" +
	"\x13RegisterDeviceToken\x12(.notification.RegisterDeviceTokenRequest\x1a).notification.RegisterDeviceTokenResponse\"e\x92A>\n" +
	"\rnotifications\x12\x1bRegister a device FCM tokenb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/notifications/devices\x12\xde\x01\n" +
	"\x15UnregisterDeviceToken\x12*.notification.UnregisterDeviceTokenRequest\x1a+.notification.UnregisterDeviceTokenResponse\"l\x92A@\n" +
	"\rnotifications\x12\x1dUnregister a device FCM tokenb\x10\n" +
	"\x0e\n" +
	"\n" +
	"BearerAuth\x12\x00\x82\xd3\xe4\x93\x02#*!/v1/notifications/devices/{token}B\x97\x01\x92Aj\x12\x1f\n" +
	"\x18Notification Service API2\x031.02\x10application/json:\x10application/jsonZ#\n" +
	"!\n" +
	"\n" +
	"BearerAuth\x12\x13\b\x02\x1a\rAuthorization \x02Z(mem_pan/services/notification-service/pbb\x06proto3"

var (
	file_notification_service_proto_rawDescOnce sync.Once
	file_notification_service_proto_rawDescData []byte
)

func file_notification_service_proto_rawDescGZIP() []byte {
	file_notification_service_proto_rawDescOnce.Do(func() {
		file_notification_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_service_proto_rawDesc), len(file_notification_service_proto_rawDesc)))
	})
	return file_notification_service_proto_rawDescData
}

var file_notification_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notification_service_proto_goTypes = []any{
	(*RegisterDeviceTokenRequest)(nil),    // 0: notification.RegisterDeviceTokenRequest
	(*RegisterDeviceTokenResponse)(nil),   // 1: notification.RegisterDeviceTokenResponse
	(*UnregisterDeviceTokenRequest)(nil),  // 2: notification.UnregisterDeviceTokenRequest
	(*UnregisterDeviceTokenResponse)(nil), // 3: notification.UnregisterDeviceTokenResponse
}
var file_notification_service_proto_depIdxs = []int32{
	0, // 0: notification.NotificationService.RegisterDeviceToken:input_type -> notification.RegisterDeviceTokenRequest
	2, // 1: notification.NotificationService.UnregisterDeviceToken:input_type -> notification.UnregisterDeviceTokenRequest
	1, // 2: notification.NotificationService.RegisterDeviceToken:output_type -> notification.RegisterDeviceTokenResponse
	3, // 3: notification.NotificationService.UnregisterDeviceToken:output_type -> notification.UnregisterDeviceTokenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_service_proto_init() }
func file_notification_service_proto_init() {
	if File_notification_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_service_proto_rawDesc), len(file_notification_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_service_proto_goTypes,
		DependencyIndexes: file_notification_service_proto_depIdxs,
		MessageInfos:      file_notification_service_proto_msgTypes,
	}.Build()
	File_notification_service_proto = out.File
	file_notification_service_proto_goTypes = nil
	file_notification_service_proto_depIdxs = nil
}
