// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deck_progress.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listDeckProgressSnapshots = `-- name: ListDeckProgressSnapshots :many
SELECT deck_id, user_id, snapshot_date, new_count, learning_count, review_count, mastered_count FROM deck_progress_snapshots
WHERE deck_id = $1
  AND snapshot_date BETWEEN $2 AND $3
ORDER BY snapshot_date ASC
`

type ListDeckProgressSnapshotsParams struct {
	DeckID         uuid.UUID `json:"deck_id"`
	SnapshotDate   time.Time `json:"snapshot_date"`
	SnapshotDate_2 time.Time `json:"snapshot_date_2"`
}

func (q *Queries) ListDeckProgressSnapshots(ctx context.Context, arg ListDeckProgressSnapshotsParams) ([]DeckProgressSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listDeckProgressSnapshots, arg.DeckID, arg.SnapshotDate, arg.SnapshotDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeckProgressSnapshot{}
	for rows.Next() {
		var i DeckProgressSnapshot
		if err := rows.Scan(
			&i.DeckID,
			&i.UserID,
			&i.SnapshotDate,
			&i.NewCount,
			&i.LearningCount,
			&i.ReviewCount,
			&i.MasteredCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeckProgressSnapshot = `-- name: UpsertDeckProgressSnapshot :exec
INSERT INTO deck_progress_snapshots (deck_id, user_id, snapshot_date, new_count, learning_count, review_count, mastered_count)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (deck_id, user_id, snapshot_date) DO UPDATE SET
    new_count      = EXCLUDED.new_count,
    learning_count = EXCLUDED.learning_count,
    review_count   = EXCLUDED.review_count,
    mastered_count = EXCLUDED.mastered_count
`

type UpsertDeckProgressSnapshotParams struct {
	DeckID        uuid.UUID `json:"deck_id"`
	UserID        uuid.UUID `json:"user_id"`
	SnapshotDate  time.Time `json:"snapshot_date"`
	NewCount      int32     `json:"new_count"`
	LearningCount int32     `json:"learning_count"`
	ReviewCount   int32     `json:"review_count"`
	MasteredCount int32     `json:"mastered_count"`
}

func (q *Queries) UpsertDeckProgressSnapshot(ctx context.Context, arg UpsertDeckProgressSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeckProgressSnapshot,
		arg.DeckID,
		arg.UserID,
		arg.SnapshotDate,
		arg.NewCount,
		arg.LearningCount,
		arg.ReviewCount,
		arg.MasteredCount,
	)
	return err
}

const deleteDeckProgressSnapshots = `-- name: DeleteDeckProgressSnapshots :exec
DELETE FROM deck_progress_snapshots WHERE deck_id = $1 AND user_id = $2
`

type DeleteDeckProgressSnapshotsParams struct {
	DeckID uuid.UUID `json:"deck_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDeckProgressSnapshots(ctx context.Context, arg DeleteDeckProgressSnapshotsParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeckProgressSnapshots, arg.DeckID, arg.UserID)
	return err
}
