// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type DailyStat struct {
	UserID        uuid.UUID `json:"user_id"`
	StudyDate     time.Time `json:"study_date"`
	ReviewsCount  int32     `json:"reviews_count"`
	NewCardsCount int32     `json:"new_cards_count"`
	StudyTimeMs   int64     `json:"study_time_ms"`
	CorrectCount  int32     `json:"correct_count"`
}

type DeckProgressSnapshot struct {
	DeckID        uuid.UUID `json:"deck_id"`
	UserID        uuid.UUID `json:"user_id"`
	SnapshotDate  time.Time `json:"snapshot_date"`
	NewCount      int32     `json:"new_count"`
	LearningCount int32     `json:"learning_count"`
	ReviewCount   int32     `json:"review_count"`
	MasteredCount int32     `json:"mastered_count"`
}

type DeckStat struct {
	DeckID        uuid.UUID      `json:"deck_id"`
	UserID        uuid.UUID      `json:"user_id"`
	TotalCards    int32          `json:"total_cards"`
	NewCards      int32          `json:"new_cards"`
	LearningCards int32          `json:"learning_cards"`
	ReviewCards   int32          `json:"review_cards"`
	MasteredCards int32          `json:"mastered_cards"`
	DueToday      int32          `json:"due_today"`
	DeckName      sql.NullString `json:"deck_name"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type UserStat struct {
	UserID             uuid.UUID      `json:"user_id"`
	TotalCards         int32          `json:"total_cards"`
	TotalReviews       int32          `json:"total_reviews"`
	TotalStudyTimeMs   int64          `json:"total_study_time_ms"`
	CurrentStreak      int32          `json:"current_streak"`
	LongestStreak      int32          `json:"longest_streak"`
	LastStudiedDate    sql.NullTime   `json:"last_studied_date"`
	TotalCorrect       int32          `json:"total_correct"`
	TotalIncorrect     int32          `json:"total_incorrect"`
	Username           sql.NullString `json:"username"`
	AvatarUrl          sql.NullString `json:"avatar_url"`
	UpdatedAt          time.Time      `json:"updated_at"`
	OptimalHourWeekday sql.NullInt16  `json:"optimal_hour_weekday"`
	OptimalHourWeekend sql.NullInt16  `json:"optimal_hour_weekend"`
	ReminderLocalTime  string         `json:"reminder_local_time"`
}

type UserActivityBucket struct {
	UserID      uuid.UUID `json:"user_id"`
	HourOfDay   int16     `json:"hour_of_day"`
	DayType     int16     `json:"day_type"`
	ReviewCount int32     `json:"review_count"`
	UpdatedAt   time.Time `json:"updated_at"`
}
